### ISSUE TITLE
[BUG]: Sorting data on the grid view page does not have any response

### ISSUE THREAD

**Issue by retopara** [RevealBi/Reveal.Sdk#10]
### SDK Version

1.3.1

### Client Framework

HTML/JavaScript

### Server Platform

Java

### Description

Description
Step to reproduce:

1、Sorting on the grid view page does not have any response. See the gif below. 

The error message reports a column that does not exist in the data:
{
  "error": {
    "errorMessage": "ERROR: column \"_rp_aggvalue_1\" does not exist\n  Position: 144",
    "errorCode": 5
  }
}

![reveal_error](https://user-images.githubusercontent.com/425233/229085015-112fcb4c-9ca9-4827-9936-41a3dc5ea9f3.gif)

**Comment by gkaveckis** [comment]
Hi thank you for reporting the issue.
We already have and internal item for that. AB#22514. 
This one should be solved in the next release
Regards.

**Comment by brianlagunas** [comment]
This issue has been fixed and will be available in our next release.
