### ISSUE TITLE
Add API to control EditMode in the RevealView

### ISSUE THREAD

**Issue by exscalliber** [RevealBi/Reveal.Sdk#100]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to programmatically change values or change the state related to the dashboard. A few examples include: changing the dashboard title, showing/hiding the datasource selection dialog, changing the edit state to true/false, setting the auto-layout to true/false, or programmatically saving or cancelling the dashboard.

**Describe the solution you'd like**

Ideally the things Accessors will also get setters (title, auto-layout) and there will be new functions to set the dashboard state (edit, dsSelectionDialog, etc).
Here are some example functions:
editDashboard(boolean) -> sets the dashboard to edit mode
showDatasourceSelectionDialog(boolean) -> show the datasource dialog
saveDashboard(void) -> Saves the current dashboard
cancelChanges(void) -> cancels the changes made to the dashboard
autoLayout(boolean) -> sets the auto layout of the dashboard
RevealView.dashboard.title = string -> set the title of the dashboard

**Describe alternatives you've considered**

There are currently no alternatives.

**Comment by brianlagunas** [comment]
There is a lot in this single request. These will be hard to keep track of.  It would be best if you could submit requests for specific features and use cases.

For example; this request could be focused on controlling edit mode and the scenarios around it. I could see the need for the follow:
- enterEdiitMode() - places the revealView in edit mode
- onEnterEditMode - event that is invoked when edit mode is entered (what args would we need)
- exitEditModel(applyChanges: boolean) - exits edit mode, if acceptChanges is true, then any changed made during edit mode would be persisted.
- onExitEditMode - event invoked when edit mode is exited (what args would we need?)

**Comment by brianlagunas** [comment]
For the remaining items I would suggest the following:

Create a feature request to add an API for adding a new visualization. I think this is what you mean by showing the data source dialog.

Create a feature request for changing the dashboard title. For now you could use a hack to make it work by using `dashboard._dashboardModel.title("My New Title");`

CReate a feature request for setting the auto layout value. For now you can use a hack to make it work by using `dashboard._dashboardModel.useAutoLayout(true);`

**Comment by srodriguezinfragistics** [comment]
Hi! The EditMode API has been developed and is slated for release in an upcoming release cycle.
