### ISSUE TITLE
[BUG]: "Show Data Labels" is not localized

### ISSUE THREAD

**Issue by jberes** [RevealBi/Reveal.Sdk#103]
### SDK Version

Show Data Labels is not localized

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Linux

### Description

<img width="911" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/18453092/7a77ff8e-3a3b-4611-97dd-8d481fc3080f">

**Comment by gkaveckis** [comment]
Hi 
Tracked internally AB#27364
Regards.

**Comment by PVillarmarzo** [comment]
This issue has been fixed and will be released in an upcoming release.
