### ISSUE TITLE
[BUG]: canAddDateFilter on RevealView crashes 

### ISSUE THREAD

**Issue by jberes** [RevealBi/Reveal.Sdk#104]
### SDK Version

1.6

### Client Framework

HTML

### Server Platform

ASP.NET

### Operating System

Windows

### Description

set  revealView.canAddDateFilter = false; and app crashes.

<img width="1850" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/18453092/c8c3cdc1-5751-447b-91fb-e306ccc097c6">

**Comment by gkaveckis** [comment]
Hi

Tracked with AB#27402 internally

Regards.

**Comment by PVillarmarzo** [comment]
This issue has been fixed and will be released in an upcoming release.

**Comment by PVillarmarzo** [comment]
This issue has been fixed and will be released in an upcoming release.
