### ISSUE TITLE
[BUG]: Enhancements to beta tooltips feature

### ISSUE THREAD

**Issue by jberes** [RevealBi/Reveal.Sdk#106]
### SDK Version

1.6 

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

![image](https://github.com/RevealBi/Reveal.Sdk/assets/18453092/d517dc7b-5aa2-430b-8765-3dbfa2c78485)

![image](https://github.com/RevealBi/Reveal.Sdk/assets/18453092/332edfe6-6c2d-426c-9ce9-1db436bc7e38)

![image](https://github.com/RevealBi/Reveal.Sdk/assets/18453092/66717bd4-da0b-4e27-a6c5-c998595b9906)

![image](https://github.com/RevealBi/Reveal.Sdk/assets/18453092/20f0540e-37b6-461d-881b-aa15a3baebd8)

**Comment by luispandolfi** [comment]
Tracked internally with AB#27589
