### ISSUE TITLE
[BUG]: KPI vs Time - overlapping text when state changes from having data to having no data to display

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#107]
### SDK Version

1.6.0

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We have several KPI vs Time visualizations across the top of a dashboard. In my screen recording, notice the first two present data in the form of "1 / +0% vs previous year", and the next two do not have any data and display "There's no data to display."

When I change the filter to a different value, now none of the 4 visualizations have any data. All four display "There's no data to display." _But_ the first two also display "0 / +0% vs previous year" and the two texts overlap each other.

I would expect in this scenario, all four visualizations would be consistent and only display "There's no data to display."

It seems like the visualization is supposed to have 2 mutually exclusive UI states, one when there is data and one when there isn't, but once it gets data for the first time, it gets stuck and can be in 2 UI states at once from that point forward.

https://github.com/RevealBi/Reveal.Sdk/assets/136626707/4c019551-9cb3-4513-b6ec-02961a049b09

**Comment by luispandolfi** [comment]
Thanks for reporting this issue. Tracking it internally in AB#27591
