### ISSUE TITLE
[BUG]: REVEAL BI intercepts TAB events”

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#108]
### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Node.js

### Operating System

Windows

### Description

“It has been found that during the process of developing a webpage, all keyboard TAB events are being intercepted by the KEYDOWN event code of REVEAL BI, which is causing all TAB switching to be non-operational.”
![img_v2_325dddf2-bf5e-456f-bd39-fcc4f07ea74g](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/5d10938a-fbbc-4dfc-9658-0b711ea02218)

**Comment by TorreyBetts** [comment]
@suzakuzt you highlighted the code and missed the line above it. If you set `window.revealDisableKeyboardManagement` to `true` then that code doesn't execute. In the latest version 1.6.1 we have that set to true by default.
