### ISSUE TITLE
Require Method on edit button and close edit button of dashboard

### ISSUE THREAD

**Issue by JinalBhanushali21** [RevealBi/Reveal.Sdk#109]
We require method on Edit dashboard shown below image link.
https://github.com/RevealBi/Reveal.Sdk/assets/149664825/5379801c-8b67-40ae-9b5a-0e5f2ebb34af

We require another method on Close Edit dashboard shown below image link.
https://github.com/RevealBi/Reveal.Sdk/assets/149664825/5101e08f-de3e-49ff-b85b-f59718afe2df

We have disabled Dashboard filters. We want to enable dashboard filters on edit dashboard and disable it on close edit mode so that we require  method on edit dashboard and edit mode close.

**Comment by TorreyBetts** [comment]
I'm fairly certain this [recently closed issue](https://github.com/RevealBi/Reveal.Sdk/issues/100) with a feature request that will be released in December fits what you're trying to accomplish. If it doesn't feel free to open this feature request back up and leave some further details.
