### ISSUE TITLE
[BUG]: Global filter configuration returns no value when searching for selected values.

### ISSUE THREAD

**Issue by retopara** [RevealBi/Reveal.Sdk#11]
### SDK Version

1.3.1

### Client Framework

Angular

### Server Platform

ASP.NET

### Description

Description
Step to reproduce, see the GIF for details:
1、configure an existing global filter
2、switch to a second data sheet
3、filter type -> selected value
4、search for value, 289 values returned, but the list is showing nothing.

![reveal_error4](https://user-images.githubusercontent.com/425233/229113890-a777405e-df8c-4d93-ac07-5b55c3dd60a9.gif)

**Comment by brianlagunas** [comment]
Also, if you could provide which browser you are using.

**Comment by suzakuzt** [comment]
> Hi @retopara, I tried to replicate the issue without success. Could you provide some sample data to replicate it? Does it happens only for Postgress datasource? Maybe you can try exporting data to an excel file, is easier to share. Thank you.

hi:The description I provided last time may not have been clear enough to understand the issue, so I will describe the steps to reproduce it again.
There is no issue when creating a visual filter and conducting a search normally.

The steps to reproduce the issue are as follows
1."Create three visual filters in the edit interface."
2.Select one of the filters to conduct a search, input a value that does not exist, and before the search results pop up, click on a blank space to close the pop-up window.

![image](https://user-images.githubusercontent.com/37360991/230526456-97dc589b-3dae-46ea-8a0f-e9890d2f4d67.png)

3.After closing the pop-up window, switch to another data filter for field B, input a value that does not exist, and then input an existing value. It is noticed that only the number of search results is displayed in the list without showing the corresponding field information.

![TESTBUG](https://user-images.githubusercontent.com/37360991/230526945-5b13c720-3161-4102-91dc-69b72c0ca95c.gif)

**Comment by brianlagunas** [comment]
I am closing this issue as it has had no response. This issue can be reopened if a response is received.
