### ISSUE TITLE
Child dashboard filters should be applied to parent dashboard filters

### ISSUE THREAD

**Issue by JinalBhanushali21** [RevealBi/Reveal.Sdk#111]
Parent dashboard filters are applied to child dashboard but when user move to child dashboard and apply filters on child dashboard that filters are not applied to parent dashboard when comes to parent dashboard.

**Comment by brianlagunas** [comment]
Thank you for the request, but this is not a feature we will be implementing. Dashboard linking is designed to only pass the filters to the dashboard being linked, not passing filters from the child back to the parent when the back button is clicked.
