### ISSUE TITLE
[BUG]: REVEAL BI International Language Issue

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#112]
### SDK Version

1.5.0

### Client Framework

Other

### Server Platform

Java

### Operating System

Windows

### Description

REVEAL BI currently does not display table information based on the language settings of the browser, but rather according to the language of the operating system on which the backend is deployed. As a result, even if I have set a certain language in my browser, the VIEW DATA table in REVEAL BI will ultimately be displayed according to the language of the deployed operating system. This can cause significant inconvenience for users. 

![RevealBIissue](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/fe026514-5455-462a-8f07-e145a08006aa)

**Comment by TorreyBetts** [comment]
@suzakuzt By table information, are you referring to the column names? Those originate from the data source and not something we can localize. We do have an [client event named "onFieldsInitializing"](https://help.revealbi.io/web/release-notes#all-platforms-7) where you can edit those names if you wish.

**Comment by brianlagunas** [comment]
As Torrey pointed out, we cannot automatically translate the data coming from your data sources. However, we do allow you to provide your own translations.  This is a topic we need to document, but we do have a small sample.

Please check out this sample: https://github.com/RevealBi/sdk-samples-javascript/tree/main/LocalizingDashboards
