### ISSUE TITLE
Add click listener to Scatter Map visualization

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#113]
We have a scatter map visualization like this one:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/53266b90-dc5a-4ed2-8770-c0ff1a1f84cd)

And we would like to allow users to click on the circles and have a click listener invoked, so that we can redirect the user to a more detailed page in our product. We do this already for some other visualizations, but the click listener doesn't seem to work on the Scatter Map.

**Describe the solution you'd like**

```
this.revealView.onVisualizationDataPointClicked = (rv, lat, lon) => {
    console.log("circle was clicked for data source", rv.referencedResourceDataSourceId)
    console.log("clicked location", lat, lon)
 ....
}
```

**Describe alternatives you've considered**
We have not found any alternative for this.

**Additional context**
None.

**Comment by nerzhei** [comment]
Hi @dwilches, this has been implemented and will be available in the next release.

The usage is as follows:

`revealView.onVisualizationDataPointClicked = function (visualization, cell, row) {
    console.log("Visualization Data Point Clicked");
    console.log(visualization.title);
    console.log(cell.columnLabel);
    console.log(cell.value);
    console.log(cell.formattedValue);
    console.log(row[0].columnLabel + ": " + row[0].value)
    console.log(row[1].columnLabel + ": " + row[1].value)
    console.log(row[2].columnLabel + ": " + row[2].value)
}`

![image](https://github.com/user-attachments/assets/d01dba4c-8989-4e9e-877a-3609d7b5b17f)
