### ISSUE TITLE
[BUG]: cursor "pointer" shows when hovering over "add your first visualization" when there is no click event.

### ISSUE THREAD

**Issue by exscalliber** [RevealBi/Reveal.Sdk#114]
### SDK Version

1.6.1

### Client Framework

HTML/JavaScript

### Server Platform

Node.js

### Operating System

Mac

### Description

Hi, Im unsure if there is a bug with a missing click event or if there is a UX error. When i hover over "add your first visualization" when the dashboard is in edit mode it shows a pointer cursor, indicating to me that there is a click event available. You can try it in the reveal playground [https://help.revealbi.io/playground/](https://help.revealbi.io/playground/) and then edit the visualization.

**Comment by federicoprovera** [comment]
Thanks for reporting this issue. Tracking it internally in AB#27837

**Comment by TorreyBetts** [comment]
This issue has been fixed and will be released in an upcoming release.
