### ISSUE TITLE
[BUG]: I18N issue at server side

### ISSUE THREAD

**Issue by colinzhy** [RevealBi/Reveal.Sdk#115]
### SDK Version

1.6.1

### Client Framework

HTML/JavaScript

### Server Platform

Java

### Operating System

Windows

### Description

While using Statistical Functions and checking the Detect Outliers option, the label "Is Outlier" returned by the server side is not changed by client side's language. As discussed in Discord, this is a bug that need to be fixed. Refer to below for some information:
- Use attached html file in the zip to reproduce this issue with below steps:
  - Open the page and switch to a non-English language
  - Choose any table in data source.
  - Build a chat with data displayed
  - Click the Statistical Functions icon and select the "Detect Outliers"
  - You will find the "Is Outlier" displayed on the left-top Coner of the chat(like the attached screenshot) 
[i18n-issue-for-is_outlier.zip](https://github.com/RevealBi/Reveal.Sdk/files/13345166/i18n-issue-for-is_outlier.zip)
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3828712/ce8bbedb-f938-4d72-b61d-724a9946e53a)

Additional:
- I want to know how to pass the language to the sever side for translating these internal labels.
- Currently, it seems the language of sever side is determined by the OS that it is deployed on.

**Comment by TorreyBetts** [comment]
Thanks for writing this up. Internally, we're tracking this bug as AB#27899.

**Comment by brianlagunas** [comment]
This has been fixed and should be availble.
