### ISSUE TITLE
[BUG]: new tooltips go out of the dashboards' top border

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#121]
### SDK Version

1.6.1

### Client Framework

Angular

### Server Platform

Java

### Operating System

Linux

### Description

Hello,

The new tooltips introduced in version 1.6.0 (enabled by `RevealSdkSettings.enableActionsOnHoverTooltip = true`) are being cropped in some cases like this one:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/5dc4a084-ac1c-448c-9319-0272c5ffa723)

In some cases it's easy to avoid the issue by putting the cursor further below, but in visualizations with many categories, there doesn't seem to be a way around it:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/d5cf608b-7da3-4286-9879-97a166d35cc3)

**Comment by brianlagunas** [comment]
We are aware of these as reported in #106. I am closing this as a duplicate. Please subscribe to #106 to be notified of updates to that issue.
