### ISSUE TITLE
[BUG]: Export timing out

### ISSUE THREAD

**Issue by gauxgaux** [RevealBi/Reveal.Sdk#122]
### SDK Version

1.6.0

### Client Framework

React

### Server Platform

Java

### Operating System

Mac

### Description

 It looks like there's a timeout happening when attempting to export dashboards and/or visualizations to excel. We traced it to a small race condition in the Reveal client that causes the error message here. Anyone else out there with this issue and know of a workaround? Right now the best we can tell our customers is to let the dashboard entirely load and then initiate the export function but for visualizations that have more data we're still hitting the maximum request time and they're unable to export.

We have tried downgrading to 1.5.0 as well as upgrading to 1.6.1 and the problem persists. 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/86023958/eeee8b84-bb42-4684-9e33-7e6c1b3f3184)

**Comment by brianlagunas** [comment]
Could you share the race condition, or area of the code you narrowed it down to?

**Comment by TorreyBetts** [comment]
An internal issue was created regarding this report. Tracked with AB#27964.

**Comment by gauxgaux** [comment]
My dev said he didn't identify anything in the codebase but identified the errors I attached.

**Comment by brianlagunas** [comment]
This issue has been fixed and will be available in our release next week.
