### ISSUE TITLE
[BUG]: Ability To Sort Month Labels Along a Chart Axis in Correct Date Order, Not Alphabetically

### ISSUE THREAD

**Issue by Aerobird88** [RevealBi/Reveal.Sdk#123]
### SDK Version

1.2.2.0

### Client Framework

Other

### Server Platform

ASP.NET

### Operating System

Windows

### Description

I am using the WinForms version of Reveal.  Not sure on the Server Platform selection above - I don't get into the technical side of this too much.

This is revisiting #102 from a while ago, still trying to resolve this issue.  Basically, I am combining 3 years of data to show year over year comparisons by month in a bar chart.  The panel is sorting the months alphabetically, not in correct month order.

I was able to get the sort by date field option to show in sort by, but when I try to apply it, I get an error.  I am including screenshots that show the field setup, the sort options shown, and the error I receive when I try to apply the changes.  I will also include the rdash file as well.

Thank you!

Michael
![bug1](https://github.com/RevealBi/Reveal.Sdk/assets/147091264/3dae049a-24f8-403f-bb4f-b5c4dc4a78f5)
![bug2](https://github.com/RevealBi/Reveal.Sdk/assets/147091264/8d437db7-1763-48cf-b94c-e46f59379fff)
![bug3](https://github.com/RevealBi/Reveal.Sdk/assets/147091264/3aca01cd-ee00-4972-9d5a-acd053b0bfee)

[INxSQL.zip](https://github.com/RevealBi/Reveal.Sdk/files/13394571/INxSQL.zip)

**Comment by TorreyBetts** [comment]
The error is produced because of a bad query being executed on SQL Server. Has your team tried updating to a newer version? Version 1.2.2 has to be quite old and several issues relating to this may have been fixed.

**Comment by Aerobird88** [comment]
“The error is produced because of a bad query being executed on SQL Server.”

Can you clarify this further Torrey?  I am pulling data from a single table on the SQL server that holds 3 years worth of sales data.

Thank you!

***@***.***
Michael White
Data Analyst at INxSQL Software

Phone 877-446-9775
Web www.inxsql.com<http://www.inxsql.com/>  Email ***@***.******@***.***>
1117 S Cass Lake Rd, Waterford, MI 48328


*Please note our email policy change below*
INxSQL will no longer send any banking or ACH information via email. If you require this information, please call our office directly. Please be cautious of any emailed banking information you receive from anyone, and always call to confirm numbers prior to sending funds electronically.

**Comment by TorreyBetts** [comment]
Your error is coming from SQL Server which tells me you have "Process Data on Server" enabled. When you're inside of the calculated field editor it may state that some functions are not available due to being processed on the server. The function MONTHNAME is one of the functions that is enabled when the process data on server mode is enabled. Should you disable that, then the issue may resolve. Additionally, this may be an issue that was later resolved with a bug fix and could be corrected by upgrading the SDK used.

**Comment by Aerobird88** [comment]
Changing the setting for this to no long process data on the server alleviated the error message.

The panel does now sort in the correct month order, but does not go January-December, it starts with June and ends in May.  Is there any way to force it to sort Jan-Dec?

Thank you Torrey!

***@***.***
Michael White
Data Analyst at INxSQL Software

Phone 877-446-9775
Web www.inxsql.com<http://www.inxsql.com/>  Email ***@***.******@***.***>
1117 S Cass Lake Rd, Waterford, MI 48328


*Please note our email policy change below*
INxSQL will no longer send any banking or ACH information via email. If you require this information, please call our office directly. Please be cautious of any emailed banking information you receive from anyone, and always call to confirm numbers prior to sending funds electronically.

**Comment by TorreyBetts** [comment]
Does your data start in June? Since you're now sorting by date, my guess is that the data starts in June so it's showing that month at the beginning.

**Comment by Aerobird88** [comment]
Yes, the first invoice date in the table does start in June, which makes sense.  It would be nice to have an option to force Jan-Dec sorting, but at this point what I am facing is no longer a bug but just a preference.

Thanks so much Torrey!   Greatly appreciate your help on this one.

Regards,

***@***.***
Michael White
Data Analyst at INxSQL Software

Phone 877-446-9775
Web www.inxsql.com<http://www.inxsql.com/>  Email ***@***.******@***.***>
1117 S Cass Lake Rd, Waterford, MI 48328


*Please note our email policy change below*
INxSQL will no longer send any banking or ACH information via email. If you require this information, please call our office directly. Please be cautious of any emailed banking information you receive from anyone, and always call to confirm numbers prior to sending funds electronically.
