### ISSUE TITLE
[BUG]: Pivot Grid Not Sorting  

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#125]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

Pivot grid is not sorting properly 

![Pivot Grid Sorting](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/fcae8473-88c2-448d-a273-9d2c6d41d422)

**Comment by PVillarmarzo** [comment]
Hey there! We've already received a report regarding this matter. To stay updated, you can follow the progress through this #92
