### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#126]
### SDK Version

None

### Client Framework

Angular

### Server Platform

None

### Operating System

MAC

### Description

The green KPIs show the total for the MoM metric - however, the yellow is not adding up to the green - even though they are showing the same thing, but by medium 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/63014f1e-4e47-4d41-a391-a2fd88ee3557)

We are not showing the ones that are empty in the current month: 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/1d411852-96dd-4b77-b9f4-6939dc4ec624)

We need to show them with an N/A message

**Comment by PVillarmarzo** [comment]
it is the same as #127
