### ISSUE TITLE
[BUG]: KPI vs Time Now Showing Empty Values in Current Month 

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#127]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

The green KPIs show the total for the MoM metric - however, the yellow is not adding up to the green - even though they are showing the same thing, but by medium 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/63014f1e-4e47-4d41-a391-a2fd88ee3557)

We are not showing the ones that are empty in the current month: 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/1d411852-96dd-4b77-b9f4-6939dc4ec624)

We need to show them with an N/A message

**Comment by PVillarmarzo** [comment]
An internal issue was created regarding this report. Tracked with AB#28066

**Comment by nerzhei** [comment]
Hi @CMcGuigan10,
 
We covered the scenario when the actual value exists, but the previous one doesn't.
 
 Before:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/10646282/d7a7a19c-78ad-4175-84ec-70e3a6191b35)

After:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/10646282/79b0d6b1-a690-4668-806f-d1a1e89e0b2c)

What do you suggest doing when the actual value doesn't exist? Currently, it displays "There's no data to display." We are open to suggestions.
