### ISSUE TITLE
[BUG]: showExportToPowerpoint should be showExportToPowerPoint

### ISSUE THREAD

**Issue by jberes** [RevealBi/Reveal.Sdk#129]
### SDK Version

1.6 

### Client Framework

HTML/JavaScript

### Server Platform

None

### Operating System

Windows

### Description

We should use the correct name, PowerPoint, not Powerpoint.  I discovered this in the Export sample in Developer Playground when I was demoing to a customer, PowerPoint export options shows up even though the property is set to false.

<img width="1615" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/18453092/029ac12d-6150-481a-9215-30f9cdfbed80">

**Comment by nerzhei** [comment]
Internal work item AB#28084
