### ISSUE TITLE
[BUG]: Text Box in Image Editor / Annotation Doesn't Remove "Enter Text"

### ISSUE THREAD

**Issue by jberes** [RevealBi/Reveal.Sdk#130]
### SDK Version

1.6 

### Client Framework

HTML/JavaScript

### Server Platform

None

### Operating System

Windows

### Description

When adding a Text control to the Image editor, the ghost text that says 'Enter Text' remains.  

<img width="1247" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/18453092/ee8ed015-e5ad-442c-8c85-c028222ac579">

**Comment by nerzhei** [comment]
We were unable to reproduce this bug. Could you please provide more information about your environment, including the browser you are using?

**Comment by jberes** [comment]
@nerzhei @brianlagunas It seems to only happen on Edgium.  I just tried in Chrome and there was no issue.  That's odd.  I thought they were the same.

**Comment by dpazos-infragistics** [comment]
Tested issue not present in Chrome 120.0.6099.71 or Edge version 120.0.2210.61 (latest versions as of Dec 11).

**Comment by brianlagunas** [comment]
We are still unable to replicate this issue. Is this still an issue for you?

**Comment by brianlagunas** [comment]
I'm closing as it appears we have not seen this issue since, and the team has not been able to reproduce it.
