### ISSUE TITLE
[BUG]: Postgres shows Procedures in the Functions list, and they don't work

### ISSUE THREAD

**Issue by jberes** [RevealBi/Reveal.Sdk#133]
### SDK Version

1.6 

### Client Framework

Angular

### Server Platform

None

### Operating System

Linux

### Description

We need to show an additional tab for Procedures in Postgres.  This tab combines Procedures and Functions.  When you select a Procedure to execute, it results in an error.

<img width="1036" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/18453092/e20e803a-0f35-463e-9ed1-88d71887f993">

<img width="862" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/18453092/119113af-f602-4301-8d91-b8f96611d474">

**Comment by luispandolfi** [comment]
Thanks for reporting. I link this issue to our internal User Story: AB#24818

**Comment by brianlagunas** [comment]
This has been resolved and will be available in our Feb release.
