### ISSUE TITLE
Support URL links in Grid Cells

### ISSUE THREAD

**Issue by fahadfastion** [RevealBi/Reveal.Sdk#135]
we needs Field as link from where we can navigate to any page or link. the link field should also allow us to create any custom link in Grid of dashboard.

**Comment by brianlagunas** [comment]
Just to confirm, you want to be able to display a link in a grid cell. Can you list the requirements for this feature?  For example, is displaying the url in a grid cell all that's required, or should there be text to represent the link and the url is hidden. Please provide as much information and detail as possible so we understand the requirements of the feature.

**Comment by fahadfastion** [comment]
A text we needs on Grid that should represent a link.if we wants to create
custom link on the bases of data in row we can easily do it by using custom
field development option that reveal already have , after clicking link the
link should be open in the new tab of the browser

**Comment by fahadfastion** [comment]
we don't need this option anymore linking of dashboard via URL is fulfilling our purpose 

thanks

**Comment by gkaveckis** [comment]
Hi 
It is nice you could find an alternative.
I will close this issue as it is not longer needed.
Regards.
