### ISSUE TITLE
Add Subtotals per group in Pivot Charts

### ISSUE THREAD

**Issue by nerzhei** [RevealBi/Reveal.Sdk#137]
<img width="863" alt="2023-12-20_11-29-56" src="https://github.com/RevealBi/Reveal.Sdk/assets/18453092/f74af910-309b-476b-9a2d-1df54d9a8d48">

**Comment by nerzhei** [comment]
Internal Work Item AB#28470

**Comment by brianlagunas** [comment]
The pivot grid already provides subtotals for value fields. The Pivot does not provide aggregations for dimension fields.
