### ISSUE TITLE
Improve defaults in Java SDK

### ISSUE THREAD

**Issue by jberes** [RevealBi/Reveal.Sdk#138]
**Is your feature request related to a problem? Please describe.**

In the .NET and Node SDK, we have delighter-type defaults, like Load / Save automatically to the Dashboards folder.

**Describe the solution you'd like**

I would like the same defaults in Java that exist in .NET.

**Describe alternatives you've considered**
Writing code to achieve the same.

**Additional context**
I do not know if there are other defaults in .NET except Save / Load; if there are, please include them in this FR.

**Comment by nerzhei** [comment]
Internal work item AB#28473

**Comment by brianlagunas** [comment]
This has been implemented and Java has a default DashboardProvider now
