### ISSUE TITLE
Detail Filters for Exported Data

### ISSUE THREAD

**Issue by nerzhei** [RevealBi/Reveal.Sdk#139]
- Filters should be included when exporting to Excel. Currently, there are no references to the used filters.

![image](https://github.com/RevealBi/Reveal.Sdk/assets/10646282/75d43206-c660-47cb-93cd-fce07be74559)

- When exporting to PDF, the selected values should be indicated somewhere. Currently, only the quantity of selected values is suggested.

![image](https://github.com/RevealBi/Reveal.Sdk/assets/10646282/b91e422c-1ed1-40a8-8e49-68904411eda5)

**Comment by nerzhei** [comment]
Internal work item AB#28472

**Comment by brianlagunas** [comment]
This has been implemented and will be available in our release next week.
