### ISSUE TITLE
[BUG]: When switching between the 'Data View' and 'Statistics Function' buttons in the data editing interface, the frontend will throw an error and the interface will freeze

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#14]
### Company

NA

### SDK Version

1.4.0

### Client Framework

React

### Server Platform

Java

### Description

Description
Step to reproduce:
1、Open Chrome in window mode
2、Enter the visual BI editing interface——>Click on the two buttons 'Data View' and 'Statistics Function' located in the top right corne
3、The interface may freeze after switching between the buttons for 'Data View' and 'Statistics Function', with no fixed pattern of occurrence after a single or multiple switches. Upon performing the switch operation, the frontend will display an error message in developer mode. After this, the interface will become unresponsive, preventing any actions such as dragging fields, and the only solution is to refresh the browser.
See the GIF for a recording.
![TESTBUG](https://user-images.githubusercontent.com/37360991/229518934-2616e438-0103-41ea-b620-70415897fa2c.gif)

**Comment by luispandolfi** [comment]
Hi, thank you for reporting this issue.
We could reproduce and created an internal work item for it AB#23120

The issue happens when you click the blank area between the title and the statistics icon.
Best regards.

**Comment by brianlagunas** [comment]
This issue has been fixed and will be available in the next release.
