### ISSUE TITLE
[BUG]: Fraction digits are not shown in choropleth map tooltip

### ISSUE THREAD

**Issue by fahadfastion** [RevealBi/Reveal.Sdk#141]
### SDK Version

6.0

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

1)the fraction with 2 decimal places is viewing in map, its rounding amount choropleth map
2) Singapore is missing in the map

**Comment by fahadfastion** [comment]
typo cannot see  fraction with 2 decimal places

**Comment by brianlagunas** [comment]
This bug report has no actionable information. It doesn't even have a title. Please provide more information about the bug and steps we can take to reproduce it.

**Comment by luispandolfi** [comment]
Created internal issue for the fraction digits bug. The Signapore related is not a bug or we need more information to understand it, please create another bug with more info for it.
The issue is being tracked by AB#29442

**Comment by brianlagunas** [comment]
This bug has been fixed and will be available in our next release
