### ISSUE TITLE
[BUG]: GA4 Sparkline Exceeding Limit of Rows & Columns

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#146]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/da74f945-5330-47a5-befc-38c6266f271b)

Date, Sessions, Landing Page filtered by hostname infragistics.com

**Comment by PVillarmarzo** [comment]
An internal issue was created regarding this report. Tracked with [AB#29822](https://infragistics.visualstudio.com/BusinessTools/_workitems/edit/29822)

**Comment by MLopezIG** [comment]
@CMcGuigan10 you need to ask Slingshot administrators to increase those limits for you (you need to be set as power user). Alternatively you can try filtering the results.
