### ISSUE TITLE
[BUG]: Scroll stops working on pop-up element when using search bar

### ISSUE THREAD

**Issue by bcacan** [RevealBi/Reveal.Sdk#147]
### SDK Version

1.6.1

### Client Framework

React

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Issue on client-side about unresponsive UI.

Users with lower resolutions or smaller browser viewport, tends to run into issues with pop-up container (eg. New Visualization pop-up).
Video attached.

https://github.com/RevealBi/Reveal.Sdk/assets/73470112/e1eea99f-d89c-4add-bfd0-1b14efa150f6

 - As user types search term that doesn't exist, there are 0 results in a list, but scrolling doesn't work anymore.
 - In a video I also tried 'touch' dragging, in that case it's possible to scroll, but scrollbar automatically bounces on top.

**Comment by nerzhei** [comment]
Thanks for reporting this. The issue is being tracked by AB#29431.
