### ISSUE TITLE
Reveal Sdk WPF problem referencing  Antlr4.Runtime.Standard -Version 4.7.2.0

### ISSUE THREAD

**Issue by fzandomeni** [RevealBi/Reveal.Sdk#149]
### SDK Version

1.6.3

### Client Framework

WPF

### Server Platform

None

### Operating System

Windows

### Description

The latest Reveal Sdk for WPF version 1.6.3 adds a reference to Antlr4.Runtime.Standard -Version 4.7.2.0.
This nuget package is from 2018 and is known for having problems, it can't be digitally signed.
If a reference to the latest version of Antlr4.Runtime.Standard (which at the time of this writing is 4:13.1) there is no problem signing it, but Reveal Sdk Wpf does not recognize it.
![image](https://github.com/RevealBi/Reveal.Sdk/assets/15477496/15a8936b-a0ba-43b9-ba37-e0ccae62e0f0)
![image](https://github.com/RevealBi/Reveal.Sdk/assets/15477496/c973bd56-fcf8-4e00-bbb2-4b9aae3a081f)

**Comment by nerzhei** [comment]
Thanks for reporting this, an internal work item has been created AB#29443.

**Comment by fzandomeni** [comment]
I updated to Reveal 1.6.4 and still seems to be a problem. See snapshot.
I'm using a simple query from a sql server database to the reveal dashboard within a winforms app

![image](https://github.com/RevealBi/Reveal.Sdk/assets/15477496/5ece7b78-ec51-48d3-9ba7-e6241dee1203)

**Comment by fzandomeni** [comment]
![image](https://github.com/RevealBi/Reveal.Sdk/assets/15477496/099f1d68-431a-4f3d-a208-1fd8b4e1d906)


See the details in the snapshots as the errors are different.

**Comment by fzandomeni** [comment]
Update:

After reviewing all the references, it was discovered that an incorrect version of Antlr4.Runtime.Standard was causing the problem. After fixing that, everything seems to be working fine. Thank you for your help on this.

I've been attempting to use Reveal for a few years, since its launch, and every time there is a new version, dealing with a very high number of references that periodically are missing or are very old becomes a headache. It would be beneficial to understand the purpose of each referenced library and whether they can be safely excluded if a particular dashboard does not need them.

In my specific case, I need to pay close attention to the size of my projects. Before using Reveal, a typical app (winforms) was 100MB. If I include all the stuff that Reveal adds by default, the app grows to about 700MB, which is insane and causes all sorts of deployment and maintenance problems. Through trial and error, I found that by removing many references, the final app size can be reduced to 180MB, and still, all the Reveal features that I am interested in seem to work.

**Comment by TorreyBetts** [comment]
> Update:
> 
> After reviewing all the references, it was discovered that an incorrect version of Antlr4.Runtime.Standard was causing the problem. After fixing that, everything seems to be working fine. Thank you for your help on this.
> 
> I've been attempting to use Reveal for a few years, since its launch, and every time there is a new version, dealing with a very high number of references that periodically are missing or are very old becomes a headache. It would be beneficial to understand the purpose of each referenced library and whether they can be safely excluded if a particular dashboard does not need them.
> 
> In my specific case, I need to pay close attention to the size of my projects. Before using Reveal, a typical app (winforms) was 100MB. If I include all the stuff that Reveal adds by default, the app grows to about 700MB, which is insane and causes all sorts of deployment and maintenance problems. Through trial and error, I found that by removing many references, the final app size can be reduced to 180MB, and still, all the Reveal features that I am interested in seem to work.

Which Reveal NuGet packages have you added to your project?

**Comment by fzandomeni** [comment]
I added the newest Reveal Sdk for Wpf 1.6.4, but there also was a reference to the Antlr version 4:13.1 which is newer than the one used by the current Reveal which I think is 4.8.0.0 (from early 2020). Is there any reason not to use the latest version??

**Comment by brianlagunas** [comment]
We couldn't upgrade to the latest because there were issues in the latest version. We used the version which worked for the product.
