### ISSUE TITLE
[BUG]: jQuery Conflict

### ISSUE THREAD

**Issue by ShashiChary** [RevealBi/Reveal.Sdk#150]
### SDK Version

1.3.1

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

if render both (reveal chat and date chooser) by adding jquery v3.7.0 and jQuery v1.9.1
the charts won't render , i try fixing the chart by adjust the query files
the datechooser fails

The consensus was that JQuery controls and Reveal are not supported to work together on the same page due to their dependencies on different versions of JQuery. Reveal is only supported with the other facets of Ignite UI (e.g. Web Components / React / Angular / etc.)

**Comment by brianlagunas** [comment]
Correct. Reveal is not supported with the older jQuery Dev Tools components. To get around this issues, you need to host your RevealView pages in an iFrame. This is not something we will be addressing in the DevTools.

**Comment by brianlagunas** [comment]
Another option is to use the Web Components instead of the jQuery components.
