### ISSUE TITLE
[BUG]: Google Analytics Filters Error on Loading 

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#152]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

I am getting an error to load filters on GA4 

I am also getting signed out a from the data source a lot - then getting stuck in an endless loop of trying to reconnect. Video sent via other channel since it was too large to attach here.

**Comment by TorreyBetts** [comment]
Internally being tracked as AB#29591

**Comment by nerzhei** [comment]
Hi @CMcGuigan10, this issue has been fixed and will be included in the next release.
