### ISSUE TITLE
[BUG]: Typo in Error Message

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#153]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

Request is spelled wrong in this error 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/3d06895d-18cd-4ec9-809a-8c98b7aa0a58)

**Comment by TorreyBetts** [comment]
Internally tracked as AB#29590
