### ISSUE TITLE
[BUG]: Stored Procedures should not be shown in the data blending UI

### ISSUE THREAD

**Issue by cleverdog** [RevealBi/Reveal.Sdk#154]
### SDK Version

1.6.3

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

At this time, from the UI perspective, we can select the additional data source as stored procedures in the data blending UI.
Thorugh the discussion in other place, I understand the function of joining stored procedures does not exsit. Please fix the UI to not show stored procs in the data blending UI.

![8dc803cbcf9b6e10e70f6f838a1a3965](https://github.com/RevealBi/Reveal.Sdk/assets/5829221/5dedf05a-3252-4808-8220-41b3b39a0d11)

**Comment by srodriguezinfragistics** [comment]
Hi! This issue is internally tracked as [AB#29632](https://infragistics.visualstudio.com/BusinessTools/_workitems/edit/29632)
