### ISSUE TITLE
[BUG]: The reaction range of the tooltip is shifted with Scatter Map

### ISSUE THREAD

**Issue by cleverdog** [RevealBi/Reveal.Sdk#156]
### SDK Version

1.6.3

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

While manipulating Scatter Map, sometimes the reaction range of the tooltip will be shifted.
The conditions I aware of that the problem is happened is following:
- This occurs when using OSM, not occur not using image tiles.
- This occurs after the map is zoomed in or out.
- It does not occur when zooming in and out by scrolling the mouse, but it seems to occur when zooming in and out using the controller at the bottom right.

Please refrer the attached video.

https://github.com/RevealBi/Reveal.Sdk/assets/5829221/3b8d4968-7413-4d2f-a3db-554223664520

**Comment by srodriguezinfragistics** [comment]
Hi! This issue is internally tracked as [AB#29664](https://infragistics.visualstudio.com/BusinessTools/_workitems/edit/29664)
