### ISSUE TITLE
Sort dataSourceItems coming from dataSource connection

### ISSUE THREAD

**Issue by tinoptilogic** [RevealBi/Reveal.Sdk#158]
Currently if you do not define dataSourceItems just the dataSource the tables and views which are pulled out from the dataSource get returned in the default order DB has returned. Would love the capability to order then in the Reveal.

**Comment by brianlagunas** [comment]
Is your desired order of tables alphabetical? If we changed the default ordering of the table to alphabetical, would that solve your primary issue?

**Comment by tinoptilogic** [comment]
Yes, any ordering type other that default from the DB would solve our issue.

**Comment by brianlagunas** [comment]
The request for tables to be sorted alphabetically by default has been implemented and will be available in our next release.

**Comment by dpazos-infragistics** [comment]
AB#30626

**Comment by tinoptilogic** [comment]
Can we please reopen this one per discussion on discord.

**Comment by brianlagunas** [comment]
@tinoptilogic If you have found an issue with the feature, please submit a bug with as much information as possible and preferably with a way to replicate it. As of today, we have not been able to replicate the ordering of the tables.
