### ISSUE TITLE
[BUG]: wrong type for RVDashboard.visualizations in d.ts?

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#16]
### Company

Private Info

### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

In `infragistics.reveal.d.ts` the `visualizations` field is declared like this (and in the [docs](https://help.revealbi.io/api/javascript/latest/classes/rvdashboard.html#visualizations) too):

    get visualizations(): readonly RVVisualization[];

Nonetheless, when I inspect it in DevTools I see it's of type `VisualizationsArray`, which allows us to use methods like `getById`.

Currently I'm casting the value myself to be able to use `getById`, but is this a bug in the declared type?

**Comment by luispandolfi** [comment]
Created an internal work item: AB#23334

**Comment by brianlagunas** [comment]
This has been fixed and will be available in the 1.5 release next week.
