### ISSUE TITLE
[BUG]: Filter value above 3000+ is not preserved

### ISSUE THREAD

**Issue by isabellacarroll** [RevealBi/Reveal.Sdk#163]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Mac

### Description

We noticed that when you apply a filter to the dashboard, it filters correctly, but the selected value over 3000 is not saved in the filter, even though its applied to the dashboard. If I apply the filter again after opening it, the 3000+ value is not preserved.
[reveal.filter.mov.zip](https://github.com/RevealBi/Reveal.Sdk/files/14439188/reveal.filter.mov.zip)

**Comment by isabellacarroll** [comment]
Will this be released in an update or should we be able to see this change immediately?

**Comment by brianlagunas** [comment]
This will be in our 1.6.5 release which we are targeting for tomorrow.
