### ISSUE TITLE
[BUG]: Skia sharp 2.88.3 and node 16.17.1 Gives Vulnerabilities when deploy on server

### ISSUE THREAD

**Issue by chiraggurjar2023** [RevealBi/Reveal.Sdk#164]
### SDK Version

Reveal.SDk.AspNetCore

### Client Framework

Angular

### Server Platform

Java

### Operating System

Linux

### Description

Skia sharp 2.88.3 and node 16.17.1 Gives Vulnerabilities when deploy on server
![image](https://github.com/RevealBi/Reveal.Sdk/assets/148424274/c3d5626f-aac9-4b63-a4f4-cdbb67a7ace2)

**Comment by gkaveckis** [comment]
Hi, thanks for reporting this.

Regarding node, you can install a higher version. Our requirements are 16.3 & higher 

Now moving to SkiaSharp we created an internal issue to track it AB#27480

Any update will be registered here.

Regards.

**Comment by brianlagunas** [comment]
This has been fixed and will be available in our April release.
