### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by fahadfastion** [RevealBi/Reveal.Sdk#166]
### SDK Version

6.0

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

In the Map we are unable to fraction it us to 3 digit below is the thread 

https://discord.com/channels/1050800659911430254/1050807777104252928/threads/1214574769748312196

**Comment by gkaveckis** [comment]
Hi
We could reproduce the missing decimal digits configuration while displaying the value in the map.
Internally tracked as AB#30086
Regards.

**Comment by brianlagunas** [comment]
Is this the same issue as #141

Also, please add titles to the bugs you submit.

**Comment by gkaveckis** [comment]
Hi

Closing it as it is duplicated with #141 

Thanks
