### ISSUE TITLE
[BUG]: Reveal/Redshit Issues

### ISSUE THREAD

**Issue by isabellacarroll** [RevealBi/Reveal.Sdk#167]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Mac

### Description

We use Reveal BI with an Amazon Redshift data source, and the Reveal Java SDK's  /dashboard/editor/datasource/getchildren endpoint attempts to list datasource metadata using the following SQL query:

SELECT schemaname, tablename FROM pg_tables WHERE encode(schemaname::bytea,'hex') = '74656e616e742d33396162323731652d303735662d343737612d613764342d343138393139656565313761'

However, bytea is not a supported datatype in Redshift (https://docs.aws.amazon.com/redshift/latest/dg/c_unsupported-postgresql-datatypes.html) and this query fails with:

ERROR: cannot cast type name to bytea

This causes the datasource picker to show up blank and unusable, see screenshot.
We have been able to use this in the past, but it's unclear when this stopped working, as we've been using a custom datasource picker.
![image (7)](https://github.com/RevealBi/Reveal.Sdk/assets/102161048/887c4ec9-a61f-4234-9ae4-759cef5c6b0e)

**Comment by luispandolfi** [comment]
Hi @isabellacarroll, this issue is fixed and will be available in the upcoming release (v1.6.5).
