### ISSUE TITLE
[BUG]: Chrome reports Violations in the browser debug tools

### ISSUE THREAD

**Issue by StevybSC** [RevealBi/Reveal.Sdk#169]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Node.js

### Operating System

Linux

### Description

When rendering a dashboard, multiple "Violations" can be seen in the browser dev tools console.

Messages regarding:
[Violation] 'setTimeout' handler took <N>ms (related to infrajistics.reveal.js:168)
![image](https://github.com/RevealBi/Reveal.Sdk/assets/39970719/32c3ec66-b31f-409c-81d5-7d8dcb1250d6)
and
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

frames:
<html>
<body>

add | @ | jquery.min.js:2
-- | -- | --
  | (anonymous) | @ | jquery.min.js:2
  | each | @ | jquery.min.js:2
  | each | @ | jquery.min.js:2
  | Ee | @ | jquery.min.js:2
  | on | @ | jquery.min.js:2
  | bind | @ | jquery.min.js:2
  | attachEvents | @ | infragistics.reveal.js:84
  | onAdded | @ | infragistics.reveal.js:84
  | addSubview | @ | infragistics.reveal.js:84
  | addSubview | @ | infragistics.reveal.js:84
  | addSubview | @ | infragistics.reveal.js:84
  | init | @ | infragistics.reveal.js:154
  | c | @ | infragistics.reveal.js:56
  | init | @ | infragistics.reveal.js:154
  | c | @ | infragistics.reveal.js:56
  | getCell | @ | infragistics.reveal.js:154
  | arrangeItems | @ | infragistics.reveal.js:84
  | refresh | @ | infragistics.reveal.js:84
  | sizeChanged | @ | infragistics.reveal.js:84
  | measureChildren | @ | infragistics.reveal.js:84
  | setFrameAsDouble | @ | infragistics.reveal.js:84
  | setFrame | @ | infragistics.reveal.js:84
  | layoutChild | @ | infragistics.reveal.js:84
  | measureView1 | @ | infragistics.reveal.js:84
  | sizeChanged | @ | infragistics.reveal.js:154
  | measureChildren | @ | infragistics.reveal.js:84
  | setFrameAsDouble | @ | infragistics.reveal.js:84
  | setFrame | @ | infragistics.reveal.js:84
  | updateSize | @ | infragistics.reveal.js:168
  | _presentRevealView | @ | infragistics.reveal.js:168
  | (anonymous) | @ | infragistics.reveal.js:168

</body>
</html>

![image](https://github.com/RevealBi/Reveal.Sdk/assets/39970719/711c2dc5-bef5-40bc-bf4a-940e78558efa)

**Comment by luispandolfi** [comment]
Hi @StevybSC, this [Violation] are warnings, doesn't mean the app is not working.
Are you experiencing any issue related to this warnings?

**Comment by brianlagunas** [comment]
Closing as there has been no response.
