### ISSUE TITLE
[BUG]: The added or subtracted value results in an un-representable DateTime. (Parameter 'value')

### ISSUE THREAD

**Issue by StevybSC** [RevealBi/Reveal.Sdk#170]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Node.js

### Operating System

Linux

### Description

When datetime2 fields in SQL have the max value: 9999-12-31 23:59:59.9999999 an error is thrown when trying to use or preview the table in the dashboard creator.

It does not happen with this value: 9999-12-31 23:59:59.9999000

My dataset also has dates with the format: 0001-01-01 00:00:00.0000000 which may also need accounting for.

**Comment by brianlagunas** [comment]
This is being tracked internally with AB#30452
