### ISSUE TITLE
Quick Filter selected value

### ISSUE THREAD

**Issue by NitinPandit** [RevealBi/Reveal.Sdk#171]
**Is your feature request related to a problem? Please describe.**
We can read the selected values from global filters on any dashboard events like "onUrlLinkRequested" or any other event but if we need to get the quick filter's values, we don't have any option for that in Reveal SDK.

**Describe the solution you'd like**
it'll be great if we have a Filters[] array in the RVVisualization Class that returns all the Quick Filters for that specific visualization or a function like "getQuickFilter("Filter Name")" from where we can read the selected values of that filter.

**Describe alternatives you've considered**
Yes, If we can have all the dashboard and quick filters on Server Export so that we can get all the custom or raw data based on filters and then export.

**Additional context**
NA

**Comment by brianlagunas** [comment]
This has been implemented with a new visualization filter API. It is available in the 1.6.7 release.
