### ISSUE TITLE
[BUG]: Export to Excel crashes 

### ISSUE THREAD

**Issue by isabellacarroll** [RevealBi/Reveal.Sdk#172]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Linux

### Description

Export to Excel crashes when the worksheet name is greater than 31 characters and encounters the following characters `: \ / ? * [ ]`. A fix would be to filter out any prohibited characters and truncate report names that are too long.

**Comment by srodriguezinfragistics** [comment]
Hi! This is being tracked internally with [AB#30550](https://infragistics.visualstudio.com/14a7928c-44bc-4aed-b2ca-9a0ffbb14d7a/_workitems/edit/30550)
