### ISSUE TITLE
[BUG]: Date format is not being applied to Excel exports

### ISSUE THREAD

**Issue by isabellacarroll** [RevealBi/Reveal.Sdk#173]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Mac

### Description

Date format is not being applied to Excel exports

**Comment by srodriguezinfragistics** [comment]
Hi! This is being tracked internally with [AB#30551](https://infragistics.visualstudio.com/14a7928c-44bc-4aed-b2ca-9a0ffbb14d7a/_workitems/edit/30551)

**Comment by brianlagunas** [comment]
This has been fixed and is available in our latest 1.6.7 release.
