### ISSUE TITLE
[BUG]: Edit option is missing in new SDK 

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#174]
### SDK Version

1.6.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We were not able to edit the dashboard datasource . Only "refresh" option is visible . In previous versions , we were having 2 options here Edit and Refresh. Is this change intentional or something is wrong ?

<img width="584" alt="Screenshot 2024-04-01 at 7 28 13 PM" src="https://github.com/RevealBi/Reveal.Sdk/assets/89643622/75aa80cd-2d35-4838-936c-bd1b032c65f3">

**Comment by brianlagunas** [comment]
The first thing you should check is if the `showEditDataSource` property of the RevealView is set. Make sure you are not changing the value, and also you can try setting it to `true`.

**Comment by brianlagunas** [comment]
I'm closing this as there has been no response. I am going to assume you set the property and it worked. If not, just comment and I can reopen.
