### ISSUE TITLE
Add the ability to reference columns in links without that column appearing in the visible dataset.

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [RevealBi/Reveal.Sdk#177]
**Is your feature request related to a problem? Please describe.**
No, this isn't a problem per-se.  However, I'm working with links, and specifically links in grids.  When considering a list of "Things" that might be past due, I'd like to add a link to the URL that the "Thing" is stored behind.  This page accepts the Id of the "Thing", but I can't reference the [ThingId] from the link because I don't have the "ThingId" in the grid.  We can certainly add the "ThingId" to the end of the grid, but users aren't really going to want to see it.

**Describe the solution you'd like**
I'd like to add columns as additional metadata items to visualizations.  These items would not be visible but will be referenceable in links.

**Describe alternatives you've considered**
The only viable alternative is adding the column to the visualization and showing it to the user.  For columns that contain identifiers, this isn't ideal.

**Comment by brianlagunas** [comment]
Have you tried adding the column to the grid and then hiding it by changing the "Is Visible" property on the field settings?

![image](https://github.com/RevealBi/Reveal.Sdk/assets/835562/73054988-9653-4272-a7fc-4ad56eab3cb5)

**Comment by ItWorksOnMyMachine** [comment]
The only options I'm seeing are Sorting and Formatting.  I'm using 1.6.4-rc11.

**Comment by brianlagunas** [comment]
Are you using a Grid or PivotGrid?

**Comment by ItWorksOnMyMachine** [comment]
> Are you using a Grid or PivotGrid?  

Just Grid

**Comment by ItWorksOnMyMachine** [comment]
@brianlagunas, just returning to this quickly.  How do I enable that IsVisible column you showed in the screenshot above?

**Comment by brianlagunas** [comment]
That was in the PivotGrid. I was unaware that this was not available for the normal grid. We have logged this request for future implementation.

**Comment by brianlagunas** [comment]
This has been implemented and will be available in our Sept release
