### ISSUE TITLE
[BUG]: The first selected DataSource is always used on DataSourceItems, regardless of subsequent DataSource selections.

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [RevealBi/Reveal.Sdk#178]
### SDK Version

1.6.4

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We demoed this on Friday, 3/29/2024, with Jason Beres.  I have two data sources specified client side.  Each are postgresql sources.  When you select the first data source, you are properly presented with a list of data source items.  When selecting a data source item, the call to the server is made and the item and its DataSource.Id are correct.  However, if you subsequently select the other Data source, you are then presented, correclty, with a list of items for that Data Source.  When selecting an item from this list, the DataSource.Id set on the DataSourceItem on the server is still referencing the data source selected the first time.  It appears there is a caching issue in the asp.net server side code.

**Comment by brianlagunas** [comment]
Thanks for reporting this issue. It is being tracked internally with AB#30578

**Comment by brianlagunas** [comment]
Turns out this is a much more complex bug to fix than it appears on the surface. So much so, we have decided to not fix it due to the risk.

The work-around is to set other properties on the client data source object, such as host, to some fake value.

We have a large effort internally on rearchitecting how the data sources work in general, and the new approach will not have this problem as the entire concept of client-side data source declarations will go away. We are a long way away from having this new architecture, but it is a path forward for us.

Given the risk and complexity, I'm closing this as "not to fix". Let me know if you have any questions.

**Comment by ItWorksOnMyMachine** [comment]
Considering the fact that multiple data sources is a supported feature that was touted during sales calls, this is a surprising decision because it eliminates this as a feature.  I understand you feel there is a workaround, but it's not really clear what this workaround is.  @brianlagunas would it be possible to get examples of how to work around this bug?

**Comment by ItWorksOnMyMachine** [comment]
> Believe me, it wasn't an easy decision. Also, the feature is still supported. The only requirement is that you need to provide an additional property on the client-side data source object.
> 
> Something like this:
> 
> ```
> const postgresDataSource = new $.ig.RVPostgresDataSource();
> postgresDataSource.id= "MyCustomId";
> postgresDataSource.title = "My PostgreSQL Title";
> postgresDataSource.subtitle = "My PostgreSQL Subtitle";
> postgresDataSource.host = "a-fake-value";
> 
> const postgresDataSource2 = new $.ig.RVPostgresDataSource();
> postgresDataSource2.id= "MyOtherCustomId";
> postgresDataSource2.title = "My Other PostgreSQL Title";
> postgresDataSource2.subtitle = "My Other PostgreSQL Subtitle";
> postgresDataSource2.host = "a-different-fake-value";
> ```
> 
> The history behind this is that in the early stages of the product, the approach to data sources was to set all the connection info client side. Since then, we have learned that this is not what customers should be doing and have shifted to recommend that customers only set connection info on the sever. If you look at our docs, we even show setting up data sources on the client (we'll be removing this from the docs soon).
> 
> However, the product is still written to support the client-side data source declaration. Which is the source of this bug. So as of today, we are in this weird transition period of moving all the data source info to the server and off the client.
> 
> I know it's annoying, but this small work-around does solve the problem and doesn't prevent you from using multiple data sources of the same type.

Thanks for the history on this, I was actually a bit curious.  In the example above, what's the additional property?  We are already setting the Id, etc.  Whichever is the first selected data source is the data source that's always returned after selecting a data source item, and that includes all properties of the first selected data source.

**Comment by brianlagunas** [comment]
Are you saying you are setting properties other than id, title, and subtitle, and it's still not working? What other client-side properties are you setting?

**Comment by ItWorksOnMyMachine** [comment]
> Are you saying you are setting properties other than id, title, and subtitle, and it's still not working? What other client-side properties are you setting? Can you provide code snippets to demonstrate which properties you are setting?

Thats what I'm asking for examples of. Id, title, subtitle, and host are what's made available. At least that's what I see in the ts definitions and documentation. If there is something else to set, I would appreciate an example. Your example above shows inly those properties also.

**Comment by brianlagunas** [comment]
If you want a list of all the possible properties that are exposed on the client you can look at the API docs.  For example, here's the RVPostgresDataSource

https://help.revealbi.io/api/javascript/latest/classes/rvpostgresdatasource.html

To clarify, it's not necessary to configure all the properties or use authentic values. The essential step is to assign one extra property with a dummy value that's never utilized to ensure each data source is correctly employed. Subsequently, you can proceed to update everything on the server as currently done.

**Comment by brianlagunas** [comment]
Just to follow-up on this issue. We have found a proper fix and it will be available in our next release scheduled for the first week of March,
