### ISSUE TITLE
Image Export should export scrollable dashboards

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#181]
### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Java

### Operating System

Windows

### Description

I created a batch of data that occupied the entire screen, which I viewed by scrolling. However, when I chose to export, it only exported the screenshot of what was visible on the screen, and the remaining part of the image information could not be fully exported

![revealbiissue](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/3251884b-b560-4779-90fd-01478b3f3e38)

**Comment by TorreyBetts** [comment]
The image export when used from the dashboard menu only creates an image of the view itself. When exported with the visualization maximized will only export an image of that visualization. To export the entire dashboard, you'd need to export PDF or PowerPoint.

This post can be seen as a bug or a potential feature request, so I'll leave it to @brianlagunas to decide on how he'd like to proceed.

**Comment by brianlagunas** [comment]
We have decided not to implement this request at this time.
