### ISSUE TITLE
Add an event when the Back button is clicked from a linked dashboard.

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [RevealBi/Reveal.Sdk#183]
**Is your feature request related to a problem? Please describe.**
We are implementing permissioning and sharing in dashboards. When a user is viweing their own dashboard they can edit it, and add a link to a dashboard that has been shared with them.  When they follow a link to that shared dashboard they should have their ability to edit the dashboard disabled.  This can be done using the onLinkedDashboardProviderAsync.  There is no easy way of determining when the user navigates back to their own dashboard with the back button in the dashboard header.  I'd like to have an event added that notifies us of when a user navigates back from a linked dashboard to the linking dashboard.

**Describe the solution you'd like**
 I'd like to have an event added that notifies us of when a user navigates back from a linked dashboard to the linking dashboard.

**Describe alternatives you've considered**
It might be possible to use onVisualizationDataLoading, however I haven't explored that option yet.  

**Additional context**

**Comment by brianlagunas** [comment]
Do you think a general dashboard loaded event would work, or do you think you need to know specifically on a button click?

**Comment by ItWorksOnMyMachine** [comment]
> Do you think a general dashboard loaded event would work, or do you think you need to know specifically on a button click?
> 
> Have you thought about what event args you would need to have in the event?

I think a general event is fine, and maybe more useful in the long-run since there could be other things that trigger this even besides the back button.  I think a parameter with the Id of the dashboard would be useful, and perhaps an arg that says something about what caused the dashboard to be loaded (e.g. "Back Button", "Load Method", etc.).  Although, that's maybe not terribly useful.

**Comment by brianlagunas** [comment]
We have added a new `dashboardChanged` event with event args that will give you the new dashboard and the old dashboard. This event fires anytime the dashboard property changes. This includes during dashboard linking and going back to the original dashboard from a linked dashboard.

Example usage:
```typescript
revealView.onDashboardChanged = function (args: DashboardChangedEventArgs) {
   console.log('Dashboard has changed.');
   console.log('Old Dashboard:', args.oldValue);
   console.log('New Dashboard:', args.newValue);
};
```

This will be available in our next release.
