### ISSUE TITLE
[BUG]: Empty title will result in a failure to export

### ISSUE THREAD

**Issue by narimanshariat** [RevealBi/Reveal.Sdk#187]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Linux

### Description

If a users sets the name of a visualization to blank (no characters) and saves the visualization. When they go to export the visualization it doesn't export. The error message in the exportData endpoint simply says "Something went wrong"

My assumption would be that the user should not be able to save the visual without a title.

Steps to Recreate:
1. Create a visualization
2. Edit the title and clear all characters
3. Save visualization
4. Click to export specific visualization

**Comment by brianlagunas** [comment]
I just wanted to mention, if your goal is to not show a title for the visualization, there is a property in the settings that allows you to hide it.

![image](https://github.com/RevealBi/Reveal.Sdk/assets/835562/6633fee0-2a27-4e80-9578-45c43040b57b)
