### ISSUE TITLE
[BUG]: Field filters are applying to the calculated modal as well

### ISSUE THREAD

**Issue by narimanshariat** [RevealBi/Reveal.Sdk#188]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Linux

### Description

Use case:
A user wants to edit (or create) a calculated field. In the case of editing they might use the quick filter field to find their calculated field.
![Screenshot 2024-04-26 at 11 02 33 AM](https://github.com/RevealBi/Reveal.Sdk/assets/8258821/716edcbc-f65a-4c5b-8687-bf7a2572c710)
When they go to edit the calculated field, the filter is still applied which means they can't see any available fields:
![Screenshot 2024-04-26 at 11 03 26 AM](https://github.com/RevealBi/Reveal.Sdk/assets/8258821/c170af8c-40d2-44f4-a0c6-d1731cf61ea7)

Expected behavior:
The applied filters shouldn't be combined but should instead be independent.

**Comment by gkaveckis** [comment]
Hi thanks for letting us know about this issue

We are internally tracking it by AB#25691

Regards.
