### ISSUE TITLE
[BUG]: trunc() doesn't work within concatenate()

### ISSUE THREAD

**Issue by narimanshariat** [RevealBi/Reveal.Sdk#189]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Linux

### Description

When using trunc() inside of concatenate() we do not get the desired results of the integer portion of a number.

**Formulas:**
![Screenshot 2024-04-26 at 11 26 36 AM](https://github.com/RevealBi/Reveal.Sdk/assets/8258821/04dd6f7a-d938-4a9b-aea9-0fc57c5e453d)
![Screenshot 2024-04-26 at 11 26 22 AM](https://github.com/RevealBi/Reveal.Sdk/assets/8258821/930b4ab1-0f66-44b9-b998-869142ecfa9e)

**Result:**
![Screenshot 2024-04-26 at 11 25 57 AM](https://github.com/RevealBi/Reveal.Sdk/assets/8258821/cf10109e-6115-41a9-8cb3-a4a75ebffabf)

Please note the decimal point inside the concatenated string. The expectation would to not have that.

**Comment by brianlagunas** [comment]
I'm not sure the correct bug is being reported here. 

Is the main issue that your integer number is being treated as a decimal?

Can you provide a screenshot of your fields that include the "location_id" and the "location_id" fields settings?

**Comment by narimanshariat** [comment]
![Screenshot 2024-04-26 at 5 57 02 PM](https://github.com/RevealBi/Reveal.Sdk/assets/8258821/528deae9-dfe6-4277-aa4c-a97c4708df61)

The field data type in postgres is an INT8. All our ID fields are INT8 so this is happening to us for any ID we want to display.
<img width="309" alt="Screenshot 2024-04-26 at 5 59 27 PM" src="https://github.com/RevealBi/Reveal.Sdk/assets/8258821/edde7e0b-44fa-4129-9459-267a63a15685">

**Comment by gkaveckis** [comment]
Hi, 

We already created an internal issue to track it AB#31166
We'll keep you updated here.
Thanks!

**Comment by gkaveckis** [comment]
Hi @narimanshariat 

While we are fixing this issue, as an alternative you can use & instead of concatenate
For example you can do something like:
"some string" & trunc([Forecasted]) 
Hope this helps.

**Comment by brianlagunas** [comment]
This has been fixed and will be available in our 1.7.0 release.

**Comment by brianlagunas** [comment]
Sorry, got ahead of myself. Seems we aren't done with this issue after all.
