### ISSUE TITLE
[BUG]: Add Field from Data Source don't work when text

### ISSUE THREAD

**Issue by narimanshariat** [RevealBi/Reveal.Sdk#191]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Linux

### Description

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'dataSourceId')
    at Class.createDataSourcesWithDatabase (infragistics.reveal.js:154:1371040)
    at Class.getExistingDatasources (infragistics.reveal.js:154:1374345)
    at c.init (infragistics.reveal.js:154:1219048)
    at c.init (infragistics.reveal.js:168:112374)
    at new c (infragistics.reveal.js:56:695)
    at c (infragistics.reveal.js:168:286774)
    at infragistics.reveal.js:168:287377
    at o.current.onDataSourcesRequested (RevealContainer.tsx:48:17)
    at SdkApp.showSelectDatasourcesScreen (infragistics.reveal.js:168:287319)
    at c.showBlendEditor (infragistics.reveal.js:154:1653585)`

This error occurs in the following condition.
1. Create a visual with a data source
2.  Add a text box
3. Edit the existing visual.
4. Add a field from a data source to the visual
5. Error occurs
6. Exit the edit mode for the visual
7. Delete the text box
8. Repeat steps 3 & 4 and no error occurs

**Comment by gkaveckis** [comment]
Hi 
Could you send us some quick video about how to reproduce it?
Because we are trying here without success,

Thanks!

**Comment by narimanshariat** [comment]
Here you go: https://www.loom.com/share/bc71c6f9f5f846d8a3e761b1dafc6dc9

**Comment by dpazos-infragistics** [comment]
We tried to reproduce the error but have been unable to do so.
Can you provide more details?
The video doesn't show the error that you're getting, if any. Only that the dialog to set up the datasource doesn't show.
Do you get any actual error? If so, can you provide us with that info?

**Comment by dpazos-infragistics** [comment]
Hi. We tried to reproduce the error but have been unable to do so.
Can you reproduce it in a simpler scenario that might help us reproduce it locally?

**Comment by narimanshariat** [comment]
Now with the console panel in view. https://www.loom.com/share/ba501bf9fdc442fb8f74fface3b62b77

**Comment by dpazos-infragistics** [comment]
I tried to reproduce the issue with SDK 1.6.4 but couldn't.
Let's try to simplify the scenario.
Try deleting all of the visualizations except the one from which you're accessing the calculated field UI.
Does the problem still happen?
If not, try going back from there and see which visualization is the one causing the issue.

**Comment by narimanshariat** [comment]
I started with a completely blank dashboard and created a visual from scratch. Same issue.

https://www.loom.com/share/318a4d25e2ca45c287c34debdcc4205e

**Comment by dpazos-infragistics** [comment]
I followed your video as closely and still couldn't reproduce it.
Here's what I tried:
- Using SDK 1.6.4, create a new dashboard
- Add a visualization based on a view on a Postgres DS. Keep the default of a Columns visualization
- Add a text field to the Label section and another text field to the Values section
- Add a field from another data source. Make it linked to a different view in the same DS, linked by a matched numeric field.
- Save the visualization.
- Add a textbox to the dashboard and set a text for it, leaving title empty.
- Save the dashboard.
- Edit the dashboard again
- Edit the visualization
- Select the option to add a field from another data source.
No error was encountered.

**Comment by narimanshariat** [comment]
If I start a blank dashboard and add a text box. Then try to add a visualization I get the same error.

To me it seems that it is trying to fetch the datasource but it is hitting an error.
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'dataSourceId')`

Is it possible that we don't have something configured correctly for textboxes to work? There is something unique about the textbox that is interrupting the normal flow.

**Comment by brianlagunas** [comment]
Can you try to create a small stand-alone application that reproduces the issue?  You can start by modifying an existing sample to save you some time. Maybe start with one of the data source samples:

https://github.com/RevealBi/sdk-samples-javascript/tree/main/DataSources

You can also try sharing the dashboard RDASH file with us via a DM on Discord.

**Comment by brianlagunas** [comment]
There hasn't been a reply to this issue in a month. I am closing this issue since we have been unable to reproduce it. If you can provide a sample, or more information, that can help us reproduce this I can reopen it.

**Comment by narimanshariat** [comment]
I think this was resolved in this issue: https://github.com/RevealBi/Reveal.Sdk/issues/211
