### ISSUE TITLE
Hide new filter summary page in PDFs

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#195]
**Is your feature request related to a problem? Please describe.**

A recent version of Reveal (between 1.6.2 and 1.6.6) added a new page to our server-side exported PDFs:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/7802015e-0dca-4d3d-b329-21c22454670b)

We would like a way to hide this page, it's of no use for our customers.

**Describe the solution you'd like**
In the `PdfExportOptions`, this would do it: `setShowFilterSummaryPage(false)`.

**Describe alternatives you've considered**
Keep using Reveal 1.6.1 for the foreseeable future.

**Additional context**
None

**Comment by brianlagunas** [comment]
We have created an internal work item for this request and have scheduled it for implementation in our next sprint AB#31881

**Comment by brianlagunas** [comment]
This has be implemented with a new property on the `ExportOptions` class called `IncludeFiltersSummaryPage`.

This feature will be available in our Aug release.
