### ISSUE TITLE
[BUG]: Error Exporting to Excel

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#198]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

https://infragisticsinc297-my.sharepoint.com/personal/aatanasov_infragistics_com/_layouts/15/stream.aspx?id=%2Fpersonal%2Faatanasov%5Finfragistics%5Fcom%2FDocuments%2FSlingshot%20Uploads%2FDownload%20to%20excel%2Ewebm&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E34860f97%2Dca1f%2D47dc%2Dbbcb%2Df0948e9a081b

**Comment by luispandolfi** [comment]
Hi @CMcGuigan10, I do not have access to that link content. Could you expand the issue information here?

**Comment by CMcGuigan10** [comment]
@luispandolfi it is the Error that pops up on the bottom left for export to excel that says export failed.

**Comment by brianlagunas** [comment]
@CMcGuigan10 can you provide more detailed information that can help us reproduce the issue? Maybe the steps to take, the dashboard being used, the data source, etc?

There is not enough information here to investigate.

**Comment by CMcGuigan10** [comment]
You can try this dashboard that doesnt work:  

https://my.slingshotapp.io/openDashboard/e97e10ef_daa34bb9-7a0b-446f-aae5-20c4337c9fda

I tried to narrow down to certain data sources and platforms, but there is no common issue between them. This is all I have unfortunately. I tested the same data source on different dashboards, it works on some but not all. I tested web vs mac etc.

**Comment by brianlagunas** [comment]
It worked for me. Are you on Slingshot dev or prod?

**Comment by CMcGuigan10** [comment]
production

**Comment by CMcGuigan10** [comment]
failing on slingshot production for dashboards tied to analysis services - MacOS and Web both tried

**Comment by luispandolfi** [comment]
> failing on slingshot production for dashboards tied to analysis services - MacOS and Web both tried

I want to try it. Could you share that dashboard with me?

**Comment by luispandolfi** [comment]
Please check that your widgets title do not contain any Excel forbidden characters, the widget title is used for the sheet name.

Worksheet names cannot:
- Be blank .
- Contain more than 31 characters.
- Contain any of the following characters: / \ ? * : [ ]
- For example, 02/17/2016 would not be a valid worksheet name, but 02-17-2016 would work fine.
- Begin or end with an apostrophe ('), but they can be used in between text or numbers in a name.
- Be named "History". This is a reserved word Excel uses internally.

**Comment by luispandolfi** [comment]
This issue was already fixed. Internal issue #AB30550

**Comment by CMcGuigan10** [comment]
@luispandolfi this is still a bug that needs to be resolved. 

We need to export when characters in the title of more than 30 characters. The sheet should just take the first 30 characters.

**Comment by TorreyBetts** [comment]
> @luispandolfi this is still a bug that needs to be resolved.
> 
> We need to export when characters in the title of more than 30 characters. The sheet should just take the first 30 characters.

The limit that Luis mentioned is a [Microsoft limit](https://answers.microsoft.com/en-us/msoffice/forum/all/what-is-the-maximum-characters-allowed-in-a-sheet/b77fc2e5-0e1e-4d4d-b30e-4b273395a61f#:~:text=31%20is%20the%20maximum.), which is out of our hands.
