### ISSUE TITLE
[BUG]: Misaligned placeholder on textarea fields

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#199]
### SDK Version

1.6.6

### Client Framework

Angular

### Server Platform

Java

### Operating System

Linux

### Description

The placeholder on text areas like this one:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/f4f6b1d2-09e9-44e6-a02a-25d2031a5dbe)

and this one:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/66871b51-74b9-4250-bdad-e999937e7d7c)

is overflowing outside of the textarea.

Once we start writing text, the content is properly inside the textarea, it's just the placeholder where the issue happens:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/37991297-81e2-4977-a918-47f99310e63b)

**Comment by luispandolfi** [comment]
Hi @dwilches, I do not get that behaviour. Are you overriding some of the styles? Could you share a simple app that replicates the issue?

**Comment by dwilches** [comment]
Hi @luispandolfi 

We do have custom CSS styles. I just tried turning off several of them that I saw applied to the `pre` and `code` elements, and they didn't fix it.

Nonetheless, I notied ther is an override for the font in the Reveal element (not our custom styles) like this:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/dd15d7d2-7e3f-4241-981d-e54210b71c57)

If I turn it off, then the alignment is correct:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/2d191a7a-7b9b-47a1-840f-368c70b697ac)

So it seems to be some issue with the line height or some calculation around font size (maybe releated: https://github.com/RevealBi/Reveal.Sdk/issues/206).

For now, I'll remove the background override so the issue is not that salient.

Thanks.

**Comment by brianlagunas** [comment]
There is some custom CSS somewhere causing these problems. Those gray bars appearing in the text boxes are not part of the RevealView styling. That is coming from somewhere else. Possibly another dependency stylesheet in your app? Try to see if you can find the source stylesheet of those gray bar styles.

**Comment by dwilches** [comment]
@brianlagunas Yes, the grey comes from my CSS. The issue I reported was not about the colour but the misalignment. The colour is just to make the misalignment more salient in these images.

**Comment by brianlagunas** [comment]
I made a comment on #206 regarding fonts in Reveal. Try verifying that the correct font name is being used and validate if it solves this issue. This alignment issue does not present itself in our SDK as-is, so it's difficult for us to investigate. If possible, could you try to reproduce the issue in a single HTML sample like this one:

https://github.com/RevealBi/sdk-samples-javascript/blob/main/ThemingDashboards/index.html

**Comment by dwilches** [comment]
@brianlagunas  I'm attaching the reproduction here. All I did was to change the font-size in the body, then the misalignment happens (because the `code` is overriding the font-size but not the `pre`). This was the piece of code I added:
```
    <style>
        body { font-size: 18px; }
        code { background-color: #7D7D7D; }
    </style>
```

That second line, overriding the colour on the `code` is just to visually emphasise the misalignment:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/dbb24f8b-5338-487b-8a6c-8d5c09f57198)

but you can remove it and, even though the issue is harder to notice, you'll see the cursor doesn't line up:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/7f0b915a-96f9-4703-a315-fd63031e26e1)

Source code:
[sample.zip](https://github.com/RevealBi/Reveal.Sdk/files/15277275/sample.zip)

**Comment by brianlagunas** [comment]
This is great! Thank you so much. @luispandolfi you have what you need to validate the bug.

**Comment by luispandolfi** [comment]
This is the perfect sample of how issues should be reported :)
We already created an internal issue to track it AB#31320
We'll keep you updated here.

**Comment by brianlagunas** [comment]
This has been fixed and will be available in our Aug release.
