### ISSUE TITLE
[BUG]: Pivot Visualization Excel export missing data/formatting

### ISSUE THREAD

**Issue by sleinenger** [RevealBi/Reveal.Sdk#200]
### SDK Version

1.6.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Hello,
When exporting a pivot visualization to excel, if you do not expand the pivot row, the export to excel works correctly. If you expand a pivot row and export to excel, it seems the first data column is dropped from the export and the column headings are shifted to the right. 

Visualization not expanded
![image](https://github.com/RevealBi/Reveal.Sdk/assets/134005865/d686434c-ba01-45ac-939c-8a896bcd145e)

Visualization Export
![image](https://github.com/RevealBi/Reveal.Sdk/assets/134005865/d3be266e-7bc7-4c95-86d1-6d282b41af1a)

Visualization expanded
![image](https://github.com/RevealBi/Reveal.Sdk/assets/134005865/ab59294d-856e-466d-affa-c0f0d61f395c)

Visualization Export - Issue
![image](https://github.com/RevealBi/Reveal.Sdk/assets/134005865/8898da5b-7979-4654-8451-c48b6f4afd63)

**Comment by luispandolfi** [comment]
Thanks @sleinenger for the details.
We already created an internal issue to track it AB#31245
We'll keep you updated here.
Thanks!

**Comment by sleinenger** [comment]
Hello,
I also want to note we are running SDK 1.6.6 receiving this behavior.
Thanks

**Comment by sleinenger** [comment]
Hello,
Is the resolution in a new SDK release?
Thanks

**Comment by brianlagunas** [comment]
It will be available in our next 1.6.7 release next month.

**Comment by sleinenger** [comment]
Thank you Brian
