### ISSUE TITLE
[BUG]: When exporting a dashboard to PPT visualizations are cut off

### ISSUE THREAD

**Issue by isabellacarroll** [RevealBi/Reveal.Sdk#202]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Mac

### Description

When exporting a dashboard or visualization to powerpoint, the reports are cut off if the data extends beyond the page.
[Demo Day April '24.pptx](https://github.com/RevealBi/Reveal.Sdk/files/15251663/Demo.Day.April.24.pptx)

**Comment by brianlagunas** [comment]
Thank you for reporting this issue. However, this is not a bug. This is by design. Export to PowerPoint uses screenshots of the dashboard visualizations. The only export that will provide all the grid data would be either Excel or PDF.
