### ISSUE TITLE
[BUG]: In custom BI, calculated fields cannot be sorted

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#207]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Windows

### Description

1.Select a table data, create a new field and edit the Calculated field"if(or([value]>0 ,[price]>0), "Delayed", "OnTime")".
2.After completion, click on that field to sort it, choose SORT BY this newly created field, and then an error occurs.                                  
Details are shown in the following screen recording
![BUG1](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/1360c3ca-a5dc-46e4-9ade-49b08c21e06c)

**Comment by nerzhei** [comment]
An internal work item has been created AB#31342. Will keep you posted here.

**Comment by brianlagunas** [comment]
This issue actually turns out to be more of a UI bug than a functional bug. The fix is to remove the option to sort by the same field. Sorting by the same field is functionally just the same as leaving 'sort by' as 'None'. You should use the "None" option in your scenario.
