### ISSUE TITLE
[BUG]: GA Spend Data Showing Incorrect Numbers Between Charts

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#208]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

This chart: 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/582f3a32-215a-40aa-9fe8-2f2372bb9346)

Is showing a total send of $44,773 for Campaign Names that contain Reveal  

But when viewing the same data by device it shows $32,844 : 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/4da19baa-8d2c-49e8-974b-ce95d8a4d837)

**Comment by TorreyBetts** [comment]
@CMcGuigan10 Are those data sources the same? They have different titles (Campaign & Ad Group), and some dimensions look different too.

**Comment by CMcGuigan10** [comment]
Data source is the same the table being used is different – Google ads.

From: Torrey Betts ***@***.***>
Date: Tuesday, May 21, 2024 at 5:29 PM
To: RevealBi/Reveal.Sdk ***@***.***>
Cc: Casey Ciniello ***@***.***>, Mention ***@***.***>
Subject: Re: [RevealBi/Reveal.Sdk] [BUG]: GA Spend Data Showing Incorrect Numbers Between Charts (Issue #208)

@CMcGuigan10<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CMcGuigan10&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=3G-aGjxZDeuTcjb6O3sc_uRd88JsWnvXgKjRHuR1uEM&m=Qg4BfcxFsNP5-erqI6CqOhKCvutOt1OGT1e3-Y5A1pjyN8yRZ2rNbR_U0thqnPVy&s=tPT2GzwiCvyBUQtAyieX5PhBe0D29zisS8qR6S65Nz0&e=> Are those data sources the same? They have different titles (Campaign & Ad Group), and some dimensions look different too.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_RevealBi_Reveal.Sdk_issues_208-23issuecomment-2D2123472350&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=3G-aGjxZDeuTcjb6O3sc_uRd88JsWnvXgKjRHuR1uEM&m=Qg4BfcxFsNP5-erqI6CqOhKCvutOt1OGT1e3-Y5A1pjyN8yRZ2rNbR_U0thqnPVy&s=1Vi-up3hEdesDpLTV7_F7P-gab-EUmUh3L7Nlv3LSFg&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANBFGJESL2XSRR6EEYZI7XDZDO4CTAVCNFSM6AAAAABICAPC6SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRTGQ3TEMZVGA&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=3G-aGjxZDeuTcjb6O3sc_uRd88JsWnvXgKjRHuR1uEM&m=Qg4BfcxFsNP5-erqI6CqOhKCvutOt1OGT1e3-Y5A1pjyN8yRZ2rNbR_U0thqnPVy&s=sev3s_g5KDFAXaVgAEffI6VB09cSrdTFK7FPhG0QWAY&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
This email originated from someone external to Infragistics.
________________________________

**Comment by luispandolfi** [comment]
@CMcGuigan10, have you compared results by building the same report in Google Ads site? I believe it could exist ads that are not in an Ad Group but included in the Campaing, the difference could be there.

**Comment by brianlagunas** [comment]
Closing as there has been no response.
