### ISSUE TITLE
Risk Wheel chart feature Request

### ISSUE THREAD

**Issue by elaiyaraja-marimuthu** [RevealBi/Reveal.Sdk#209]
We have requirement from our client for a Risk Wheel Chart feature in the Reveal BI dashboard. Currently, this feature is not available.

The implementation of this feature is of high importance and we believe it will significantly enhance the user experience and provide valuable insights.

 Your prompt response will be greatly appreciated as this is a critical requirement from our client.
![image](https://github.com/RevealBi/Reveal.Sdk/assets/81211142/edf773bc-b520-4c50-afe6-47aca6d58856)

**Comment by brianlagunas** [comment]
This isn't a chart type that we would be adding any time soon. However, you could use a custom visualization to use your own version of this chart.

You can read about using custom visualizations here: https://help.revealbi.io/web/custom-visualizations

**Comment by brianlagunas** [comment]
Thank you for your idea, but we will not be implementing this chart in Reveal.
