### ISSUE TITLE
[BUG]: When switching between data tables in a data visualization tool, there is an issue where the fields in the left sidebar contain both English and Chinese characters.

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#21]
### Company

NA

### SDK Version

1.4.0

### Client Framework

React

### Server Platform

Java

### Description

Step to reproduce:
1.To enter the editing interface, select "Edit Data Table" under the data section on the left sidebar, and then choose the new data table B.
2.Selecting data from table B in the data pop-up window of a data visualization tool.
3.After switching to a new data table, it was found that the fields in the sidebar are mixed with both 
![TESTBUG](https://user-images.githubusercontent.com/37360991/230523378-ca102257-c1a8-4b8c-b2c8-8995f6f42899.gif)
Chinese and English.

**Comment by TorreyBetts** [comment]
Hi @suzakuzt,

Field names typically come from the connected data source. In your case it looks like Postgres. Would you be able to check the table definition for the one having both English and Chinese to see if they are actually defined that way?

**Comment by brianlagunas** [comment]
@suzakuzt Could you please respond to @TorreyBetts. If not, I will consider this issue resolved and close it. Thank you.

**Comment by brianlagunas** [comment]
I am closing this issue as it has had no response. This issue can be reopened if a response is received.
