### ISSUE TITLE
[BUG]: Export, runs too many "Chrome.exe" processes simultaneously

### ISSUE THREAD

**Issue by elaiyaraja-marimuthu** [RevealBi/Reveal.Sdk#214]
### SDK Version

1.6.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

lot of  chrome.exe created in prod servers and occupied lot of memory  .We configured chromium for export functionality
![image](https://github.com/RevealBi/Reveal.Sdk/assets/81211142/424010b4-fd04-4e17-8a7a-cc85d307538e)

**Comment by PVillarmarzo** [comment]
To have a better understanding, I ask: 
- Are you using server or client for exporting? 
- Is the export process functioning correctly? 
- Are there any errors in the log?

**Comment by brianlagunas** [comment]
Closing as there has been no response.

**Comment by MLopezIG** [comment]
It is our understanding that the sdk has been configured with:
`settings.Export.MaxConcurrentExportingThreads = 50;`

I see around 40 in the screenshot, so there doesn't seem to be any issue. 

Not closing as we should have confirmation here.

**Comment by elaiyaraja-marimuthu** [comment]
Now We  added max concurrent thread is 3 we will monitor continuosly then we will share update

**Comment by brianlagunas** [comment]
Can you share an update on if changing the max concurrent threads solved your issue?

**Comment by elaiyaraja-marimuthu** [comment]
As of now its not creating any issue we will close this
