### ISSUE TITLE
[BUG]: Google Analytics Filter Changing 

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#215]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Linux

### Description

I have set this filter to this: 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/ce093421-1050-4cbb-b724-5c7ae535e00c)

It keeps changing to this: 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/84c09e3c-b4ac-46ee-9726-21b577f10f14)

After I have saved and a period of time.

**Comment by luispandolfi** [comment]
We couldn't replicate this issue, and Casey have not seen it again.
