### ISSUE TITLE
[BUG]: Google Ads Error

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#216]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

Getting this error on our visualization for Google Ads in Mac: 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/e8abff8c-75d4-4504-b018-bf3ce704fe9f)

**Comment by brianlagunas** [comment]
Closing as there has been no response.
