### ISSUE TITLE
[BUG]: regarding the garbled text in REVEAL BI settings

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#218]
### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Java

### Operating System

Windows

### Description

1.Enter the REVEAL BI editing interface and select the data table editing settings.
2.After selecting "greater than or equal to" or "less than or equal to", garbled text appears in the Value Comparison Type.
![image](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/feac4e1c-b27a-4dce-b201-2e2a82106189)

**Comment by gkaveckis** [comment]
Hi @suzakuzt,
Thank you for sharing this with us
Regarding the issue and If it is possible, did you try a newer version of Reveal? now were in 1.6.6

Also are you using a specific language in your browser?

**Comment by brianlagunas** [comment]
Closing as there has been no response.
