### ISSUE TITLE
Add Method to add new Visualization 

### ISSUE THREAD

**Issue by pchlupacek** [RevealBi/Reveal.Sdk#219]
**Is your feature request related to a problem? Please describe.**

If the dashboard header is hidden, there is no way to add the new visualisation, b/c also the Add visualisation button is hidden. Having method that triggers adding visualisation programatically allows to trigger that action from custom UI. 

**Describe the solution you'd like**
Add method to RealView "addVisualisation". If possible, I would like to be able to specify which visualisation to add.  

**Describe alternatives you've considered**
There is a undocumented access to simulate click: 
revealView._dashboardView._headerView.__addSplitButton.mainClicked(); 

**Additional context**
---

**Comment by brianlagunas** [comment]
This method has been added to the Reveal SDK Web Component Wrappers

https://help.revealbi.io/web/web-component-wrappers/reveal-view/#addvisualization

In addition to the `addTextBoxVisualization` function

https://help.revealbi.io/web/web-component-wrappers/reveal-view/#addtextboxvisualization
