### ISSUE TITLE
[BUG]: Error in joining two datasets

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#22]
### Company

IMSPOS

### SDK Version

1.1.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Description

Today we are facing issue while trying to join two data sources . 

Below is a screenshot of error message.
<img width="1698" alt="Screenshot 2023-04-10 at 7 54 43 PM" src="https://user-images.githubusercontent.com/89643622/231167182-18755aa8-63d0-41d7-ac12-cee01f70566b.png">

 
Error message is "Can't read properties of null (reading tableAlias)"
 
Strange thing is that it was working fine before and we have not done any changes in code base. Could you please check if you can assist us in resolving this issue ?
 
We are currently running on Reveal SDK V1.1.4

**Comment by vishwa-ims** [comment]
@brianlagunas  Thanks for your response. We are using 1.1.4 SDK version from last couple of months and it was working perfectly fine . Yes we have Client and Server SDK in sync .

**Comment by brianlagunas** [comment]
It is not possible to answer that question without more information or context. If the code did not change, then it maybe you hit a bug which has recently been fixed. Is it possible someone else on the team change something that you are just not aware of? Maybe the SQL Server was updated or received a patch that caused the issue. Could there be something in the data cache that is causing issues? Maybe delete the Reveal cache files. It will be very hard to tell with little to no information.

Please let me know if upgrading to 1.4 fixes your issue. Also, be sure to research the breaking changes before you upgrade.

https://help.revealbi.io/web/release-notes

If you are still having issues after the upgrade then we may need to start looking at your environment.

**Comment by vishwa-ims** [comment]
@brianlagunas  could you please confirm the location of cache files ?
Is this C:\Temp\Reveal\Web\Cache ?

**Comment by brianlagunas** [comment]
Yes

**Comment by vishwa-ims** [comment]
@brianlagunas  Even after upgrading to V1.4 , we are still facing issue . Please let me know what all details you want to check this issue further

**Comment by TorreyBetts** [comment]
Hi @vishwa-ims,

I tried to reproduce the issue you mention and wasn't able to when using 1.4.0. Would you be able to edit the attached source to reproduce the issue? The edit you make needs to be something I'd be able to access to track down the issue if you're able to reproduce it. The attached source uses an Excel file as a data source, you can join Marketing & Sales through the Territory field.

[Data Blending Test.zip](https://github.com/RevealBi/Reveal.Sdk/files/11262940/Data.Blending.Test.zip)

Thanks!

**Comment by brianlagunas** [comment]
@vishwa-ims I just want to follow up. If we don't hear back, I will consider this resolved and close the issue.

**Comment by brianlagunas** [comment]
I am closing this issue as it has had no response. This issue can be reopened if a response is received.
