### ISSUE TITLE
Allow RevealSdkSettings.setAdditionalHeadersProvider to accept identification of the RevealView instance that is making the request. 

### ISSUE THREAD

**Issue by pchlupacek** [RevealBi/Reveal.Sdk#220]
**Is your feature request related to a problem? Please describe.**
Currently the provider accepts callback that has URL as only parameter. This is not enough if you need to add headers in context of RevealView instance. 

For example to implement SlideShow view that is using multiple RevealView instances on single page where each instance needs different context (i.e. customerId) to be passed as a source for later retrieval on server SDK for enhancing the UserContext, this is impossible. 

**Describe the solution you'd like**
Apart for passing the URL to the provider, add id of the RevealView (such as id that refers to DOM Element where RV is bound to)

**Describe alternatives you've considered**
Move RevealSdkSettings.setAdditionalHeadersProvider to RevealView. That way no Id will be necessary. 

**Additional context**
Note that we would also ask with this change to get Promise based provider if possible see #185

**Comment by pchlupacek** [comment]
Hi Reveal Team do you need some more information about this feature request ?  Thank you !

**Comment by brianlagunas** [comment]
We do not need more information. If you're just looking for an update, this feature has not been planned for implementation at this time. If/when this feature is accepted, we will update this issue.
