### ISSUE TITLE
[BUG]: Calendar picker does not use current timezone.

### ISSUE THREAD

**Issue by AdamChlupacek** [RevealBi/Reveal.Sdk#225]
### SDK Version

1.6.6

### Client Framework

HTML/JavaScript

### Server Platform

Node.js

### Operating System

Mac

### Description

The calendar picker is never offset to the current timezone. It it always assumed to be UTC. Which causes inconsistent queries and relative time displays to the user.

More info at discord: https://discord.com/channels/1050800659911430254/1252165848999919707/1253346636508299375

**Comment by MLopezIG** [comment]
Tracked internally by AB#13381
