### ISSUE TITLE
[BUG]: onFieldsInitializing causes exception for In-Memory data source

### ISSUE THREAD

**Issue by matthewquinn** [RevealBi/Reveal.Sdk#23]
### Company

Loadscan (trialing, not yet licensed)

### SDK Version

1.4.0

### Client Framework

React

### Server Platform

ASP.NET

### Description

The InMemory data source does throws when using the `onFieldsInitializing` event hook in on the RevealView.

This occurs when selecting an InMemory data source on the client for a new visualization. The error "Don't know how to deal with InMemory data source type" is logged in the console and the UI remains stuck in a loading state.

**Comment by brianlagunas** [comment]
We have verified this issue and have logged the internal bug AB#23398

**Comment by brianlagunas** [comment]
This has been fixed and will be available in the 1.5 release next week.
