### ISSUE TITLE
Lighten background color of filter search

### ISSUE THREAD

**Issue by pchlupacek** [RevealBi/Reveal.Sdk#232]
### SDK Version

1.6.7

### Client Framework

HTML/JavaScript

### Server Platform

Node.js

### Operating System

Mac

### Description

Currently the pickers of filtered values works with modal-only experience hiding the content of full window and focusing only on the value picker only providing sub-optimal user experience similar to mobile phone UX controls. 

Ideally, the search shall not be modal, and shall only filter displayed values.

**Comment by jberes** [comment]
@pchlupacek I think we misunderstood the issue.  In this screenshot, the entire background goes quite dark, so it's clear that it is like a mobile / modal UX.

![image](https://github.com/RevealBi/Reveal.Sdk/assets/18453092/69388f21-dcc9-4447-9399-668305ec6e82)


If we simply changed the color to not be so dark, so it matches the color of clicking the overflow for example, would that resolve the issue?

The entire UX is based on these 'modals', so we can't change that.  However, we _may_ be able to change it so the background is not so dark, it's simply the same (or lighter) than current.  Would that address the issue?

**Comment by pchlupacek** [comment]
Hi Jason, thank you very much for looking into it. 
This is exactly what we have been looking for. I think modal is completely ok, just the dark background has been a bit too much.  Transparent background will be completely ok, like you do in other modal cases. 

Sorry of not being clear in the requirement initially.

**Comment by brianlagunas** [comment]
Thanks for the additional detail. I am reopening this as a feature request.

**Comment by brianlagunas** [comment]
This has been implemented. The modal background color now matches the rest of the RevealView modal backgrounds

![image](https://github.com/RevealBi/Reveal.Sdk/assets/835562/7db2aece-fa40-4a78-9a15-f06b4537c314)
