### ISSUE TITLE
[BUG]: Date Calender is not responsive

### ISSUE THREAD

**Issue by VANSHIKAAGARWAL571** [RevealBi/Reveal.Sdk#234]
### SDK Version

Client SDK

### Client Framework

React

### Server Platform

Node.js

### Operating System

Mac

### Description

The Date Calendar is not customizable and is also not responsive. For some graphs the date is not getting responsive as we are loading it in our application and restricting its space. The button is not getting visible for some and even the scroll option not working. The dates are not reflecting correctly.

https://github.com/user-attachments/assets/282dc11d-a618-419b-afd1-b5f08549e9c2

https://github.com/user-attachments/assets/416f5275-1452-4d28-b065-19656c689ecb

![Image 15-07-24 at 1 00 PM (2)](https://github.com/user-attachments/assets/9bf85641-ed9a-4de7-bb45-a153dee08140)
![Image 15-07-24 at 1 00 PM (1)](https://github.com/user-attachments/assets/6fa3410b-57c5-4077-abdf-626734a499ff)
![Image 15-07-24 at 1 00 PM](https://github.com/user-attachments/assets/5ec694bd-df4d-4352-85e0-f835196610f4)
Please look into this issue as soon as possible

**Comment by brianlagunas** [comment]
This issueg has been fixed and will be available in our next release scheduled for the first week of Nov.
