### ISSUE TITLE
[BUG]: Nebraska is always colored green

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [RevealBi/Reveal.Sdk#241]
### SDK Version

1.6.7

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

<img width="744" alt="image" src="https://github.com/user-attachments/assets/d02adc3e-6b70-4fff-8340-8c2d474878b4">

Nebraska is always colored green.  This green isn't even in our chartColors collection for our theme.

**Comment by PVillarmarzo** [comment]
An internal issue was created regarding this report. Tracked with [AB#32988](https://infragistics.visualstudio.com/BusinessTools/_workitems/edit/32988)

**Comment by PVillarmarzo** [comment]
The solution for this BUG will be included in our next release.
