### ISSUE TITLE
[BUG]: Error - exceeded limit of string data

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#243]
### SDK Version

1.6.6

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We are getting below error message for large set of data . Not sure how to get it resolved ?

![image](https://github.com/user-attachments/assets/1b85854f-e811-4070-a1cd-4547baa619f7)

**Comment by gkaveckis** [comment]
Hi @vishwa-ims 

There is a setting that allows specify the string size as described below.

Please let us know if it works

services.AddControllersWithViews().AddReveal(builder =>
{
	builder.AddSettings(s => {s.MaxTotalStringsSize = STRING_SIZE;})

**Comment by brianlagunas** [comment]
This is covered in our caching doc topic: https://help.revealbi.io/web/caching/#cache-files

Closing as the `MaxTotalStringsSize` controls this behavior.

If you are still having issues let us know and we can reopen.
