### ISSUE TITLE
[BUG]: Cascading datasources are not refreshed when a user refreshs the dashboard or visualization

### ISSUE THREAD

**Issue by isabellacarroll** [RevealBi/Reveal.Sdk#244]
### SDK Version

1.6.4

### Client Framework

React

### Server Platform

Java

### Operating System

Mac

### Description

<img width="500" alt="Screenshot 2024-07-30 at 2 50 20 PM" src="https://github.com/user-attachments/assets/01a338f8-bc0a-4e0c-b211-116ab2fd821d">
When I select refresh here, any joined datasources are not refreshed.

**Comment by isabellacarroll** [comment]
We've also noticed the refresh is not refreshing data filters. When new data is added, and the datasource is refreshed, the data filter does not pick up the new values. Even when the field is removed and re-added.

**Comment by dpazos-infragistics** [comment]
Despite several attempts, we have been unable to replicate the issue.
Can you provide us with the .rdash that exhibits the issue so that we can take a look?

**Comment by brianlagunas** [comment]
Closing as we have had no response. If this is still an issue, let us know and we can reopen for further investigation.
