### ISSUE TITLE
[BUG]: WPF SDK: "Add a custom chart" does not work

### ISSUE THREAD

**Issue by norikois** [RevealBi/Reveal.Sdk#245]
### SDK Version

Reveal.Sdk.Wpf 1.6.7

### Client Framework

WPF, Angular

### Server Platform

N/A

### Operating System

Windows

### Description

1. Start the angular app in the reproducible sample.
2. Start the C_00238376_WpfApp1 app in the reproducible sample.
3. Click the add a visualization button.
4. Select the excel datasource.
5. Select the Marketing (or any sheet is ok).
6. Change the visualization to "CustomChart".
7. Select rows, columns, values, etc. from fields. -> Observe whether the preview is displayed.
8. Click save button and go back to dashboard. -> Observe whether the added visualization is displayed.

Actual:
Step 7: No preview is displayed. It's emplty.
Step 8: And the added visualization is not displayed when you go back to the dashboard.

Expected:
Step 7: Preview is displayed.
Step 8: The added visualization is displayed in the dashboard.

[C_00238376_CustomVisualization_Sample1.zip](https://github.com/user-attachments/files/16519829/C_00238376_CustomVisualization_Sample1.zip)

[Recording 2024-08-05 143735.zip](https://github.com/user-attachments/files/16519828/Recording.2024-08-05.143735.zip)

**Comment by brianlagunas** [comment]
Hey @norikois, seems there is a slight naming difference between the web version of the bridge and WPF. We will fix the naming conflict in our SDK, but for now simply change the name `revealBridgeListener` to `RPBridgeListener` and everything should work as expected.

Here is the full bridge with the fix for WPF
```
var host;
window.revealBridge = {
  sendMessageToHost: function (data) {
    try {
      var iframe = document.createElement("IFRAME");
      var message = encodeURIComponent(JSON.stringify(data));
      iframe.setAttribute("src", "js-frame:" + message);
      document.documentElement.appendChild(iframe);
      iframe.parentNode.removeChild(iframe);
      iframe = null;
    }
    catch (e) {      
      // The frame couldn't be created. 
      // This could happen in web environments when the host is not in the same domain than the custom view webpage.
      // Is not a problem as we are using window.postMessage for the communication in this case.
    }

    try {
      if (window.top && window.top.location) {
        window.top.postMessage(data, "*");
      }
    } catch (e) {
      // window.top.postMessage couldn't be executed.
      // This sould never happen but...
    }
  },

  notifyExtensionIsReady: function (formatting) {
    if (formatting) {
      this.sendMessageToHost({ message: "ready", formatting: true });
    } else {
      this.sendMessageToHost({ message: "ready" });
    }
  },

  runAction: function (actionName, data) {
    this.sendMessageToHost({ message: "runAction", action: actionName, rowData: data });
  },

  openUrl: function (url) {
    this.sendMessageToHost({ message: "openURL", URL: url });
  },
}

function processMessageFromHost(message) {
  
  if (!message || !message.data || !message.data.metadata) {
    return;
  }

  if (message.data.message) {
    // This is the same message that I'm sending to notify that the extension is ready and the iPad is sending it back here.
    return;
  }

  if (!window.RPBridgeListener) {
    return;
  }  

  window.RPBridgeListener.dataReady(message.data);
};

window.addEventListener('message', processMessageFromHost, false);

```

Tracked internally with AB#33299

**Comment by norikois** [comment]
Hi @brianlagunas ,
The code you gave me works fine on my side, too. Thank you very much!

**Comment by nerzhei** [comment]
This issue has been fixed and will be available in our next release. The custom visualization should work as per the documentation, and we've kept the old bridge name for compatibility.
