### ISSUE TITLE
Unable to show axis label name in chart

### ISSUE THREAD

**Issue by elaiyaraja-marimuthu** [RevealBi/Reveal.Sdk#247]
### SDK Version

1.6.4

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Unabe to set y axis label in all charts

**Comment by brianlagunas** [comment]
Can you please be more specific about what you are trying to accomplish? Which axis are you referring to? Where are you trying to display it? Can you provide any images of mockups of what you are asking for?  Based on the very limited information you provided, this sounds more like a feature request.

**Comment by brianlagunas** [comment]
Closing as we have not had a response.
