### ISSUE TITLE
[BUG]: InMemory DataSource opens editor directly when there is more than one ds available when visualization button is clicked

### ISSUE THREAD

**Issue by arunkumarpolisani** [RevealBi/Reveal.Sdk#249]
### SDK Version

1.6.7

### Client Framework

React

### Server Platform

Java

### Operating System

Mac

### Description

https://github.com/user-attachments/assets/cacd7aca-a53d-4864-a926-68fac955ef9c

Hello Reveal Team, When I add an InMemory DataSource along with other datasource like MySQL etc and when I open a Dashboard and click on Visualization button for editing, I see some errors
First, I don't see pop-up to select the datasources or datasource items. When I click on the Visualization button, the editor directly opens with inmemory datasource item. If I remove the InMemory ds from my code, I see the selection popup as expected to select a datasource from the available options. Instead of showing pop-up for DS selection, why in-memory ds item directly opens for editing?
I have to edit the datasource in editor, navigate back to see the selection of datasources and select an item. I see my selected table opens, but the title doesn't change, it still shows the title of inmemory ds item's title.
Is this default behavior when InMemory DS is added along with other types of DS with what I am facing with above 2 issues?
Please find screen recording attached with above issues.

**Comment by brianlagunas** [comment]
This has been fixed and will be available in our next release scheduled for end of Oct / beginning of Nov.
