### ISSUE TITLE
[BUG]: Reveal BI multiplication and division formula Issues

### ISSUE THREAD

**Issue by mahtnar** [RevealBi/Reveal.Sdk#252]
### SDK Version

1.6.4

### Client Framework

Angular

### Server Platform

None

### Operating System

Linux

### Description

Multiplication and division formula is not working as expected. Below mentions the formula
Multiplication :
**if(isempty([num1]),1,[num1]) * if(isempty([num2]),1,[num2])**

**Comment by mahtnar** [comment]
Sharing screenshot of dummy data on which we performed the multiplication and division operation.

Multiplication and division formula is not working as expected. Below mentions the formula
Multiplication Formula :
if(isempty([DA_Currency]),1,[DA_Currency]) * if(isempty([AOSD_Currency]),1,[AOSD_Currency])

Actual Result : Please find in below screenshot

Expected Result: 100,000 * 100,000 = 10,000,000,000
Similarly, Please check it should calculate for other rows. But expected result is not matching actual result for other cases where multiplication formula used.

![image](https://github.com/user-attachments/assets/f961b136-902f-4c56-b43b-a54f1387c977)

![image](https://github.com/user-attachments/assets/1143b9d4-0716-408f-8e0a-7519dfd44f90)

![image](https://github.com/user-attachments/assets/e23bdd5b-3c18-49bf-bb91-84558802e612)


Division Formula :
if(isempty([DA_Currency]),1,[DA_Currency]) / if(isempty([AOSD_Currency]),1,[AOSD_Currency])

Actual Result : Please find in below screenshot

Expected Result: 100,000 / 100,000 = 1
Similarly, Please check it should calculate for other rows. But expected result is not matching actual result for other cases where division formula used.

![image](https://github.com/user-attachments/assets/88da898f-c374-4ebb-b084-71b5b3473f33)

![image](https://github.com/user-attachments/assets/00aeded6-705c-4709-a44f-be6c0508c1c0)

**Comment by TorreyBetts** [comment]
@mahtnar What kind of data source did you use?

**Comment by mahtnar** [comment]
restapi data source

**Comment by MLopezIG** [comment]
@mahtnar Looks like what you need there is to make use of the 'post calculated' fields, instead of regular calculated fields. Those are created as shown in the following image, and will operate on aggregated values:

![image](https://github.com/user-attachments/assets/d2358014-410b-4e6c-932c-e43012aeee97)
