### ISSUE TITLE
[BUG]: Column names not always alphabetized

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [RevealBi/Reveal.Sdk#255]
### SDK Version

1.6.7

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

The column names for data items aren't always alphabetized.  This goes for the list down the left side of the Edit Visualization view as well as drop down menus in filters, etc.  I will share screenshots in a DM with Brian L.

**Comment by brianlagunas** [comment]
We have not been able to replicate this issue. Do you have a sample dashboard that this happens to?

**Comment by brianlagunas** [comment]
We have been unable to replicate this behavior. I am closing this issue for now. If you are able to consistently reproduce it, then let me know and I can reopen for further investigation.
