### ISSUE TITLE
[BUG]: Visualization filters erroring when Calculated Field exists and is part of a data filter.

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [RevealBi/Reveal.Sdk#256]
### SDK Version

1.6.1

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We are getting an error if we add a Visualization filter and there is a Calculated Field.  The one scenario we can consistently reproduce is when the Calculated Filter is added as a Data Filter.  But, there seem to be other times as well, although we can't consistently reproduce.  Also, if you use the calculated field in any kind of sort scenario, it will fail, unless you turn off server side data when adding the data item.  I will share a screenshot with Biran L.

**Comment by brianlagunas** [comment]
This has been verified and logged internally with AB#33356

**Comment by nerzhei** [comment]
This has been fixed and will be available in our next release.
