### ISSUE TITLE
[BUG]: The GA4 Connector is missing the custom events to use in dashboards

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#258]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

<img width="574" alt="image" src="https://github.com/user-attachments/assets/72eed869-0be6-4160-86e9-f5461f4cce99">

**Comment by luispandolfi** [comment]
@CMcGuigan10, Is this issue the same as https://github.com/RevealBi/Reveal.Sdk/issues/228 ?

**Comment by brianlagunas** [comment]
Closing as duplicate.
