### ISSUE TITLE
API to modify the dashboard files in Java

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#26]
**Is your feature request related to a problem? Please describe.**

There are some cases where we've wanted to edit the dashboards programmatically.

The most recent one was we wanted to replace an old data source by another, but all customer dashboards were already using the old data source's url. So we couldn't do it (would have to edit tens of dashboards through the UI).

But also this would give us more possibility for workarounds like those of issues #19 and #25: we could edit the dashboard before asking the server-side export API to generate the PDF.

**Describe the solution you'd like**
An API to load and edit the rdash files. Similarly to the JavaScript API that let's us pass an rdash (`loadDashboardFromContainer`) and we get back a RVDashboard where we can invoke methods.

**Describe alternatives you've considered**
I discarded doing it myself as the rdash format is not documented, so even though I think nothing would break if I change one or two things, there is no guarantee.

**Comment by dwilches** [comment]
@gauxgaux In case you're still using Reveal, they have now a beta API to look inside dashboards and modify them: https://github.com/RevealBi/revealbi-dom

This is from the JS side, not JS, but at least in my case that was enough.

The API is undocumented, but I gave it a try and it seems fairly complete, I managed to grab visualizations from 2 different dashboards and merge them together in a new dashboard, so it's worth a try.

Also to keep in mind:
>  Dom library is an Open Source convenience, it is not part of the Reveal product and is not supported in that same way.

**Comment by brianlagunas** [comment]
After much deliberation, we have decided not to create a version of the DOM for Java. We are currently only supporting C# and Typescript/JavaScript.

We will be working to make the current versions of the DOM part of the reveal product by adding unit test coverage, samples, and docs.
