### ISSUE TITLE
Add multi-value to Donut/Pie Chart 

### ISSUE THREAD

**Issue by pchlupacek** [RevealBi/Reveal.Sdk#261]
**Is your feature request related to a problem? Please describe.**
Currently Pie/Chart donut visualisation do not accept multiple value fields. When having table where series are in columns, there is no way how to display these series in Pie Chart/Donut. 

**Describe the solution you'd like**
This feature requests asks to add multiple series functionality to PieChart/Donut similarly like some Visualisations already have (i.e. Time Series).  

**Describe alternatives you've considered**
There is no alternative available up to my knowledge. 

**Additional context**

**Comment by brianlagunas** [comment]
My initial thought is based on your data structure, the Pie/Donut is not the correct visualization to use. However, could you provide more context or information regarding this request? Perhaps an image of what you expect the pie chart to look like when given two values?

**Comment by pchlupacek** [comment]
Hi Brian, 

lets assume following Data: 

Date | Calls | Chats 
-----|------|------
Jan | 5 | 10
Feb | 3 | 5
Mar|  10 | 7

What I want to be able to have is to du Sum over chats and calls and have Pie / Donut showing 18Calls / 22 chats. 
Also, this table could be used as time series, where Jan/Feb/March will be on "X" axis and two series Calls/Chats will be displayed with values on Y axis. 
Does that make a sense? 
I am open to any other approach with the Reveal if you would be so kind to point me out in correct direction. Thank you !

**Comment by jberes** [comment]
Hi Pavel - I am not sure I completely understand what you need, however using the transpose data along with calculated fields might be of value.  Check out this video to see if it helps.

https://app.screencast.com/mLmYNy3P30DyZ

The results would look like this:

![image](https://github.com/user-attachments/assets/2026716b-c051-4037-9b4f-708c6a950e2b)

**Comment by pchlupacek** [comment]
HI @jberes thank you for the tutorial. That may work in this simple table (I purposely made the problem simple so I would be able to explain it), will try how this will for for ODATA data source. I have added XLS file with Pie chart diagram so it is clear which functionality I am looking for. 

I think is defacto standard for any piechart / donut functionality.  Tried this in Goggle Sheet, Apple Numbers and MS Excel and all have this functionality where you may specify for pie slices the sum of particular column value 

Please see attached file. 

Thank you ! 
[Untitled.xlsx](https://github.com/user-attachments/files/16670258/Untitled.xlsx)

**Comment by jberes** [comment]
This is what Excel does - 

![image](https://github.com/user-attachments/assets/48286733-3276-4faf-a2ac-0ef8ea8579f0)


If there is an automatic way in Excel to make your goal 
chart, I can't seem to figure it out.

**Comment by pchlupacek** [comment]
Hi @jberes it looks like only one month is grabbed, so we would have to do SUM first to have correct data. 

I think the functionality is perhaps more complex what we asking here - 1st we need to define the Aggregation (i.e. sum/count) and then we have to be able to use columns to specify slices. 

You are completely right that this could be achieved by remodeling input data shape. We will try to find workaround around these lines. 

However, I still believe that from user perspective this may be useful visualisation feature. I will see how for example Looker and BI are achieving this. 

Not sure if you share my point of view there and if we shall invest into this a bit more?

**Comment by jberes** [comment]
IMO if you can't do it in Excel with the auto-charting, like grab the table and show the chart, it's a data issue.  Something like time-series is very specific, lines are the way to deal w/ it.

Since this is doable w/ some data-massaging (plus possibly calculated field), it's the way to go, it seems to work pretty well.  I'd pursue that approach.
