### ISSUE TITLE
[BUG]: Reveal Viewer not respecting Data Source Ids for unique identifier

### ISSUE THREAD

**Issue by sswfrd** [RevealBi/Reveal.Sdk#264]
### SDK Version

 v.1.6.7-rc29

### Client Framework

Angular

### Server Platform

None

### Operating System

Windows

### Description

The client is using the data source Host Name as the unique key.  This is causing an issue when there are more than one data source with the same host but different database user login. The data source should use the Id as the unique identifier to ensure it is unique.

"As I mention before, Reval tries to be smart about reusing data sources that have the exact same connection properties regardless of the ID you use. So to force Reveal to skip this logic, we want to use fake info on the client."

**Comment by sswfrd** [comment]
Is this redesign going to be mandatory?  Our current source of truth is the client. We only add the username / pwd on the server.

**Comment by brianlagunas** [comment]
Not initially. But one day (could be years) client-side data sources will go away. The server is always the truth for all data for a web application. Never the client. Clients can't be trusted since they can be easily manipulated.
