### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by smwfrd** [RevealBi/Reveal.Sdk#265]
### SDK Version

v.1.6.7-rc29

### Client Framework

Angular

### Server Platform

None

### Operating System

Windows

### Description

While attempting to edit a dashboard, we occasionally encounter Infragistics error, which disrupts all reveal viewer instances. In this faulted state, dashboards still load, but none of the instances can enter the edit mode until the client is reloaded or opened in a new tab. 

![image](https://github.com/user-attachments/assets/52a37aaf-48af-4919-ab84-35c3908c3c03)

What would be the most effective way to handle exceptions of this nature on the client side? In our case, the above exception is occurring when we attempt to edit dashboard or visualization. Once this happens, the Reveal viewer does not accept any edits, and the editing functionality remains broken even if we switch to other dashboards. To restore the ability to edit, we are having to open the application in a new browser tab.

**Comment by brianlagunas** [comment]
Wasn't this issue already addressed in Discord?

https://discord.com/channels/1050800659911430254/1184523792488333343/1278869553182670849

The response is that you need to keep your client versions in sync with your server version (you had mismatched versions), and that the fix would be in our next release, which would be scheduled for this week.

**Comment by smwfrd** [comment]
Yes, I was informed that this will be resolved in the next release. Meanwhile, I'm interested in learning how to best manage these exceptions on the client side.

**Comment by brianlagunas** [comment]
When you run into exceptions that cause the RevealView to stop working, simply report them to us here with as much information as possible, and we will get the bugs fixed. There is nothing specific for you to do on your end.

**Comment by brianlagunas** [comment]
I'm going to close this as we believe we have already fixed this issue. Our release got pushed to next week. When the release is available, try it out and let us know if you are still having issues with this.
