### ISSUE TITLE
[BUG]: Value on DateTime reporting incorrectly on Click / Hover events

### ISSUE THREAD

**Issue by jberes** [RevealBi/Reveal.Sdk#267]
### SDK Version

1.6.7

### Client Framework

HTML/JavaScript

### Server Platform

None

### Operating System

Windows

### Description

![image](https://github.com/user-attachments/assets/6fefa161-fec7-4441-a355-2db8e5dfe5c7)

The value is being reported as the previous Day, Month, Year in the cell/row args when using both:

- onVisualizationDataPointClicked
- onTooltipShowing

Hover / Click on Dec 25, value is Dec 24
Hover / Click on 1997, value is 1996
Hover / Click on December, value is November 30th

**Comment by brianlagunas** [comment]
Is this using one of our sample dashboards? If so, which one?

**Comment by jberes** [comment]
No a sample I am using.  I can post a sample.

**Comment by PVillarmarzo** [comment]
An internal issue was created regarding this report. Tracked with [#33792](https://infragistics.visualstudio.com/BusinessTools/_workitems/edit/33792)

**Comment by MLopezIG** [comment]
This is working as expected. 
What's happening here is that the browser is showing you the Date objects by formatting them using the local time zone. For January 1st 2024 UTC, that's December 31 2023 in your timezone.
