### ISSUE TITLE
More control for hiding visualizations

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#27]
**Is your feature request related to a problem? Please describe.**

We have dashboards that are shared among our customers, and would like to hide one of the visualizations for some of the customers as it doesn't apply to them (it shows data for a product they don't have). It's kind of a dashboard that shows a high-level view of all the products they have contracted with us, so depending on what products they have contracted I would like to hide some visualziations.

I thought of locating the visualization in the `RVDashboard` object (in the Javascript side) and removing it from the `RVVisualization` array, but I see in the `d.ts` that the value returned by the `visualizations` field is readonly, so I shouldn't be tampering with it:

```javascript
class RVDashboard {
    ...
    /**
     * The list of visualizations in the dashboard.
     */
    get visualizations(): readonly RVVisualization[];
    ...
}
```

Is there a way to remove a visualization programmatically?

**Describe the solution you'd like**

I was thinking of something like this, akin to the `getByTitle` method of `VisualizationsArray`:

```typescript
revealView.dashboard.visualizations.removeByTitle("Feature XYZ");
```

**Describe alternatives you've considered**
Creating a new dashboard for some customers is our current alternative. Although this won't scale well in the case we have 2 independent features as that would mean having 4 variations of the dashboard, if we have 3 features it means 8 variations, etc.

**Comment by brianlagunas** [comment]
What platform do you need this functionality in?  I ask because there is a DOM (Document Object Model) for .NET that can be used to achieve this today.

**Comment by dwilches** [comment]
I use Java on the backend. Although my request above was for a way to do it in the frontend.

**Comment by brianlagunas** [comment]
@dwilches I found a work-around for you so that you don't have to wait for a Java DOM or for this to be added to the API.

```js
const vizTitleToRemove = "Sales by Product";
const vizArray = dashboard._dashboardModel.__widgets.filter(x => x._title != vizTitleToRemove)
dashboard._dashboardModel.__widgets = vizArray;
```

basically, just manipulate the `dashboard._dashboardModel.__widgets` array and you'll modify the visible visualizations.

**Comment by brianlagunas** [comment]
We now have a beta of a client side DOM on npm. Install the `@revealbi/dom` package.

Here's a quick example of how you might remove a visualization
```
    const document = await RdashDocument.load("Sales");
    document.visualizations.splice(0, 1); // remove first visualization
    const dashboard = document.toRVDashboard();

    let revealView = new $.ig.RevealView("#revealView");
    revealView.dashboard = dashboard;
```

Let me know if this will work for you and if you run into any issues

**Comment by brianlagunas** [comment]
This is being closed as the new JavaScript DOM will be the recommended way to modify dashboards on the client.

**Comment by dwilches** [comment]
Hello,
Thanks, it look great to have this API on the JS side.
