### ISSUE TITLE
Adding a URL - Open in same tab

### ISSUE THREAD

**Issue by sswfrd** [RevealBi/Reveal.Sdk#272]
We would like the option to determine if the Linked URL should open in a new tab or the current tab.

**Describe the solution you'd like**
Perhaps a radio button or drop down to allow the user to choose the target, defaulting to new tab.

![image](https://github.com/user-attachments/assets/0b1096b0-0091-4973-83a5-0196ceebe063)

**Comment by brianlagunas** [comment]
Should this be a public setting that you set when creating the link, or should this be something that can only be controlled via an API within the SDK?

Do you want your end-users being able to decide the target, or should your app control that?

**Comment by sswfrd** [comment]
I would think this would be a per link decision. Our particular use case does not need to lock down the options so the end user does not have a choice.

**Comment by brianlagunas** [comment]
Would you like an ability to override the end-user's target?  Maybe something like

```
revealView.onUrlLinkRequested = (args) => {
    args.target = "some_target"; //force a different target
    return args.url + "&webUpdated=true&cellValue=" + args.cell.value();       //augment the link with new parameters        
};
```

**Comment by sswfrd** [comment]
I do not know of a current use case, but everyone likes more options.

**Comment by nerzhei** [comment]
This has been implemented. A new 'Target' option has been added to control where the link opens.

![image](https://github.com/user-attachments/assets/e16f27bc-4700-4dc6-a57e-712757354a75)

Additionally, you can perform the override as Brian suggested above.

It will be available in the upcoming release.
