### ISSUE TITLE
[BUG]: Unable to view 1.7.0 features 

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#273]
### SDK Version

1.7.0

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Hi,
We have just updated SDK to 1.7.0 but we are not able to view below listed features even though required settings are enabled . Could you please confirm what UI level changes we can see to confirm if below settings are enabled ?

1. (Beta) Compare filtered data within the same visualization. The series tooltip includes an option to filter by the selected value. The rest of the visualization will display both the filtered values and the original ones for easy comparison. In this release support was added for funnel, treemap, and gauges. This functionality is currently supported in the following chart types: Column, Bar, Line, Time Series, Area, Step Area, Spline, Stacked Column, Stacked Area, Stacked Bar, Funnel, Treemap, and Gauges. To enable this functionality, set highlightedFilteringEnabled to true on the RevealView.

2. Server side grid paging is now available without requiring the enableBetaFeatures flag in $.ig.RevealSdkSettings. Paging is supported in the following providers: SQL Server, MySQL, BigQuery, PostgreSQL, SyBase, Athena, and Oracle. The providers that support stored procedures will have grid paging disabled when a stored procedure is selected as these can't be queried like tables to return a range of rows. Additionally, paging is not available when processing data on server is false, as well as when using blended data - (this might help with dashboard performance on large data.)

3. (Beta) Visualization toolbar was added to quickly access trend-lines, labels, zooming, etc. To enable this functionality, set enableNewToolbar to true on $.ig.RevealSdkSettings

**Comment by brianlagunas** [comment]
First make sure you have both the client, and the server updated to 1.7.0.

1. For the highlighted filtering beta feature, the property to turn it on is actually `revealView.interactiveFilteringEnabled = true;`. We'll update the docs. Also, the highlighting is only applied when you filter by using the tooltip filter button
![image](https://github.com/user-attachments/assets/7368db73-48b8-45f3-bf13-caa3982e6fdb)

2. Grid paging must be turned on in the settings of the grid visualization.
![image](https://github.com/user-attachments/assets/5902ec4f-8244-4093-835b-8b0c4ff514d8)

3. The property to turn on the toolbar is `$.ig.RevealSdkSettings.enableNewToolbar = true;`. Then the toolbar will appear in supported visualizations.
![image](https://github.com/user-attachments/assets/0947d843-b2db-44f9-a008-cc8db238213b)

**Comment by vishwa-ims** [comment]
@brianlagunas  can you please help on this "Grid paging must be turned on in the settings of the grid visualization.". I am not able to turn ON these settings . Could you please help exact settings name for this ? Thank you

**Comment by brianlagunas** [comment]
@vishwa-ims I'm confused, I provided a screenshot of the exact settings for grid paging that can be found under the settings tab of the visualization editor.

**Comment by vishwa-ims** [comment]
@brianlagunas  I am not able to see grid paging settings options . Not sure if I am doing anything wrong . 

<img width="419" alt="image" src="https://github.com/user-attachments/assets/008def81-ae93-4615-8981-6800e99376ac">

**Comment by brianlagunas** [comment]
Paging does not work with the PivotGrid, only the standard Grid.

**Comment by vishwa-ims** [comment]
@brianlagunas  thank you . Paging is working fine now . We have also enabled $.ig.RevealSdkSettings.enableNewToolbar = true; but not able to see toolbar . Could you please confirm which visualisations will have this toolbar ?

**Comment by brianlagunas** [comment]
The financial charts, and the majority of the category charts minus the pie, doughnut, and funnel.
