### ISSUE TITLE
[BUG]: timeout error

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#276]
### SDK Version

1.7.0

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Getting below error message
![image](https://github.com/user-attachments/assets/16b1c793-6c3c-46f4-a03b-18d8a9726e9c)

**Comment by luispandolfi** [comment]
Hi @vishwa-ims, this is not a bug, it is a timeout and could happen in several scenarios. Please, add more information to be able to replicate the bug, or contact us in Discord first for assistance. Thanks.

**Comment by vishwa-ims** [comment]
Hi ,

Do we have any setting where I can increase the timeout limit ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by luispandolfi** [comment]
Unfortunately not, we do not have a setting for the execution timeout.
What is your data source type?
Is the timeout only happening in that visualization?
Do you have another visualizaton with the same data source working?

**Comment by luispandolfi** [comment]
Hi @vishwa-ims, any updates on this issue?
