### ISSUE TITLE
[BUG]: Chromium Browser Instance Not Disposed Properly After Export

### ISSUE THREAD

**Issue by vinodkumarrajan** [RevealBi/Reveal.Sdk#281]
### SDK Version

1.6.4

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

**Summary:** After performing export operations (Image, PDF, and PowerPoint) using the Chromium browser, the browser instance is not disposed of properly. This results in a significant increase in server memory usage.

**Steps to Reproduce:**

Perform an export operation (Image, PDF, or PowerPoint) multiple times.
Monitor the server memory usage.

**Expected Result:** The Chromium browser instance should be disposed of properly after the export operation, and server memory usage should remain stable.

**Actual Result:** The Chromium browser instance is not disposed of properly, leading to an increase in server memory usage.

**Impact:** This issue causes a significant increase in server memory usage, which can lead to performance degradation and potential server crashes.

**Note:** We tried to dispose of the Chromium instance from our side after the export is completed. However, after disposing of the Chromium instance, the export functionality stops working.

**Comment by MLopezIG** [comment]
Hi there! Chromium instances are pooled to improve response times for the export functionality. The default number of instances is 2, and can be controlled with the MaxConcurrentExportingThreads setting. 

At least one chromium instance is needed for export, so the server available memory should be enough to accommodate at least one for its lifetime.

**Comment by vinodkumarrajan** [comment]
Hi There,

While exporting there is 4 instances of chromium is created. Is there are sub processes? (i set the maxConcurrentExportingThreads to 1)

**Comment by MLopezIG** [comment]
Yes, at least on my environment I see one chromium process plus other 3 that are sub-processes of that one.

**Comment by vinodkumarrajan** [comment]
Thanks for sharing the details. Could you please clarify the following scenario as well? It would help us find some workarounds on our side.

When I tried to forcefully kill the Chromium process after exporting (once the export is completed), further exporting stops working. 
To be clear,
**Step 1:**  When I launch the application, there is no Chromium browser. 
**Step 2:** After exporting to PDF, I can see the Chromium browser in processes. 
**Step 3:** I kill the Chromium browser from our end by capturing the completion of your API. 
**Step 4:** Then, when we try to export to PDF again, it does not work. 
The expectation is that it should start Chromium again if there is no Chromium browser and perform the export.

**Comment by MLopezIG** [comment]
Hi, those instances should not be killed externally. If the reason you're killing them is b/c you get more than the expected number of chromium instances, please check the usage of 'MaxConcurrentExportingThreads'. If instances still grow higher than expected, then there must be something else that needs investigation. In our tests, the number of instances remain controlled.

**Comment by vinodkumarrajan** [comment]
Hi, 
As per our observation, the Chrome instance problem does not occur in our production environment if we disable the export to PDF/Image/PowerPoint in revealBI. It reproduces in the production environment when we enable export to PDF/Image/PowerPoint and it is used by multiple users. As per your suggestion, we are currently using MaxConcurrentExportingThread = 1. I will observe its effect and update you further.

**Comment by luispandolfi** [comment]
Hi @vinodkumarrajan, any updates on this issue?

**Comment by brianlagunas** [comment]
@vinodkumarrajan Great to hear. I am closing this issue. If you run into any other problems, be sure to open another issue.
