### ISSUE TITLE
[BUG]: Text Box Showing "There's no data to display"  

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#282]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Linux

### Description

![image](https://github.com/user-attachments/assets/d503b916-8738-47fa-ada3-3c3e743e6618)

Internal issue [AB#33745](https://infragistics.visualstudio.com/14a7928c-44bc-4aed-b2ca-9a0ffbb14d7a/_workitems/edit/33745)

**Comment by luispandolfi** [comment]
This issue was already fixed, will be available in the next release. AB#33745
