### ISSUE TITLE
[BUG]: Error with off-screen Paged Row Grid (1.7.0)

### ISSUE THREAD

**Issue by Hawkeye66** [RevealBi/Reveal.Sdk#286]
### SDK Version

1.7.0

### Client Framework

Angular

### Server Platform

None

### Operating System

Windows

### Description

We have a fairly busy dashboard with a number of visualisations that you have to scroll down to see. One of those that is off-screen on initial load is a grid using the new paged row featue.

On loading this dashboard, the visualisations that are initially visible on the screen take a few seconds to load. Once they are loaded, if you then scroll the page down, as soon as the paged row grid would start to come into view, we get a console error within the `setMinimizedActionIcon` function trying to access `this.__theme.foregroundColor()` which fails due to `this.__theme` being null.

If we move this visualisation up the dashboard so it's visible on initial load it's fine. If we scroll the dashboard page down quickly before the initially viewable visualisations have finished loading it's fine. And in particular, if we turn off paged row it's fine.

100% reproducible.

**Comment by brianlagunas** [comment]
This has been fixed and will be available in our next release planned for the first week of Nov.
