### ISSUE TITLE
[BUG]: Dashboard filters visible even though showFilters is set to false

### ISSUE THREAD

**Issue by bart-credlens** [RevealBi/Reveal.Sdk#287]
### SDK Version

1.7.0

### Client Framework

React

### Server Platform

Node.js

### Operating System

Linux

### Description

I've got a single dashboard with 3 visualizations and I've created dashboard filters for 2 of the 3 visualizations and control them with my own widgets.  And because I've got my own filter widgets, I want to hide the ones provided by Reveal and this is working as expected by setting `showFilters` to false.  

However, if I maximize a visualization and click Refresh on the maximized visualization, the dashboard filters reappear even though they shouldn't be displayed.  If I minimize the visualization and maximize again, the filters are not displayed but anytime Refresh is clicked, the filters are displayed.

Here is a video showing this behavior.
https://github.com/user-attachments/assets/4a81e9a2-2a77-4c58-b6dc-b0c1aaef32ac

**Comment by brianlagunas** [comment]
This should be reviewed along with #278 as it appears they could be related.

**Comment by PVillarmarzo** [comment]
The bug was created internally and you can track it from here #[34594](https://infragistics.visualstudio.com/BusinessTools/_workitems/edit/34594)

**Comment by nerzhei** [comment]
This has been fixed and will be available as part of the next release.
