### ISSUE TITLE
MongoDB Connector generates inefficient queries

### ISSUE THREAD

**Issue by rivadblins** [RevealBi/Reveal.Sdk#288]
### SDK Version

1.7

### Client Framework

Other

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We have been hitting some performance bottlenecks with our MongoDB instance and have narrowed it down to the query being generated by RevealBI when using a MongoDB datasource. We have narrowed down the culprit to the $match statement that is being created. We have created indexes and compound indexes to help with performance. For some background, we have a CustomQuery set to match the field policyId to a value tied to the currently authenticated user. This policyId identifies a group of users for which we want to retrieve statistics for. The $match generated by reveal looks like this:

{ "$match": { "policyId": "{policyId}" } },
{
  "$match": {
    "$expr": {
      "$and": [{ "$in": ["$eventSubType", ["Create", "Update", "Delete"]] }]
    }
  }
}

Because there are two match statements we found that instead of using the compound index we created for eventSubType and policyId it would only use the policyId index which returned over 750k unrelated results. Using Mongo's explain command we traced that this then results in all 750k documents being fetched so that the next $match can be executed against those. This took nearly 60 seconds to complete making the dashboard unusable.

I wrote some integration tests to validate different query formats. Combining the two in this way:

{ 
"$match": { "policyId": "{policyId}",
    "$expr": {
      "$and": [{ "$in": ["$eventSubType", ["Create", "Update", "Delete"]] }]
    }
  }
}

Helped with performance very little. It went down from 60 seconds to 47 seconds. I was a little confused by the way that this query was built and tried the more simple $in method:

{
  "$match": {
    "policyId": "{policyId}",
    "eventSubType": { "$in": ["Create", "Update", "Delete"] }
  }
}

With this our performance significantly increased, we were able to execute this in 6 seconds. Even testing with 2 matches instead of combining them yielded the same performance increase. I also read through the Mongo documentation here https://www.mongodb.com/docs/manual/reference/operator/query/expr/ and the main culprit is that $expr. The way that the match is built for that is mimicking an $in statement, but Mongo can't optimize it since the $expr evaluates against every single document. Once it gets the documents from the policyId match back, it doesn't use the eventSubType index and instead goes through each document, resolves the eventSubType field value, then checks if that resolved value is in the list.

The optimized query is able to use the compound index and so it doesn't need to resolve all the documents and can just use the index. Even having two separate match statements instead of combining them is fine, as long as the $expr isn't used.

**Comment by MLopezIG** [comment]
This issue is being internally tracked as: [AB#34200](https://infragistics.visualstudio.com/BusinessTools/_workitems/edit/34200/)
