### ISSUE TITLE
[BUG]: REST Endpoint Datasource calls sometimes do not get the dateFilterFrom and dateFilterTo populated

### ISSUE THREAD

**Issue by rivadblins** [RevealBi/Reveal.Sdk#293]
### SDK Version

1.7

### Client Framework

Other

### Server Platform

ASP.NET

### Operating System

Windows

### Description

When making calls to a REST Endpoint with date filter parameters, the date filter parameters are sometimes not populated.

We observed an unpredictable behaviour where sometimes the dateFilterFrom and dateFilterTo parameters were not being populated, but this was not consistent. Sometimes it was the from, sometimes it was the to. Sometimes it was neither for the same selected value.

I was not able to replicate this reliable, but did notice it happened more frequently when choosing values such as "Last 30 days" or "Previous Quarter". We had to add special parsing and handling to deal with this scenario.

Ideally, regardless of what value is selected in the date filter both the from and to should be populated, or at the very least the from should always be populated.

**Comment by rivadblins** [comment]
I'm not sure how I could create a sample that could replicate it without that sample going to our endpoint, is there anything else that I might be able to capture or do to provide additional information? As far as I am aware we are not doing anything out of the normal for an ASP.NET backend. Could it be related to our Vue frontend? I know Vue isn't directly supported but I'm not sure how it could cause this issue.

**Comment by MLopezIG** [comment]
We can stub the endpoint if necessary, with your help. So that's still an option to move forward IMO.

In the meantime, if you can share the dashboard, and your extension point implementations (in particular the datasource/usercontext providers) that might help too.

And if you're able to reproduce, and can capture the request/response (e.g. from the 'Network' tab in Chrome's Dev tools), as well as what you see in your endpoint, it can complement the other information here.

We don't think using Vue is related.

**Comment by brianlagunas** [comment]
@rivadblins When you get a chance can you provide the requested information. We cannot move forward until we have enough info to replicate the issue.

**Comment by rivadblins** [comment]
[syncdashboard.json](https://github.com/user-attachments/files/17667108/syncdashboard.json)
![image](https://github.com/user-attachments/assets/156c08b1-b3f8-4ea8-9198-dfc2be16b55a)
![image](https://github.com/user-attachments/assets/8154774a-82ad-48bf-856b-9717418c34fd)
![image](https://github.com/user-attachments/assets/2ea1a97e-454b-4b08-aa98-263fb53c0875)

Attached is our dashboard.json file, an image our of datasource provider and usercontext provider, and and image of the definition for our endpoints. I will try to capture a trace.

**Comment by MLopezIG** [comment]
@rivadblins thanks for sharing. That ChangeDataSourceItemAsync needs to be fixed. Not your fault, the implementation of that method that we require is not trivial (we're working to improve that). Please take a look at my suggestion on your other issue, #294 where you'll see a skeleton of how the method should look. In particular, what you're missing there is the recursive call to ChangeDataSourceItemAsync on the dataSourceItem.ResourceItem.

**Comment by brianlagunas** [comment]
I am closing this as there has been no response. I am assuming that Mauro's feedback helped point you in the right direction to fix your issue.
