### ISSUE TITLE
[BUG]: Selecting "All Time" date filter causes visualization render to break

### ISSUE THREAD

**Issue by rivadblins** [RevealBi/Reveal.Sdk#294]
### SDK Version

1.7

### Client Framework

Other

### Server Platform

ASP.NET

### Operating System

Windows

### Description

When selecting the "All Time" in the date filter drop down after loading the visualizations with any other range of data causes the visualizations to break.

We are using a REST Datasource, when selecting "All Time" no call is made to the backend, instead the visualizations load for a moment, freeze, then display as shown in the screenshot below.

![image](https://github.com/user-attachments/assets/78950daf-5854-42cc-bb5e-5190ee34c8c1)

**Comment by brianlagunas** [comment]
This was already fixed and will be available in our next release targeted for the first week of Nov.

**Comment by brianlagunas** [comment]
Actually, I'm reopening to make sure we are talking about the same problem.

Are you reporting the "There is no data to display" issue", or is the primary issue that the data is not correct when filtering?

**Comment by rivadblins** [comment]
There were no errors in the console, I also noticed that this wasn't consistent. I was happening to me consistently yesterday, today when I re-launched, now it is the "today" value that is causing this issue.

There should be valid data in this date range. The issue I am reporting is that "Total Items Synced" is totally broken in its rendering, as well as "Total Items Synced by Module", and that it is rendering "There's no data to display" when there is definitely date to be displayed

**Comment by MLopezIG** [comment]
As Brian mentioned, the broken rendering has been fixed and will be available in the next release.

Regarding the 'All Time' option for a dashboard date filter, my guess is that you expect that the URL placeholders '$dateFilterFrom' and '$dateFilterTo' will be replaced with something like the empty string (e.g. 'https://yourdomain/yourpath?from=&to=&etc')

Can you confirm that you're setting '$dateFilterFrom' and '$dateFilterTo' parameters accordingly in your IRVDataSourceProvider implementation?

**Comment by rivadblins** [comment]
I can confirm we are populating it and most of the time at least one of the two parameters is populated while the other isn't. This morning I did observe neither being populated.

![image](https://github.com/user-attachments/assets/47e36ee1-8156-43a2-9a70-d7d605f5ba61)

**Comment by rivadblins** [comment]
I also opened this ticket for the issue of the dateFilterFrom/To not being populated https://github.com/RevealBi/Reveal.Sdk/issues/293

**Comment by MLopezIG** [comment]
I'll start by clarifying my previous comment. When I asked whether you were setting from/to  '$dateFilterFrom' and '$dateFilterTo' parameters, I'm referring to the `RVRestDataSourceItem.Parameters` property. 

The code that you've shared above shows how you're setting the `Url` property in the `ChangeDataSourceAsync` method. the parameters need to be set in the `ChangeDataSourceItemAsync`.

**Comment by brianlagunas** [comment]
@rivadblins have you tried our suggestion, and did it resolve your problem?

**Comment by brianlagunas** [comment]
I'm closing this as there has been no response. If you are still experiencing this issue, please let us know.
