### ISSUE TITLE
[BUG]: Large numbers in Donut Chart are overflowing rather than shrinking

### ISSUE THREAD

**Issue by rivadblins** [RevealBi/Reveal.Sdk#299]
### SDK Version

1.7

### Client Framework

Other

### Server Platform

ASP.NET

### Operating System

Windows

### Description

When a large value is present in the donut chart, it is moving the last digit to a new line rather than shrinking the text.

![image](https://github.com/user-attachments/assets/61facc37-23aa-4cbe-a008-b8258e90144e)

Internally tracked as [AB#34589](https://infragistics.visualstudio.com/14a7928c-44bc-4aed-b2ca-9a0ffbb14d7a/_workitems/edit/34589)

**Comment by luispandolfi** [comment]
Hi @rivadblins, we confirmed is a bug. We will notify when fixed.
Thank you.

**Comment by brianlagunas** [comment]
This has been fixed and will be available in our next release planned for the first week of Nov.
