### ISSUE TITLE
New data source fields not recognized in existing visualizations

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#30]
**Is your feature request related to a problem? Please describe.**

I added 2 new fields to a data source, and I can use them ok in new visualizations:

![image](https://user-images.githubusercontent.com/3975401/235150353-698fad64-edca-4b9f-8135-a0c17be3a400.png)

But, if I open one of the existing visualizations for that data source, the new fields don't appear there, even if I click the REfresh button next to my data source. Notice the 2 fields are not in here:

![image](https://user-images.githubusercontent.com/3975401/235150403-eb94ea69-5640-4d58-93bc-81d00e07d40b.png)

This data source is configured to "Refresh Data = Always" in case it matters:
![image](https://user-images.githubusercontent.com/3975401/235151189-4c4f20e6-8bf8-4955-9b78-0858cd89f9a5.png)

And this is how I'm configuring the fields of that data source:

```java
    private toDataSourceItem(dataSource: DataSource): RevealApi.RVJsonDataSourceItem {
        const rvDataSource: RevealApi.RVRESTDataSource = new $.ig.RVRESTDataSource();
        rvDataSource.id = dataSource.revealId;
        rvDataSource.url = dataSource.url;
        rvDataSource.title = dataSource.subtitle;
        rvDataSource.contentType = "application/json";
        rvDataSource.method = "GET";

        const dsItem = new $.ig.RVRESTDataSourceItem(rvDataSource);
        dsItem.id = dataSource.revealId + "-item";
        dsItem.title = dataSource.title;

        const jsonDsItem = new $.ig.RVJsonDataSourceItem(dsItem);
        jsonDsItem.config = this.getDataSourceFormat();
        jsonDsItem.defaultRefreshRate = 0;
        jsonDsItem.title = dataSource.title;
        return jsonDsItem;
    }
    
    private getDataSourceFormat(): string {
        return new RevealApi.RVJsonSchemaConfigBuilder()
            .addStringField("Framework Name")
            .addStringField("Framework Section")
            .addNumericField("Framework Section Order") // the new field
            .addStringField("Framework Subsection")
            .addNumericField("Framework Subsection Order") // the other new field
            .addStringField("Control")
            .addStringField("Answer")
            .addNumericField("Yes")
            .addNumericField("No")
            .addNumericField("Not Applicable")
            .addNumericField("Partial")
            .addNumericField("Unanswered")
            .addNumericField("Has Evidence")
            .setIterationDepth(0)
            .build();
    }
```

**Describe the solution you'd like**
I would like the new fields to be recognized when I hit the Refresh button, so that my customers don't need to rebuild all their visualizations for this data source each time we add a new field.

**Describe alternatives you've considered**
Telling the customers to rebuild the visualizations, which they are not happy with.

**Comment by MLopezIG** [comment]
In the future, it should be possible to set the json configuration server side (in the `IRVDataSourceProvider`) and that will make this problem dissappear. At the moment we don't have the java version of the `RVJsonSchemaConfigBuilder`.
