### ISSUE TITLE
Ability to define the cache store in a Java server application

### ISSUE THREAD

**Issue by robinsmith4142** [RevealBi/Reveal.Sdk#301]
**Is your feature request related to a problem? Please describe.**
Need to be able to define where the cache is stored and control the cache parameters in a Java server application.

**Describe the solution you'd like**
Implement the same controls available in the other technologies as per documentation.

**Comment by gkaveckis** [comment]
Hi,  a new method 
_public InitializeParameterBuilder setCachePath(String path)_
was added to _InitializeParameterBuilder_ to allow customization of the cache files location.

Will be available in the next release

**Comment by robinsmith4142** [comment]
Fantastic.  Thanks
