### ISSUE TITLE
[BUG]: onVisualizationDataPointClicked not invoked for Doughnut charts

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#303]
### SDK Version

1.6.1

### Client Framework

Angular

### Server Platform

Java

### Operating System

Linux

### Description

We have a chart like this:

![image](https://github.com/user-attachments/assets/5bad17bf-969b-4fcb-84f4-15f95177e358)

And a click listener defined like this:

```js
        this.revealView.onVisualizationDataPointClicked = (rv) => {
            ....
        };
```

But clicking on the rings of the doughnut is not invoking the click listener. If I change the chart type to bars, then the click listener is invoked.

I checked the docs in the d.ts and there is no mention of this callback being restricted to a subset of the visualization types:

> This event is triggered whenever the end user clicks on a data point over a maximized visualization and not in edit mode.

**Comment by brianlagunas** [comment]
I verified this occurs on the new charts we have been moving to. We are tracking this with internal item [#34763](https://infragistics.visualstudio.com/BusinessTools/_sprints/backlog/Reveal%20Team/BusinessTools/Reveal/Nov%202024?workitem=34763)

Note: This does not occur on the old chart.

**Comment by nerzhei** [comment]
Hi @dwilches. This has been fixed and will be available as part of the next release.
