### ISSUE TITLE
Allow for resizing of text

### ISSUE THREAD

**Issue by OwilsonCC** [RevealBi/Reveal.Sdk#304]
**Is your feature request related to a problem? Please describe.**
We are trying to add dashboards to a large screen so that users can see information in real time. The issue we are having is that the large text size, is not quite large enough, we will only be having 2 - 3 visualizations on the screen at a time, so would be ideal if the font size could be larger to allow users to read from further away.

**Describe the solution you'd like**
We would like the ability to set a font size ourselves, or to have larger pre-set sizes for fonts.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by brianlagunas** [comment]
This is a duplicate request of #168. I would recommend subscribing to that issue, so you are notified when the feature has been implemented.
