### ISSUE TITLE
Y/X axis to not show decimal places when large number formatting is switched on. 

### ISSUE THREAD

**Issue by bradzedonk** [RevealBi/Reveal.Sdk#318]
<img width="756" alt="Screenshot 2024-11-20 at 14 46 08" src="https://github.com/user-attachments/assets/305d8c5f-91bd-403d-ad23-fcdc46d1cd29">

**Comment by TorreyBetts** [comment]
If you click on the value field it's possible to change "Fraction Digits" to the desired amount. This defaults to what you've used with past value fields. Which could be why you see two digits after the decimal.

<img width="503" alt="image" src="https://github.com/user-attachments/assets/ffd2ffe5-0a60-4c59-ae39-aebd38bc8ef2">

**Comment by brianlagunas** [comment]
I'm closing this as the Fraction Digits setting should achieve your desired formatting.

**Comment by bradzedonk** [comment]
When working with values you want the exact figure to be shown correctly when the user is either drilling down or exporting the data to excel thus the reason for decimal places. 

It is however not required when looking at an axis. Excel works this way. 
![Screenshot 2024-11-21 at 09 11 20](https://github.com/user-attachments/assets/325d643e-43ce-4a03-9faf-bec0fc1d7c74)
