### ISSUE TITLE
[BUG]: Not able to upload dashboard file with new datasource

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#32]
### Company

IMSPOS

### SDK Version

1.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Description

We have below usecase

- We have existing dashboard with datasource "ds1"
- We downloaded those dashboard and uploaded back again with new datasource "ds2"
- But still new dashboard is looking for old datasource "ds1"

We wanted to understand how to update datasource of existing dashboards. We have number of dashboards for which we want to update datasource to point to new IP address.

**Comment by brianlagunas** [comment]
> We downloaded those dashboard and uploaded back again with new datasource "ds2"

How are you changing the data sources?

**Comment by vishwa-ims** [comment]
Below is a codebase for dashboard upload. We are passing sourceid of new source

if (!Directory.Exists(newpath))
            {
                Directory.CreateDirectory(newpath);
            }
            fileName = DashboardName + "-" + companyId + "-" + randomId + ".rdash";
            pathMerg = Path.Combine(newpath, fileName);
            using (var stream = new FileStream(pathMerg, FileMode.Create))
            {
                files.CopyTo(stream);
            }

            /////////////Add new Dashboard///////////////

            Dashboards dashboards = new Dashboards();
            dashboards.CompanyId = Convert.ToInt32(companyId);
            dashboards.DataSourceId = Convert.ToInt32(sourceId);
            dashboards.DashboardId = randomId.ToString();
            dashboards.DashboardName = DashboardName + "-" + companyId + "-" + randomId;
            dashboards.DisplayDashboardName = DashboardName;
            dashboards.DashboardPath = pathMerg;
            dashboards.IsActive = true;
            await _dashboardService.CreateDashboard(dashboards);

        

            //////////////////////Make Entry on DashboardUser Table//////////////////////////
            DashboardUser dashboardUser = new DashboardUser();
            dashboardUser.DashboardId = Convert.ToInt32(dashboards.DashboardId);
            dashboardUser.UserId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            dashboardUser.PermissionType = Convert.ToInt32(Stadis.Intelligence.Data.Enum.Enum.PermissionType.Owner);
            dashboardUser.SourceType = Convert.ToInt32(Stadis.Intelligence.Data.Enum.Enum.SourceType.Dashboard);
            await _dashboardService.AddAssigneesToDashboard(dashboardUser);

            /////////////Add new Dashboard in Folder Table///////////////
            DashboardFolder dashboardFolder = new DashboardFolder();
            dashboardFolder.DashboardId = Convert.ToInt32(dashboards.DashboardId);
            dashboardFolder.FolderId = Convert.ToInt32(HttpContext.Session.GetString("FolderId"));
            await _dashboardService.SaveDashboardInFolder(dashboardFolder);

**Comment by brianlagunas** [comment]
Unfortunately, that code does not show the actual replacement of data sources in the dashboard or rdash file. That looks like custom code.

How are you replacing the data sources of the dashboard?
