### ISSUE TITLE
[BUG]: RevealView.onVisualizationDataLoading not being hit when loading a dashboard

### ISSUE THREAD

**Issue by FergusViriumDev** [RevealBi/Reveal.Sdk#334]
### SDK Version

1.7.1

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

This may well be me mis understanding the API, but I've found that the `onVisualizationDataLoading` JavaScript event is not being hit when loading a dashboard from JSON and displaying the visualisations. It is successfully hit when adding a new visualisation to the dashboard however, and is providing the correct args, so I know it at least functions that way. 

I've tried it both in the `revealView.dashboard.onVisualizationDataLoading` and `revealView.onVisualizationDataLoading` formats, and have been unsuccessful getting either of them to hit.  

I can also confirm that the dashboard is loading correctly, and is not displaying any other errors.

**Comment by PVillarmarzo** [comment]
I believe the issue might stem from incorrect method placement. Please try this method: it is a functioning HTML example; unzip the zip file and run it.

[index.zip](https://github.com/user-attachments/files/18168280/index.zip)

**Comment by brianlagunas** [comment]
To put it more simply, you have to set the callback prior to setting the dashboard property

![image](https://github.com/user-attachments/assets/6424ecc3-e7da-472b-9df5-e38a337a2221)

**Comment by brianlagunas** [comment]
Closing at this works in the attached sample. If you are still having issues let us know.

**Comment by FergusViriumDev** [comment]
Thank you very much for the information. The sample you provided does fix the error, and now hits the event as expected. Sorry - perhaps I should have opened this on the Discussion Board first, before diving into the Issues.
