### ISSUE TITLE
[BUG]: not all custom colours are kept in JavaScript exports

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#35]
### Company

N/A

### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

We have a dashboard that looks like this:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/edc24c14-a974-4620-9041-d5cae1ae099c)

Notice the colours in the first image.

When I try to export to PDF, the preview looks like this, notice the first chart's colours are now blue:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/4151dea9-ed5f-409a-ba4e-95daea7fe6de)

And in the PDF, the coloursa are also blue:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/8241c3bb-7248-48c8-87c5-769a13c39282)

The blues come from the custom palette I'm setting with `RevealTheme.chartColors`, and the other colours (red, green, yellow, etc.) are colours I'm customizing according to the "categoryName" by using this method:

```javascript
            this.revealView.onVisualizationSeriesColorAssigning = (visualization, defaultColor, fieldName, categoryName) => {
                if (!categoryName) {
                    return defaultColor;
                }
                if (categoryName === "<null>") {
                    return "#bdbdbd"; 
                }

                const dataSourceId = visualization.referencedResourceDataSourceId;
                const customColor = this.getCustomColor(dataSourceId, categoryName);
                return customColor || defaultColor;
            };
```

So it seems the PDF export is respecting colours set by `RevealTheme.chartColors` but not colours set by `RevealView.onVisualizationSeriesColorAssigning`?

**Comment by brianlagunas** [comment]
This is not a bug, but by design. The PDF export does not know about changes you have made at runtime using the `onVisualizationSeriesColorAssigning` event.  Also, you just submitted a feature request about this same topic. Please do not double post.

**Comment by dwilches** [comment]
#34 is not the same topic, that is for server side requests, where not even `RevealTheme.chartColors` is being used (as it lives in JavaScript and the server-side code doesn't know about what I do on the UI side.

**Comment by brianlagunas** [comment]
The PDF export uses the same approach regardless of it runs on the client or server.

**Comment by brianlagunas** [comment]
I've updated your feature request (#34) to include improvements to both the client and the server.
