### ISSUE TITLE
[BUG]: Error message Exceeded limit of rows

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#36]
### Company

IMSPOS

### SDK Version

1.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Description

Hi 
We are getting error message as below
![MicrosoftTeams-image (14)](https://github.com/RevealBi/Reveal.Sdk/assets/89643622/d997d30f-2ea1-4d61-b1c6-ba6133560526)

**Comment by gkaveckis** [comment]
Hi, please verify the following link: https://help.revealbi.io/api/aspnet/latest/Reveal.Sdk.RevealEmbedSettings.html

It will explains how MaxInMemoryCells and MaxStorageCells can be changed.

Regards.
