### ISSUE TITLE
[BUG]: Reveal swaps custom colours when "Others" is included

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#37]
### Company

N/A

### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

I have a dashboard where I overrode the method `onVisualizationSeriesColorAssigning` to assign custom colours depending on the `categoryName` of the data. Most of the times this was working, but from time to time the wrong colours were being selected.

Today I managed to track down the issue to when Reveal adds a "Others" category in the visualization. If "Others" is not included, the colours are as I expect, when "Others" is included, the colours are swapped (a category has the colour of another category).

Here is an image of what I'm seeing to explain better:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/ad81130c-121e-413d-81bc-782ef38f29cd)

This is my code for `onVisualizationSeriesColorAssigning`:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/f7526b49-624f-4b78-ac4e-e962888789fc)

This code prints the categoryName alongside the colour before returning it to Reveal, which is what you can see on the DevTools console in the first image.

So for example it says my code returned blue `#0040ff` for "Daniel Wilches", but in the graph you can see this user is shown in green, which is the colour my code returned for "Airflow Search User". Similarly, my function returned purple `#b700ff` for "David", but in the graph you see it's displayed in orange.

**Comment by brianlagunas** [comment]
I just wanted to give you an update on this issue. We are currently blocked by an internal work item that we are waiting on the be resolved. This has been scheduled for the last couple of sprints, but keeps getting bumped because of the internal issue. As soon as that internal issue is resolved, we will be able to move forward with this issue.

**Comment by brianlagunas** [comment]
This has been fixed and will be in our next reelase.
