### ISSUE TITLE
[BUG]: Visualization Date Filter 

### ISSUE THREAD

**Issue by sleinenger** [RevealBi/Reveal.Sdk#41]
### Company

International Micro Systems

### SDK Version

1.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Description

Hello,
We have created SQL server stored procedures for reporting purposes. These stored procedures ran correct in Reveal SDK version 1.1.4, but they are not running correctly in Reveal SDK version 1.4.
We found the issue to be with connecting the date filter. The store procedures have a @fromdata and @todata. We were able to edit the visualization date filter to apply the start and end date parameter. This seems to be missing or changed in version 1.4. Does the date filter start and end date parameters still exist in 1.4?
Is this process/setup different in 1.4?
Or is this option completely missing from 1.4?

Thanks

![image](https://github.com/RevealBi/Reveal.Sdk/assets/134005865/12c582ea-c78f-469a-84f6-0a9a2f4cc1e7)

**Comment by PVillarmarzo** [comment]
Hi, it is possible to edit the date filter to apply the start and end date parameters as you can see in the attached images.
Let us know if that's what you were looking for.


![Screenshot 2023-05-22 090827](https://github.com/RevealBi/Reveal.Sdk/assets/108025451/ba7ae5c8-daa6-4e64-b165-87efff3bc7f1)
![image](https://github.com/RevealBi/Reveal.Sdk/assets/108025451/1794e7f7-fa1d-4ff1-accf-d49c0031a565)

**Comment by PVillarmarzo** [comment]
Maybe I am not understanding the error correctly, I am attaching a GIF with what I understand is being raised. In case it is not, I appreciate more detail
The example was made in version 1.4 of the SDK

![BUG#41](https://github.com/RevealBi/Reveal.Sdk/assets/108025451/62ca21de-2f1f-473c-8ec0-4255a9cd5c12)

**Comment by brianlagunas** [comment]
@sleinenger can you create a small app that reproduces the issue and send it to us?

**Comment by sleinenger** [comment]
@brianlagunas I seen today that version 1.5 was release two weeks ago. Our plan was to install version 1.5 and retest.

**Comment by sleinenger** [comment]
@brianlagunas We are noticing the same behavior on version 1.5 regarding the date filtering for start and end date parameters.

**Comment by brianlagunas** [comment]
@sleinenger we are unable to reproduce this behavior. Can you please create a new sample that can reproduce this behavior?

**Comment by sleinenger** [comment]
@brianlagunas We are looking at our current deployment to make sure were not missing anything. Does Reveal have an existing sample for .net for date filters?

**Comment by brianlagunas** [comment]
We don't have any samples that connect to a database since that would require sharing credentials. This is a stored proc that we are testing with that works for us

![image](https://github.com/RevealBi/Reveal.Sdk/assets/835562/2728927d-f375-4320-95e9-941d40a53c42)

Can you identify anything in your stored proc that may be different. Maybe the casing, or the data type being used?

**Comment by brianlagunas** [comment]
One thing to check, can you check to see if you can scroll down to see the other filter option? We think we have identified the issue being that the second time you open the dialog, the parameter is added at the bottom of the dialog which requires scrolling. Check out this GIF

![newBUG](https://github.com/RevealBi/Reveal.Sdk/assets/835562/da40224b-ef4c-4ef8-8c08-636ff5c4d644)

**Comment by vishwa-ims** [comment]
@brianlagunas  we tried converting FromDate and ToDate parameters to DateTime but still it is giving same result . 

Below is our stored procedure 
<img width="545" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/89643622/85783bb4-3455-4ea0-9966-2089c4b24fb2">


https://github.com/RevealBi/Reveal.Sdk/assets/89643622/c12fd9a5-5e37-42b1-b710-1a9185058a6b

Do we need any specific changes in code while configuring the SDK or it should work fine without any additional changes for V1.5 SDK version ?

**Comment by vishwa-ims** [comment]
@PVillarmarzo  we are still getting same issue even after removing BEGIN , END command. Below is updated stored procedure

USE [DB1]
GO

/****** Object:  StoredProcedure [dbo].[Test_USP]    Script Date: 5/26/2023 10:56:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[Test_USP3]
    @FromDate DATE,
    @ToDate DATE
AS


Select * from INVOICE as i where i.CREATED_DATE >= @FromDate and  i.CREATED_DATE <= @ToDate

**Comment by PVillarmarzo** [comment]
I just tried a stored procedure based on the previous and it works correctly for me

![image](https://github.com/RevealBi/Reveal.Sdk/assets/108025451/dc73a6ec-cd85-42a9-9245-4538f8ba0f31)

![image](https://github.com/RevealBi/Reveal.Sdk/assets/108025451/1343a825-d958-4abf-ba33-10fd32fd97bc)

**Comment by vishwa-ims** [comment]
@PVillarmarzo  are you checking this on Reveal ASP.NET core SDK 1.5.0? Because we are not able to get it working in this SDk version

**Comment by brianlagunas** [comment]
@vishwa-ims try refreshing the data source to make sure you're not hitting a cache 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/835562/ab03775d-8433-467d-be48-64da0994a1cf)

**Comment by vishwa-ims** [comment]
@brianlagunas  yes I tried refreshing as well .Also I tried to create new stored procedure every time just to make sure I am not using it from cache

**Comment by brianlagunas** [comment]
Are you getting any errors in the console in the browser dev tools?

**Comment by vishwa-ims** [comment]
Do not see any errors in console while designing dashboard

**Comment by brianlagunas** [comment]
Please try using one of the samples in this repo to connect to your data source and see if you still have the issue.

https://github.com/RevealBi/sdk-samples-javascript

**Comment by brianlagunas** [comment]
The .NET version does not matter. Our SDK targets .NET Core 3.1. It works in all versions of .NET Core including 5.  Does it work as expected in the samples I sent you? Have you been able to reproduce this in a new sample app?

On a side note, I would recommend moving off .NET 5. It is no longer supported by Microsoft.

**Comment by vishwa-ims** [comment]
Hi @brianlagunas  we were not able to get it working . We have created one sample project so that you can have a look at it .

https://github.com/ims-pos/reveal-sample-code.git

We have configured one cloud based datasource so that this code should directly work in your machine without any additional changes . Also we have created screen recording of the issue with the same code

https://myimspos-my.sharepoint.com/:v:/g/personal/vawate_ims-pos_com/EcotWLF4pZVPqd3IRwwGKW4B9smF-3xyKEpTkNg3pl1e_Q?e=gLujAR

**Comment by brianlagunas** [comment]
I see the problem. When you upgraded the server to v1.5, you did not update the client side `infragistics.reveal.js` file.

Make sure you update the `infragistics.reveal.js` to v1.5 too.

You can do a quick test using the CDN
```js
<script src="https://dl.revealbi.io/reveal/libs/1.5.0/infragistics.reveal.js"></script>
```

After updating the client-side SDK it works

![image](https://github.com/RevealBi/Reveal.Sdk/assets/835562/7a415082-7ab9-4482-b15e-698324d9c6c8)

Please verify and let me know.

**Comment by vishwa-ims** [comment]
@brianlagunas  Thanks a lot . It is working fine now. May be we overlooked installation step for client side library
