### ISSUE TITLE
[BUG]: setting revealView.canChangeVisualizationBackgroundColor occurs an error.

### ISSUE THREAD

**Issue by cleverdog** [RevealBi/Reveal.Sdk#43]
### Company

Infragistics

### SDK Version

https://dl.revealbi.io/reveal/libs/1.5.0/infragistics.reveal.js

### Client Framework

HTML/JavaScript

### Server Platform

Node.js

### Description

When I set revealView.canChangeVisualizationBackgroundColor to true as below.
`revealView.canChangeVisualizationBackgroundColor = true;`

`infragistics.reveal.js:154 Uncaught TypeError: this.__spectrumElement.spectrum is not a function`
this error has occured.

Can be reproduced on [playground](https://help.revealbi.io/playground/).

**Comment by brianlagunas** [comment]
You need to install the Spectrum dependency as noted in the docs

https://help.revealbi.io/web/install-client-sdk#add-dependencies

**Comment by cleverdog** [comment]
Sorry for missing the docs, thank you!
