### ISSUE TITLE
[BUG]: Missing legend from doughnut charts for null values

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#44]
### Company

N/A

### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

I have a chart where some of the fields ("resolution") can be null some times (notice the 3rd row):
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/4f637cb3-b5fc-4b18-8d11-19b04353cc42)

When using a bar chart, the null "resolutions" are shown in the legend as `<null`>:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/c51174c3-36af-40b7-95b3-6a6746681e04)

But with a doughnut chart, the `<null>` is not being shown in the legend, even though there is a doughnut section for them:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/1a7feb59-567d-46a6-82ca-649859162ffc)

This causes issues with customers not understanding what the blue section is as there is no legend for it.

**Comment by PVillarmarzo** [comment]
This has been fixed and will be available in a future release
