### ISSUE TITLE
Multiplying by decimals smaller than 1 without leading 0

### ISSUE THREAD

**Issue by gauxgaux** [RevealBi/Reveal.Sdk#47]
**Is your feature request related to a problem? Please describe.**
I expect when I multiply by a decimal without a leading 0 that Reveal understands it's a decimal. Instead it misses the decimal and multiplies by everything as though it's a whole number. 

**Describe the solution you'd like**
I want to be able to multiply [number]*.5 and have it calculate the same as [number]*0.5.

**Describe alternatives you've considered**
Right now I advise customers to include the leading zero for accurate calculations.

**Additional context**
none.

**Comment by brianlagunas** [comment]
This is related to issue #46 which was reported as a bug, but closed and then requested to be resubmitted as a feature request.

@Christianig in the future, just change the tags on the issue instead of asking for a new issue that is reporting the same thing.

**Comment by brianlagunas** [comment]
This issue has been resolved and will be available in our next release at the end of Aug.
