### ISSUE TITLE
Add support for data blending using Athena

### ISSUE THREAD

**Issue by Ian247** [RevealBi/Reveal.Sdk#49]
**Is your feature request related to a problem? Please describe.**
We have a number of models that require joining. Our preference would be to use the data blending feature in the front-end rather than build specific models or custom queries for every problem we have. Currently the RVAthenaDataSource does not support this feature.

**Describe the solution you'd like**
If the support for data blending could be added, that would be helpful. 

**Describe alternatives you've considered**
We could use a different database, but this goes against our existing strategy.

**Comment by gkaveckis** [comment]
Hi thank your for submitting the feature request. 
We created an internal item to track it AB#24807
We will keep you updated for any update.
Regards.
