### ISSUE TITLE
[BUG]: After creating a new view and setting the preview format, the data fields are displaying abnormally.

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#50]
### Company

NA

### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Java

### Description

1.After entering the interface, create a new VISUALIZATION.
2.Select the corresponding data table and click the preview data button.
3.After setting the preview format with the table preview function on the right, create a new one.
After clicking to enter, you'll find that the corresponding field has turned into the value data of the ID, rather than the field information of the table.

Please refer to the video section for the operating steps.
![TESTBUG](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/27993902-81b7-4a07-98dd-91acc54f8861)

**Comment by luispandolfi** [comment]
Hi @suzakuzt, from your video I noticed you did a transpose of the data in the preview screen, so that is a expected behaviour. The transpose switches the rows with the columns.
Please try not clicking the transpose button.

**Comment by suzakuzt** [comment]
HI,   @luispandolfi  ,My understanding is that the user performed a switch preview format operation in a preview feature newly created within a view. This operation does not cause the entire field's information to change. The field information should remain as id, value, price, and other field names when entering the subsequent data editing interface, rather than including the actual values of the id field. Please confirm if my understanding is correct.

Even after following the current operation, an error still occurs. I believe there might be a problem with the handling of transposition in this section.The specific error message is as follows:

![TESTBUG](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/8e19b0fc-4b3b-4242-a847-27c254805802)






>

**Comment by luispandolfi** [comment]
Hi @suzakuzt, maybe the feature is kind of confusing. In the preview screen, when you transpose the data (rows are columns, columns are rows) and then accept that by clicking the "tick" button, Reveal will take the transposed data. If you click the transpose button and want to discard the transpose, you have to close the preview screen with the "cross" button.
Notice that the icon of the table changed, it has a double arrow in the upper-left corner, that indicates it is the transposed data:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/419583/a3714ea0-ce08-4f74-87bd-aea3665ca97b)

Regarding the ArithmeticException, yes that is an error, will try to replicate it.

**Comment by brianlagunas** [comment]
@suzakuzt We are going to close this issue as "by-design". If you believe we have misunderstood the issue, or you can provide more clarification we can reopen the issue.

@luispandolfi were you able to replicate the ArithmeticException? If so, please create a new issue and tag @suzakuzt in it.
