### ISSUE TITLE
Ability to Copy and Paste Between dashboards

### ISSUE THREAD

**Issue by gauxgaux** [RevealBi/Reveal.Sdk#51]
**Is your feature request related to a problem? Please describe.**
Currently in order to copy and paste between dashboards there is some unknown criteria to make it work. You have to have the same windows open or stay within the same browser. It's inconsistent at best. 

**Describe the solution you'd like**
I would like to see a consistent ability to copy and paste between dashboards. 

**Describe alternatives you've considered**
Right now we have clear step by step instruction on how to make sure you're in the same browser. 

**Additional context**
[A video of someone on our team copying and pasting.](https://share.vidyard.com/watch/DknK54n6cJFek8ayqFq97Z)

**Comment by brianlagunas** [comment]
This has been added to our next sprint for implementation AB#25239.

**Comment by brianlagunas** [comment]
This has been completed and will be in our next release at the end of this month.
