### ISSUE TITLE
[BUG]: Request headers do not work for RVDataSource() when using the NodeSDK 

### ISSUE THREAD

**Issue by exscalliber** [RevealBi/Reveal.Sdk#52]
### Company

N/A

### SDK Version

Client-1.5.0 / Server-0.8.1

### Client Framework

React

### Server Platform

Node.js

### Description

RVRESTDataSource() does not process REST requests if there are headers included in the data source credentials. This is only a problem with the Node SDK.

Example: 

```
  revealView.onDataSourcesRequested = (callback) => {
    const apiKey = "PMAK..."; // change this api key
    const restDataSource = new $.ig.RVRESTDataSource();

    restDataSource.url = "https://api.getpostman.com/me"; // example endpoint that requires a header.
    restDataSource.title = "Test API with header(s)";
    restDataSource.useAnonymousAuthentication = true;
    restDataSource.headers = [ 
        `X-Api-Key=${apiKey}`,
    ];
    
    callback(new $.ig.RevealDataSources([restDataSource], [], true));
  }
```

 It seems as though the server fails before it tries to hit the REST endpoint. The error i get back on the client side is: "Problems with Verify Credentials using the specified data source. User Id: (user id...)". 

Providing the same headers using the sample URL (https://samples.revealbi.io/upmedia-backend/reveal-api/) works fine. I assume the sample is ASP.NET

**Comment by brianlagunas** [comment]
This has been logged with AB#25463

**Comment by PVillarmarzo** [comment]
This has been fixed and will be available in a future release
