### ISSUE TITLE
[BUG]: Pushing multiple menu items with menuItem action functions calls the last action function.

### ISSUE THREAD

**Issue by exscalliber** [RevealBi/Reveal.Sdk#53]
### Company

N/A

### SDK Version

1.5.0

### Client Framework

HTML/JavaScript

### Server Platform

Node.js

### Description

[revealView.onMenuOpening()](https://help.revealbi.io/api/javascript/latest/classes/revealview.html#onmenuopening) Calls the wrong RVMenuItem.action function when adding multiple menu items. 

Example code: 

```
revealView.onMenuOpening = (visualization, args) => {
  args.menuItems.push(new $.ig.RVMenuItem("Custom Menu Item 1", null, () => { 
    alert('this is the first menu item'); // this entire callback is lost to the abyss :(
  }));

  args.menuItems.push(new $.ig.RVMenuItem("Custom Menu Item 2", null, () => {
    alert('this is the second menu item'); // this entire callback is also lost to the abyss :(
  }));

  args.menuItems.push(new $.ig.RVMenuItem("Custom Menu Item 3", null, () => {
    alert('this is the third menu item'); // only this alert will be called
  }));
}
```

If you were to click on the first menu item, it will alert with the last menu items function. 

GIF recording: 
![output](https://github.com/RevealBi/Reveal.Sdk/assets/75103473/93e28fe5-6fdd-46d6-988c-c65e668a8711)

**Comment by PVillarmarzo** [comment]
Internal work item AB#25344 created

**Comment by PVillarmarzo** [comment]
This has been fixed and will be available in a future release
