### ISSUE TITLE
[BUG]: Color for "No Data" of Choropleth map is wrong for Non-English Language

### ISSUE THREAD

**Issue by cleverdog** [RevealBi/Reveal.Sdk#55]
### Company

Infragistics

### SDK Version

1.5.0

### Client Framework

HTML/JavaScript

### Server Platform

Node.js

### Description

I created a choropleth map like this.
![image](https://github.com/RevealBi/Reveal.Sdk/assets/5829221/bb78b29b-f4ef-4bd9-896d-c36f6b0822af)
This looks good with EN language browser setting, but when I changed language to JA...
![image](https://github.com/RevealBi/Reveal.Sdk/assets/5829221/96d02c1b-36b9-4492-8d00-0c4367006433)
The areas of "No Data" filled by green color, I cheked with KO and this is also green.
![1b1f7a95-6121-4b23-b519-9718780847e3](https://github.com/RevealBi/Reveal.Sdk/assets/5829221/b255b79d-34f7-46a9-9937-a42589fcdf07)

**Comment by PVillarmarzo** [comment]
Internal work item AB#25695 created

**Comment by TorreyBetts** [comment]
This issue has been fixed and will be released in an upcoming release.
