### ISSUE TITLE
[BUG]: Reveal BI map data displays anomalies

### ISSUE THREAD

**Issue by suzakuzt** [RevealBi/Reveal.Sdk#57]
### Company

NA

### SDK Version

1.5.0

### Client Framework

Other

### Server Platform

Java

### Description

Here are the steps
1.Enter the REVEAL BI report.
2.After viewing the map data, click on the VIEW DATA button.
3.Check the list data. The COST_PERC field in the list data has values, but in the map interface, it is not displayed and shows a value of 0.

"The settings for the 'cost_perc' field are as shown in the following image."
![image](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/c64375ea-8c1c-4535-8d9e-fac8d8dee4b3)

![BUG-reveal](https://github.com/RevealBi/Reveal.Sdk/assets/37360991/7092b09d-e068-46c4-8563-aa15a57e6fd0)

**Comment by PVillarmarzo** [comment]
Internal work item AB#25742 created

**Comment by PVillarmarzo** [comment]
This issue has been fixed and will be released in an upcoming release.
