### ISSUE TITLE
[BUG]: Null is unable to be filtered on

### ISSUE THREAD

**Issue by exscalliber** [RevealBi/Reveal.Sdk#63]
### Company

N/A

### SDK Version

Client 1.5.0

### Client Framework

HTML/JavaScript

### Server Platform

Node.js

### Description

Hi guys, 

I have found an issue with filtering null values on a datasource (with the help of Pablo Villarmarzo on discord). Attached is an example dataset that will need to be imported into a database. The "category" column will need to have NULL cells rather than empty strings to replicate the bug.

[exampleDataset2.csv](https://github.com/RevealBi/Reveal.Sdk/files/12210154/exampleDataset2.csv)

This is how i have structured the data in a visualization (you will see there is no "null" option in the filter): 

<img width="1300" alt="Screenshot 2023-07-28 at 8 53 01 AM" src="https://github.com/RevealBi/Reveal.Sdk/assets/75103473/3ec6d1ce-6306-4b3f-bb6e-eb6c535eb43e">

<img width="1080" alt="Screenshot 2023-07-31 at 9 28 35 AM" src="https://github.com/RevealBi/Reveal.Sdk/assets/75103473/189ba3bd-c190-4adb-b81c-86ed3d80eb41">

**Label**: Time(hour)
**Value(s)**: exampleWeight (kg)
**category**: category
**Visualization Filter**: category

The image shows that "\<null\>" is a category but is unable to be filtered on. Empty strings behave as expected and have an option within the filter.

Thanks!

**Comment by PVillarmarzo** [comment]
Internal work item AB#25806 created

**Comment by brianlagunas** [comment]
This has been fixed and is available in our current 1.6.1 release.
