### ISSUE TITLE
Add noopener attribute when opening a new windows from a dashboard link

### ISSUE THREAD

**Issue by gkaveckis** [RevealBi/Reveal.Sdk#64]
**Is your feature request related to a problem? Please describe.**
I have a link set up on one of my dashboards that opens a url. I'm finding that sometimes when I click the link and new tab opens, the page with the dashboard freezes. 

**Describe the solution you'd like**
When new window is open include the attribute noopener

**Describe alternatives you've considered**
We've encountered this in the past when opening new tabs and mitigated by always using rel="noopener" (or window.open(url, '_blank', 'noopener'))

**Additional context**

**Comment by gkaveckis** [comment]
Hi... tracked internally as AB#25994

**Comment by TorreyBetts** [comment]
This issue has been fixed and will be released in an upcoming release
