### ISSUE TITLE
[BUG]: Get null IRVUserContext in IRVDataSourceProvider.changeDataSourceItem in createwidget API

### ISSUE THREAD

**Issue by colinzhy** [RevealBi/Reveal.Sdk#65]
### Company

Lanxing

### SDK Version

1.5.0

### Client Framework

Other

### Server Platform

Java

### Description

As the sample code in the document,  while implementing the `IRVDataSourceProvider.changeDataSourceItem`, we need invoke `changeDataSource` method also. But I found the method parameter userContext is null in `changeDataSourceItem`. This is found in API `dashboard/editor/datasource/createwidget`, And it is null only in creating widget scenario

- Screenshot of document:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3828712/cf10de3a-70c8-4225-bf0b-a421e2dd3a1b)
- Screenshot of debug screen:
  - Get UserContext in other API
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3828712/f451d564-eb18-422b-b01b-ba4331ccff48)
  - Get null UserContext
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3828712/a98445bb-1e8b-4dc2-b2fc-d270a2bf7818)
- Sample code for reproducing the bug
[PostgreSQLServer.zip](https://github.com/RevealBi/Reveal.Sdk/files/12303733/PostgreSQLServer.zip)

**Comment by luispandolfi** [comment]
Internal work item #AB26053 created.

**Comment by brianlagunas** [comment]
This has been fixed and will be available in our next release targeted for the end of this month.
