### ISSUE TITLE
Customize option for tooltips

### ISSUE THREAD

**Issue by cleverdog** [RevealBi/Reveal.Sdk#67]
![customToolTip](https://github.com/RevealBi/Reveal.Sdk/assets/5829221/ea7d6826-b47a-45ae-9da7-518f17e3ab31)

Besides filtering and drill-down, there is a demand for unique operations on selected Visualizations.
It would be nice to be able to add a custom menu in the tooltip like in the image.

Thanks

**Comment by brianlagunas** [comment]
This has been implemented and will be available in our next release scheduled for the first week of Nov.

Here is a simple example of the API
```js
        revealView.onTooltipShowing = function (args) {
            var increaseIcon = "https://svgsilh.com/svg/152614.svg";
            var decreaseIcon = "https://svgsilh.com/svg/97616.svg";
            
            if (args.visualization.title !== "Actual Spend vs Budget") {
                return;
            }

            args.customItems.push(new $.ig.RVTooltipItem("Budget", "Increase Annual Budget", increaseIcon, (sender, clickArgs) => { console.log(clickArgs) }));
            args.customItems.push(new $.ig.RVTooltipItem("Budget", "Decrease Annual Budget", decreaseIcon, (sender, clickArgs) => { console.log(clickArgs) }));
        }
```
