### ISSUE TITLE
Add an onTooltipHiding event

### ISSUE THREAD

**Issue by cleverdog** [RevealBi/Reveal.Sdk#68]
**Is your feature request related to a problem? Please describe.**
The onTooltipHiding event is used to retrieve data for the selected Visualization. However, it always keeps the data from the last onTooltipHiding event, so it may call unnecessary data.

**Describe the solution you'd like**
If I can handle onTooltipHiding event, retained data can be erased when the tooltip is hidden.

**Describe alternatives you've considered**
It may be better to have a method to access the selected Visualization.

**Comment by TorreyBetts** [comment]
@cleverdog Could you add more detail? What is written appears unclear and I'm trying to understand the idea as well as the use case.

**Comment by cleverdog** [comment]
@TorreyBetts What I want to do is to perform some action from the selected Visualization, such as copying the value of the selected visualization to the clipboard. For now, the left click is occupied for displaying tooltips, so I am trying to use the right click to display the custom context menu and place specific actions there as a menu.
Specifically, the code is as follows:

```
//load dashboard from server
var dashboard = await $.ig.RVDashboard.loadDashboard("Sales");

//create reveal view
let revealView = new $.ig.RevealView("#revealView");

let toolTipData = [];

//assign dashboard
revealView.dashboard = dashboard;

revealView.onTooltipShowing = (args) => {
    toolTipData = args.row;
};

$("html").on("contextmenu", function (e) {
    if (e.which == 3 && e.target.tagName == "CANVAS") {
      for (let i = 0; i < toolTipData.length; i++) {
        console.log(toolTipData[i]);
      }
      return false;
    }
});
```
The above code works as expected when hovering over the targeted Visualization, but it also looks at the last held toolTipData when not hovering over a specific Visualization.

This is the reason why I want to empty toolTipData in the onTooltipHiding event, but it would be preferable if [this feature](https://github.com/RevealBi/Reveal.Sdk/issues/67) is implemented.

**Comment by brianlagunas** [comment]
I also just had a thought. You could try using a `MutationObserver` to monitor for any div's being removed, such as the tooltip, and then clear out the value. Maybe something like:
```
$(document).ready(function() {
    // Create a Mutation Observer instance
    const observer = new MutationObserver(function(mutationsList) {
    for (const mutation of mutationsList) {
        if (mutation.removedNodes.length > 0) {
            const removedNodesArray = Array.from(mutation.removedNodes);
            
            // Check if the removed nodes include the target div
            const targetChildDiv = removedNodesArray.find(node => node.id === 'CPPopupContainerView')
            if (targetChildDiv) {
                const tooltipDiv = $(targetChildDiv).find('#TooltipPopup');
                if (tooltipDiv.length > 0) {
                    //Target child div has been removed
                    toolTipData = [];
                }
            }
        }
    }
    });

    // Start observing changes on the revealView element
    observer.observe(document.getElementById('revealView'), { childList: true, subtree: true });
});
```

**Comment by cleverdog** [comment]
@brianlagunas thank you for your advice! MutationObserver works well👍
