### ISSUE TITLE
Create live dashboard 

### ISSUE THREAD

**Issue by elaiyaraja-marimuthu** [RevealBi/Reveal.Sdk#69]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brianlagunas** [comment]
There is no useful information in this feature request. Please provide as much detail as you can when requesting a feature or it will be closed. Preferred API ideas, images, videos, links to examples, or other assets that can help convey the desired result would be most useful.

Thanks

**Comment by elaiyaraja-marimuthu** [comment]
We need to sync the dashboard with live api data

**Comment by brianlagunas** [comment]
What is the source of your data? Are there more than one "live data source" that should be considered? If so, what are they? How do you envision the API looking like? How do you think the Reveal SDK Should hook into your live data API? Do you expect any specific events to be fire during data updates? How often does the data update? Are groupings or aggregations performed on the live data. If so, do those occur in your data source, or is that the responsibility of the Reveal SDK? Are only specific chart types supported? All chart types? Any performance concerns you have using other features like calculated fields on live data? What about data blending? is that supported in your live data scenario?
