### ISSUE TITLE
[BUG]: failed requests being cached?

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#70]
### Company

N/A

### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

Hello,

Today I found an odd issue with Reveal in which, after deploying to 2 of my machines (without any Reveal-releated changes), my dashboards started failing with an HTTP 403. 

Upon closer inspection, I saw they failed because Reveal was passing an invalid url to my data endpoints (HTTP/REST/JSON endpoints). Notice in this images the part that says `$orgId` and `$timeZoneId`, those are placeholders we use in our application and we replace them by actual values in the classes that implement  `IRVRestUrlResolver` and `IRVDataSourceProvider`.

After I stopped 1 of the machines, the error stopped happening. The other machine has worked well the whole time, and both were deployed the same code.

What kind of information you'd need and even how to start troubleshooting this? I shutdown my service in the server that had the issue, so I can gather useful information. I'm suspecting something with Reveal's cache was at fault because of a similar issue I saw years ago, but I'm not sure.

Is there a way I can look into Reveal's cache to see if there is a failed response that was cached?

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/fd82a5f3-8c18-4199-9aba-3c3f936bcb9f)

By the way, the "Forbidden" comes from my backend endpoint, when it sees `$orgId` instead of the value it expected.

Something else I noticed it that the `{$dateFilterFrom}` and `{$dateFilterTo}` placeholders were replaced ok by Reveal, those are the ones that say `localBegin` and `localEnd` in the image.

These are some relevant logs, they may not be for the same instance of the image so the dates may vary, but it's the same error that was happening over and over again (each time somebody refreshed their dashboards):

[reveal-p.log](https://github.com/RevealBi/Reveal.Sdk/files/12398495/reveal-p.log)

**Comment by TorreyBetts** [comment]
@dwilches One suggestion to help us figure out the issue is to add additional logging when the IRVRestUrlResolver and the IRVDataSourceProvider are supposed to run and replace the url placeholders. We'd like to verify these places are called by us and with the right parameters. It may also help to check your implementation to verify it is doing what is supposed to.

Also, on that machine with the issue, had you tried a refresh on the dashboard? Sometimes that can solve the issue if it was related to the cache.

**Comment by dwilches** [comment]
> add additional logging when the IRVRestUrlResolver and the IRVDataSourceProvider are supposed to run and replace the url placeholders

Actually I already have logging in place for `IRVDataSourceProvider`, I had not noticed in the failing machine there were no logs coming from my `RevealDataSourceProvider` class, but in the working machine there are. So, the `IRVDataSourceProvider` is not being invoked at all in the failing machine.

An example of how the logs look in my working machine:

```
2023-08-21 14:12:10,013 INFO  grizzly-http-server-11 c.c.m.RevealDataSourceProvider - RevealDataSourceProvider-changeDataSourceItem:
 dashboardId=null
 userContext=IRVUserContext: com.infragistics.reveal.sdk.base.RVUserContext
 dataSourceItem=RVDataSourceItem: com.infragistics.reveal.sdk.api.model.RVJsonDataSourceItem
 - id=12312312-594f-4425-6de0-1d561de337e0
 - title=REDACTED
 - dataSource=RVDashboardDataSource: com.infragistics.reveal.sdk.api.model.RVJsonDataSource
 - id=null
 - title=null
 - config={"columnsConfig":[{"type":1,"key":"Count"},{"type":0,"key":"State"},{"type":3,"dateFormat":"ISO8601_DATETIME","key":"Created On"},{"type":3,"dateFormat":"ISO8601_DATETIME","key":"Closed On"},{"type":3,"dateFormat":"ISO8601_DATETIME","key":"Due On"},{"type":0,"key":"Owner"},{"type":0,"key":"Severity"},{"type":0,"key":"Resolution"}],"iterationDepth":0}
 - resourceItem=
   IRVResourceItem: com.infragistics.reveal.sdk.api.model.RVRESTDataSourceItem
    - url=https://my-company.com/org/$orgId/reveal/incident-counts?localBegin={$dateFilterFrom}&localEnd={$dateFilterTo}&timeZoneId=$timeZoneId
    - parameters={}
    - datasource=RVDashboardDataSource: com.infragistics.reveal.sdk.api.model.RVRESTDataSource
 - id=incident-counts-v1
 - title=REDACTED
 - url=https://my-company.com/org/$orgId/reveal/incident-counts?localBegin={$dateFilterFrom}&localEnd={$dateFilterTo}&timeZoneId=$timeZoneId {jerseyId=local62647}
```


About the `IRVRestUrlResolver`. My class is not being invoked at all either. I just took a look and I noticed I made a mistake in the log file I attached, I redacted a bit too much and the lines that said:

    c.m.RestUrlResolver - Unexpected data source item received to resolve REST URL: null

Should actually say:

    i.r.RestUrlResolver - Unexpected data source item received to resolve REST URL: null

Because that error message is coming from one of your classes, not ours (I redacted it thinking it was our class which has a similar name)

> Also, on that machine with the issue, had you tried a refresh on the dashboard?

I don't think we have a way to do this: the machine with the issue is a backend machine, the issue happens when somebody in the UI loads a dashboard that ends up being directed to that machine by the load balancer. So if there is a button to "refresh dashboard" on the UI, and I press it, the load balancer could send it to any of our backend instances.

Thanks.

**Comment by dwilches** [comment]
In case it helps, I looked for the first instances of that `Unexpected data source item received to resolve REST URL: null` and found them close to when the server was restarted. Attached is the log file. The server restarted at `23:14:25,599` and the first customer request arrived at `23:39:20,120`, that is when the issue started manifesting.

I see a message saying `system may have quit unexpectedly`, but we get that one even in the machines that are working. It is caused because when we use `sudo service my-service stop`, Reveal takes too long to shutdown, so after a grace period Linux kills our process.
[reveal-q.log](https://github.com/RevealBi/Reveal.Sdk/files/12401862/reveal-q.log)

**Comment by MLopezIG** [comment]
Is your RevealDataSourceProvider class logging in both the changeDataSource and changeDataSourceItem, and is it doing it always (i.e. first statement in the method, not under any conditional)? 

Also, we understand that the code is exactly the same, but of course there must be some difference somewhere, otherwise the issue wouldn't exist. It can be something in the environment, something different in the request (though it is unlikely that your load balancer would be sending something different to this particular machine), and we have to leave the possibility of having code differences open. You also suggest that maybe the state of the machine (e.g. cache) may be the issue, but we cannot at this point link that error to a cache issue.
 
In case you're absolutely sure the DataSourceProvider is not being invoked at all by the Sdk, can you also double check that your RevealDataSourceProvider is being instantiated/registered at all?

**Comment by dwilches** [comment]
Hello,

The logging in the methods of `RevealDataSourceProvider` happens first thing. There are other logging code inside of conditionals. Here is the almost full code:

```java
public class RevealDataSourceProvider implements IRVDataSourceProvider {
    private static final UUID logId = getLoggingId();

    @Override
    public RVDashboardDataSource changeDataSource(final IRVUserContext context,
                                                  final RVDashboardDataSource source) {
        log.info("{}:\ncontext={}\nsource={}", logId,
                 RevealUtils.toString(context),
                 RevealUtils.toString(source));

        // REDACTED VALIDATION

        try {
            if (source instanceof RVRESTDataSource) {
                final RVRESTDataSource datasource = (RVRESTDataSource)source;
                // REDACTED VALIDATION
                datasource.setUrl(RevealUtils.replaceUrlPlaceholders(context, datasource.getUrl()));
            } else {
                log.warn("{}: Unknown data source class: {}", logId, source.getClass());
                throw new RuntimeException("Unknown data source class");
            }
            return source;
        } catch (Exception e) {
            log.error("{}: Unhandled exception", logId, e);
            throw e;
        }
    }

    @Override
    public RVDataSourceItem changeDataSourceItem(final IRVUserContext userContext,
                                                 final String dashboardId,
                                                 final RVDataSourceItem dataSourceItem) {
        log.info("{}:\ndashboardId={}\nuserContext={}\ndataSourceItem={}", logId, dashboardId,
                 RevealUtils.toString(userContext),
                 RevealUtils.toString(dataSourceItem));

        // REDACTED VALIDATION

        try {
            if (dataSourceItem instanceof RVRESTDataSourceItem) {
                final RVRESTDataSourceItem dsItem = (RVRESTDataSourceItem)dataSourceItem;
                // REDACTED VALIDATION
                dsItem.setUrl(RevealUtils.replaceUrlPlaceholders(userContext, dsItem.getUrl()));
            } else if (dataSourceItem instanceof RVJsonDataSourceItem) {
                final RVRESTDataSourceItem dsItem = (RVRESTDataSourceItem)((RVJsonDataSourceItem)dataSourceItem)
                        .getResourceItem();
                // REDACTED VALIDATION
                dsItem.setUrl(RevealUtils.replaceUrlPlaceholders(userContext, dsItem.getUrl()));
            } else {
                log.warn("{}: Unknown data source item class: {}", logId, dataSourceItem.getClass());
                throw new RuntimeException("Unknown data source item class");
            }
            return dataSourceItem;
        } catch (Exception e) {
            log.error("{}: Unhandled exception", logId, e);
            throw e;
        }
    }
}
```

That method `replaceUrlPlaceholders` is the one that changes our placeholders `$orgId` and `$timeZoneId` by actaul values (taken from some values we put in the userContext's properties).

About differences in the environment, the machine, etc, nothing is impossible, but there is no reason why I would think there is a difference outside of Reveal: we instantiate these machines from a common image using an Auto Scaling Group's launch configuration. These machines were instantiated months ago and were behaving well. So the differences among them only start when we deploy new code versions, which I also can see happening in all machines around the same time according to the logs. I also see the jar files deployed to them was the same (I just looked at the sha256sum of the jars).

The reason I can only think of an issue in Reveal is: all machines were working OK, then I deployed new code to all (no code specific to Reveal), and then only 1 machine started behaving weirdly.

**Comment by MLopezIG** [comment]
After inspecting relevant code, we can see one race condition that would lead to your issue. Depending on how concurrent threads run here, you might end up with an Sdk that will never succeed in calling your RestUrlResolver. Coincidentally, we are fixing that for the upcoming 1.6.0, so you'd be able to test it soon. 

Now, while I'm confident that the race condition applies to your scenario and would cause your exact issue (provided our understanding so far is correct), we find it odd that it would happen 100% of the times with a particular server, and never with the other. Not to mention that you need to be a bit unlucky to get the threads to execute in the needed order to get into this bad state.

Another piece of information is that this race condition would either result in a correct initialization of the Sdk or a wrong one, by this I mean that it will either work all of the times, or none.

Maybe you can try your server a little more to support, or falsify our theory about this race condition being the cause of the problem (or just wait a bit for the fix). Here's an idea around that: try starting the machine a few times, and try to hit it with a simple dashboard (one containing a single visualization using this rest data source Item).

**Comment by dwilches** [comment]
Sure, I will start this server tomorrow and see if the issue persists (we stopped it once we noticed the issue).
If this is indeed the issue then this same server could work well when restarted because it may not hit the same race-condition.

**Comment by dwilches** [comment]
Hello,

I restarted the server that had the issues and the issues don't appear anymore. This is consistent with it being a race-condition. We'll work towards using 1.6.0 then.

Thanks.
