### ISSUE TITLE
Add multiselect option in selecting label and values

### ISSUE THREAD

**Issue by elaiyaraja-marimuthu** [RevealBi/Reveal.Sdk#71]
![image](https://github.com/RevealBi/Reveal.Sdk/assets/81211142/57b58a11-eb0c-415b-b1ce-89ce353475aa)
As per business requirement its very difficult to select each fields  for example  1 year monthly data Jan to dec manually we need to select its taking lot of  time to create chart

**Comment by brianlagunas** [comment]
Is this what you are asking for?
![image](https://github.com/RevealBi/Reveal.Sdk/assets/835562/3693e29b-dada-440a-b730-1051f58ef04d)

Also, looking at your screenshot, your data is structured in a way that forces you to do a lot of manual work. If you're able to change the structure of your data, you wouldn't need to add so many fields.

**Comment by brianlagunas** [comment]
Can you clarify the requirements of this request? Can you acknowledge if my screenshot represents your request?

**Comment by brianlagunas** [comment]
I'm closing this request as there has been no response to my questions
