### ISSUE TITLE
Large number formatting and aggregation

### ISSUE THREAD

**Issue by elaiyaraja-marimuthu** [RevealBi/Reveal.Sdk#72]
![image](https://github.com/RevealBi/Reveal.Sdk/assets/81211142/d552a90c-abfd-4e4f-9a13-bf6cf193b183)
Large number formatting and aggregation should be configurable we should not select each field manually its take lot of time

**Comment by TorreyBetts** [comment]
We need to understand your scenario and request a little better. From your picture you're in the dashboard editor, this is used when tweaking an existing dashboard or creating a new one. In this example, you're showing 4 value fields and saying it takes too much time to customize how you'd like those fields to be shown, which would only need done once and should take less than 5 minutes.

1) Are you creating a new dashboard with each use?
2) Where would suggest placing the configuration and how would it be used?

Any additional detail could offer may help us, thanks!

**Comment by elaiyaraja-marimuthu** [comment]
We have 100 fields while adding a label we need to set aggregation and number formatting one by one but i need to configure 20 fields then one by one is difficult.We dont want min or max it should take actual value of field and large number formatting should be configurable

**Comment by brianlagunas** [comment]
Having 100 fields seems like a lot. I wonder if there is a better way to structure your data.

Regardless, we are having a hard time envisioning how this would work. How do you see this working? What would be your ideal API to enable this functionality? What do you want your experience to be?

Currently this seems like an edge case, and I'm not sure we will consider this for implementation.

**Comment by brianlagunas** [comment]
Due to the unclear nature of this request, no real suggestions for it's implementation, and limited benefit to our user base we have decided not to implement this feature. Thank you for you idea, and please keep them coming.
