### ISSUE TITLE
[BUG]: Data filter is showing only 3000 rows

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#74]
### Company

IMSPOS

### SDK Version

1.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Description

When we try to apply data filter , it is only showing 3000 records and it is not showing all the records . Even if we try searching records , it is not displaying 

<img width="483" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/89643622/bc8b6171-9097-4e31-a148-6c02700a47a7">

**Comment by Christianig** [comment]
Hi, the 3k limit on the filter refers to different types of values you are filtering. For example, if there were products, that refers that you have more than 3k products to select. In this case, you have a numeric value. What kind of data source are you using here? Are those values all that large negative numbers?

**Comment by vishwa-ims** [comment]
Hi
It can be number or text . In database we have more than 3000 records but all are not displayed here . We are using SQL Server datasource

**Comment by Christianig** [comment]
You will be able to search values outside that 3k shown. We checked here and the search works for other providers, like XSLX, so there is a bug for SQL Server on this scenario. This will be internally tracked as #AB26549.
Thanks and sorry for the inconvenient.

**Comment by vishwa-ims** [comment]
Thank you Chris. Please help us updated with the status of this bug

**Comment by vishwa-ims** [comment]
@Christianig  Could you please confirm the estimated turn around time ?

**Comment by Christianig** [comment]
We don't have that information yet.

**Comment by vishwa-ims** [comment]
@Christianig do you have any updates on this issue please ?

**Comment by TorreyBetts** [comment]
This bug is currently on slate for fixing in the December release. Priorities can sometimes change which can affect if this is fixed before or after that time. At the least this message should give you a better rough estimate.

**Comment by PVillarmarzo** [comment]
This BUG also affects Redshift

**Comment by PVillarmarzo** [comment]
This issue has been fixed and will be released in an upcoming release.

**Comment by vishwa-ims** [comment]
@PVillarmarzo  Do you have any updates on release please?

**Comment by vishwa-ims** [comment]
Hi @brianlagunas is this issue fixed and released ?

**Comment by PVillarmarzo** [comment]
Hello, the fix is included in version 1.6.2 that has already been released

**Comment by gauxgaux** [comment]
We upgraded to 1.6.2 and noticed that while we can now search for results over 3000 we can't load more - is this the intended fix? @PVillarmarzo

**Comment by brianlagunas** [comment]
Correct. We do not add more than 3000 items to the list UI component itself as that would cause significant UI performance problems. However, the search now works as expected.

**Comment by isabellacarroll** [comment]
We noticed that when you apply a filter to the dashboard, it filters correctly, but the selected value over 3000 is not saved in the filter, even though its applied to the dashboard. If I apply the filter again after opening it, the 3000+ value is not preserved. 
[reveal filter.mov.zip](https://github.com/RevealBi/Reveal.Sdk/files/14425181/reveal.filter.mov.zip)

**Comment by brianlagunas** [comment]
@isabellacarroll 

Great find! Can you submit what you found as a new bug?

Thanks
