### ISSUE TITLE
Conditional Formatting Additional Options 

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#75]
**Describe the solution you'd like**
In addition to the colors for icons that we allow for conditional formatting, we want the option to fill in the whole cell with a color, as you can in Excel. We would also like to control the colors of the font for conditional formatting.

**Comment by brianlagunas** [comment]
Is this for a specific visualization? It sounds like you are talking about the grid or pivot grid. Are there other visualizations that need this?

Is issue #15 the same as your request?

**Comment by brianlagunas** [comment]
I am closing this as a duplicate. As there has been no response, I am going to assume this applies only to Pivot and Grid.
