### ISSUE TITLE
[BUG]: new visualization->sheet selection page, search bar not placed at the correct location after searching for items

### ISSUE THREAD

**Issue by retopara** [RevealBi/Reveal.Sdk#8]
### SDK Version

1.3.1

### Client Framework

HTML/JavaScript

### Server Platform

Java

### Description

Description
Step to reproduce:
1、Open Edge/Chrome in window mode(instead of full screen mode)
2、Click new visualization -> select a data source -> scroll down to select one of the last sheets.
3、Type in characters in the search bar，make sure the search returns no items.
4、Occasionally the search bar jumps down and appears at a much lower location, which could not be seen without zooming out the browser.

See the GIF for a recording.

![Reveal搜索框消失BUG(1)](https://user-images.githubusercontent.com/425233/228810831-889b40f6-3bc6-407d-8336-ffef0b927539.gif)

**Comment by PVillarmarzo** [comment]
This was recently fixed and should be available in the next release.
