### ISSUE TITLE
[BUG]: Reveal WPF SDK - Sql Server: Tables, views, Stored Proc options not visible in dark themes

### ISSUE THREAD

**Issue by fzandomeni** [RevealBi/Reveal.Sdk#81]
### SDK Version

1.4

### Client Framework

Other

### Server Platform

ASP.NET

### Operating System

Linux

### Description

![image](https://github.com/RevealBi/Reveal.Sdk/assets/15477496/e0c8a4ef-c088-4222-bbd1-34e379d5d597)
![image](https://github.com/RevealBi/Reveal.Sdk/assets/15477496/82217208-aef1-43ea-a736-009277ef2042)

See notes on both snapshots. 
Thank you.

**Comment by gkaveckis** [comment]
Hi,
Thanks for reporting it.
The bug AB#26717 was created in our internal system to track it

**Comment by brianlagunas** [comment]
This has been fixed and will be in the next release
