### ISSUE TITLE
Hide table columns from display in the UI

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#86]
**Is your feature request related to a problem? Please describe.**
We have a visualization (a table) that contains several columns, one of which is a Guid value, and an action link column that launches a url when clicked. We need the Guid column only to make the action link work, because the Guid value is used as a parameter in the url. But we don't want to display the Guid column to the user. Right now we are forced to.

**Describe the solution you'd like**
An ability to have a column in your visualization's dataset but hide it from display in the UI.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by brianlagunas** [comment]
Would another perspective of this be that you want to be able to use fields as parameters regardless of if they are part of the visualization or not?

**Comment by agroton-libtax** [comment]
> Would another perspective of this be that you want to be able to use fields as parameters regardless of if they are part of the visualization or not?

Yes, that is correct.

**Comment by brianlagunas** [comment]
This has been implemented and will be available in our next release targeting the first week of ept.
