### ISSUE TITLE
Intercept/modify URL links in dashboards at runtime

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#87]
**Is your feature request related to a problem? Please describe.**
We have dashboards that contain URL links. These links are environment-specific. There is currently no way to intercept them like we do with data sources, which means I have to maintain 3 separate copies (Dev, QA, Prod) of every dashboard to ensure each environment's dashboards have the correct urls.

**Describe the solution you'd like**
I'd like an ability to intercept these links at runtime and swap out the url for the correct environment url. 

**Describe alternatives you've considered**
I tried to use the DOM SDK to replace the urls in the .rdash files when the API starts up, but we had limitations with read/write permissions in our API server environments and ultimately had to scrap that solution. 

**Additional context**
Example:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/068676b5-fc56-4ebc-ae6c-aaa7281fb04d)

**Comment by brianlagunas** [comment]
internal issue AB#26955

**Comment by brianlagunas** [comment]
We have implemented the following function for you to intercept the URLs and modify them:
```
revealView.onUrlLinkRequested = (args) => {
    return args.url + "&webUpdated=true&cellValue=" + args.cell.value();                
};
```
This will be available in our next release.
