### ISSUE TITLE
[BUG]: encoding error

### ISSUE THREAD

**Issue by 1991jhf** [RevealBi/Reveal.Sdk#88]
### SDK Version

1.6

### Client Framework

Angular

### Server Platform

Java

### Operating System

Linux

### Description

here is an encoding error.
![image](https://github.com/RevealBi/Reveal.Sdk/assets/31055890/6f150acb-371c-4ccb-9588-7f0b1d889f4a)

**Comment by luispandolfi** [comment]
Hi @1991jhf, could you provide some more information about your environment? linux distribution, java version, angular version.
Which chart type are you using?
Have you noticed similar encoding errors in other places?

**Comment by brianlagunas** [comment]
@1991jhf were you able to confirm if you had the Roboto fonts installed, and if so did it fix your problem?

**Comment by TorreyBetts** [comment]
The encoding issue is with the greater than or equal type unicode character. That typically means your page is using the wrong encoding. Make sure your HTML pages specify `<meta charset="UTF-8">` within the HEAD tag.

**Comment by brianlagunas** [comment]
Closing as there has been no response.
