### ISSUE TITLE
[BUG]: Extremely slow when loading list of tables with PostgreSQL has hundreds of schema.

### ISSUE THREAD

**Issue by 1991jhf** [RevealBi/Reveal.Sdk#89]
### SDK Version

1.6

### Client Framework

Angular

### Server Platform

Java

### Operating System

Linux

### Description

Is there any way we can pass the schema filter before the Revel BI pull all the meta data from PostgreSQL?
The SQL sent by Revel is extremely slow (few minutes) especially the SQL pull all the stored procedures from database.

**Comment by luispandolfi** [comment]
Internal work item AB#26913

**Comment by srodriguezinfragistics** [comment]
Hi! This issue has been fixed and the changes will be included in an upcoming release.
