### ISSUE TITLE
[BUG]: Exported Excel BI style does not match the selected BI style

### ISSUE THREAD

**Issue by retopara** [RevealBi/Reveal.Sdk#9]
### SDK Version

1.3.1

### Client Framework

HTML/JavaScript

### Server Platform

Java

### Description

SDK Version
1.3.1

Client Framework
HTML/JavaScript

Server Platform
Java

Description
Step to reproduce:

STEP1：click to edit the BI config
![image](https://user-images.githubusercontent.com/425233/229081842-5b3c7bd5-200f-4926-9085-86dfb1ed3744.png)

STEP2：change the BI visualization style, here from column to bar
![image](https://user-images.githubusercontent.com/425233/229081977-f47b1441-05fe-4507-9724-ac342bae03bf.png)

STEP3：export to Excel
![image](https://user-images.githubusercontent.com/425233/229081886-c7bad5a3-f836-47a5-b784-3a00dfe8df0c.png)

STEP4：the exported data still uses columns instead of bar style
![image](https://user-images.githubusercontent.com/425233/229082256-b726132b-1ac6-43a5-a5c5-ebceff51aa4b.png)

**Comment by PVillarmarzo** [comment]
This issue has been fixed and will be available in our next release.
