### ISSUE TITLE
Export individual visualization widget to pdf (or image)

### ISSUE THREAD

**Issue by gauxgaux** [RevealBi/Reveal.Sdk#91]
**Is your feature request related to a problem? Please describe.**
Right now when I want to export a pivot table or grid visualization (NOT THE WHOLE DASHBOARD) that is longer than my screen I can only select image or excel. If I select image it will take a screengrab of only the part that's visible on the screen, not the full table.

**Describe the solution you'd like**
I would like either the image to be a complete image of the visualization or, more likely, an export to pdf option for an individual visualization. 

**Describe alternatives you've considered**
We've been told there's a potential workaround in 1.6.1:  https://github.com/RevealBi/Reveal.Sdk/issues/19

**Additional context**
None

**Comment by brianlagunas** [comment]
Internal work item AB#26959

**Comment by gauxgaux** [comment]
Just wanted to follow up on this. Had a couple of customer complaints about it recently with a direct quote from a customer being:

> I would request that this be reviewed as it really does not provide an export PDF as indicated. The majority of time I can export to Excel, and it is fine but there needs to be a way for users to print other charts and graphs that are created in the reporting section.

**Comment by brianlagunas** [comment]
Does the work-around not unblock you? You can add a custom menu item to the visualizations, then when the menu item is clicked send the visualization ID to your endpoint to perform a server side export which now has support to export a single visualization.

**Comment by gauxgaux** [comment]
Oh I see, I'll work with my team on adding that and get back to you if we get stuck.

**Comment by gauxgaux** [comment]
@brianlagunas - did I hear you're working on a new solution for this?

**Comment by brianlagunas** [comment]
The only feature we have related to this is server side export of single visualization which fixed #19. You can read about it here

https://help.revealbi.io/web/release-notes?code=java#new-features-1

We don't have this built into the client side export yet.

**Comment by PVillarmarzo** [comment]
A new submenu has been added for widget export options. It now includes the option to export to PDF. This change will be part of the next release.

![image](https://github.com/user-attachments/assets/49973f8e-0fe4-4b7a-9f42-9722c0bfd0fa)
![image](https://github.com/user-attachments/assets/2ee877e6-e6f2-4c66-854f-487527abab6c)
