### ISSUE TITLE
[BUG]: Date Sorting is inconsistent in pivot tables and grids

### ISSUE THREAD

**Issue by gauxgaux** [RevealBi/Reveal.Sdk#92]
### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Java

### Operating System

Linux

### Description

I've noticed that sometimes I can sort by dates in pivot table and sometimes I can't. I wasn't able to identify a trend of when it worked and when it didn't. We have a few dates that are date type and most of them are datetime but they all show up correctly identified in Reveal with the little date icon and haven't been the identifying factor (that is to say, sometimes I can sort by dates and note datetimes and vice versa).

I noticed it initially with a customer dashboard but was able to reproduce it in our test environment with the rdash attached. We were able to sort by 2 fields in one of the visuals but not others.

Here is the rdash:
[9c7e68f4-e3de-4831-ac01-ed010243548c.rdash.zip](https://github.com/RevealBi/Reveal.Sdk/files/12729550/9c7e68f4-e3de-4831-ac01-ed010243548c.rdash.zip)

And this is the field definitions: 

```
{
	"IsHidden": true,
	"IsCalculated": false,
	"Properties": {
		"DataType": "timestamp"
	},
	"FieldName": "draft_date",
	"FieldType": "DateTime",
	"Sorting": "None"
}, {
	"IsHidden": true,
	"IsCalculated": false,
	"Properties": {
		"DataType": "timestamp"
	},
	"FieldName": "submission_date",
	"FieldType": "DateTime",
	"Sorting": "None"
}, {
	"IsHidden": true,
	"IsCalculated": false,
	"Properties": {
		"DataType": "timestamp"
	},
	"FieldName": "inprogress_date",
	"FieldType": "DateTime",
	"Sorting": "None"
}, {
	"IsHidden": true,
	"IsCalculated": false,
	"Properties": {
		"DataType": "timestamp"
	},
	"FieldName": "decision_date",
	"FieldType": "DateTime",
	"Sorting": "None"
}
```

**Comment by brianlagunas** [comment]
Does the "Sort" field show up in the UI or it is missing? I'm trying to understand if the Sort property is set, but not being respected, or if there is just no way to sort the field.

**Comment by gauxgaux** [comment]
Yep, it was in the UI and even shows the Up or Down arrow when I click it, it just doesn't actually sort.

**Comment by PVillarmarzo** [comment]
An internal issue was created regarding this report. Tracked with AB#27263

**Comment by agroton-libtax** [comment]
Also experiencing this bug in environment:
**SDK Version:** 1.6.0
**Client:** Angular
**Server:** ASP.NET
**OS:** Windows

**Comment by agroton-libtax** [comment]
Any updates on this?? Timeline for a fix?

**Comment by TorreyBetts** [comment]
@gauxgaux When this sorting issue occurs, are you viewing a dashboard (and applying client sorts or using what was defined in the dashboard), or edit a visualization in the editor, or going from the editor back to dashboard?

**Comment by gauxgaux** [comment]
@TorreyBetts - we are sorting from view only - not the edit view. Sorting in edit view doesn't work.
