### ISSUE TITLE
Support for calculated fields using "fyear" function on a SQL Server data source with "Process Data on Server" enabled

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#93]
**Is your feature request related to a problem? Please describe.**
We need to use the "fyear" function to create a calculated field on a dashboard visualization. However, because our data source is SQL Server, we have to disable the "Process Data on Server" option in order to use "fyear". We are unable to take advantage of the "Process Data on Server" feature due to this limitation. 

**Describe the solution you'd like**
When working with a SQL Server data source, I'd like to be able to use the "fyear" function in a calculated field even if I have "Process Data on Server" enabled.

**Describe alternatives you've considered**
Modifying the data source or creating a new one (such as a View) so that we don't need to use "fyear" function, but this isn't always possible or feasible due to time/cost constraints

**Additional context**

**Comment by brianlagunas** [comment]
Tracking with internal issue AB#26962
