### ISSUE TITLE
[BUG]: Joining Two SQL Server Stored Procs in Slingshot doesn't allow edits to be saved

### ISSUE THREAD

**Issue by jjAtNxtPt** [RevealBi/Reveal.Sdk#94]
### SDK Version

1.6.0

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We are connecting to SQL Server and using two stored procedures.  When I create a join between the two in one widget I can make changes and create what I wanted.  However, when I save everything and either refresh the dashboard OR close and reopen it, I lose all the changes I made prior to creating the join.  This start happening yesterday, didn't happen before that.  If that's not weird enough, when I go back into the widget to re-create the join, it shows that the join is already there.  When I'm in the widget editing view, if I refresh the data the join returns, along with all my prior edits.  However, when I save (again) and refresh the dashboard, they disappear again.

I ran across this issue while trying to figure out why the original widget that I created with a join like this works in my Slingshot environment but doesn't in our embedded app.

As a test, I removed the join and the column created from that join in the original widget and it worked fine, no issues.  So, the issue looks like it has to do with joining the two stored procedure sources for one widget.

**Comment by PVillarmarzo** [comment]
I would appreciate it if you could let us know how you implement the save option. Perhaps you could send us a screenshot of the implementation.

**Comment by jjAtNxtPt** [comment]
I hope I'm understanding you correctly when you say "save option".  Whenever I make an edit to a visualization or a dashboard in Slingshot itself there is a check mark and an X at the top right corner of the screen.  I click the check mark to save the edits I've made.

  *   from the dashboard screen:  [cid:70dc608f-9871-4c20-852f-1c42e41f6431]

  *   from the visualization screen:  [cid:85f2a855-3914-4a42-a91d-a26230218988]

In the scenario that I was having issues with, not sure if it's still going on, I was making the edits, clicking the check mark once for the visual and another for the dashboard.  Then, when I closed out the dashboard and re-opened it all of the edits would be gone and it was to the same state as before I made any edits.  However, when I opened the visual to re-make the edits they were back.  After playing with it over and over again found that when the dashboard was refreshed, either by closing and reopening or by clicking the refresh button before closing, the edits disappeared.

I'm not sure that it's still happening, though.  I have a dashboard with that same join in it now and the column doesn't seem to be disappearing like it did when I posted the bug.

Hopefully, that helps.

Thanks,

James Johnson
Sr. SAS Programmer
(817) 803-4432
500 Grapevine Hwy | Hurst, TX 76054
2387 Liberty Way | Virginia Beach, VA 23456
[NextPoint Acquisition Corp. - Home]

________________________________

**Comment by PVillarmarzo** [comment]
The error occurred only in the embedded app, right? Given that you may have implemented different ways to save dashboards (https://help.revealbi.io/web/saving-dashboards), I assumed that the problem could lie in those implementations. This led to my earlier request.

Please, when you can, confirm if the error still persists or if it was a specific issue.

**Comment by jjAtNxtPt** [comment]
The bug I entered (subject line) had to do with Slingshot itself, not necessarily Reveal.  Actually, I don't know if it had to do with Reveal or not, but it was definitely happening in Slingshot.

Right now I can confirm that the bug I entered that wasn't allowing the edits to be saved when two SQL SPROCs are joined is NOT happening.  I'm looking at an updated dashboard that has the two SPROCs joined with at least one column from the additional table in the pivot/grid and they aren't disappearing like they were.  I don't remember doing anything different than before so I can't give a reason why the issue/bug isn't happening now.

James Johnson
Sr. SAS Programmer
(817) 803-4432
500 Grapevine Hwy | Hurst, TX 76054
2387 Liberty Way | Virginia Beach, VA 23456
[NextPoint Acquisition Corp. - Home]


________________________________

**Comment by brianlagunas** [comment]
Thanks for the information. I'll close this issue. If you need anythign else, let us know.
