### ISSUE TITLE
Support for calculated fields using date functions on a SQL Server data source with "Process Data on Server" enabled

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#97]
**Is your feature request related to a problem? Please describe.**
We need to use date functions to create calculated fields on a dashboard visualization. However, because our data source is SQL Server, we have to disable the "Process Data on Server" option in order to use many of these. These include:
- date()
- time()
- hour()
- minute()
- second()
- formatdate()
- datevalue()

We are unable to take advantage of the "Process Data on Server" feature due to this limitation. Note that ideally we'd like to be able to use any of the date functions, I just listed the ones we have already found a need for.

**Describe the solution you'd like**
When working with a SQL Server data source, I'd like to be able to use the date functions listed above in a calculated field even if I have "Process Data on Server" enabled.

**Describe alternatives you've considered**
Modifying the data source or creating a new one (such as a View) so that we don't need to use these functions, but this isn't always possible or feasible due to time/cost constraints

**Additional context**

**Comment by brianlagunas** [comment]
Tracking with internal issue [AB#26962](https://infragistics.visualstudio.com/14a7928c-44bc-4aed-b2ca-9a0ffbb14d7a/_workitems/edit/26962)

**Comment by brianlagunas** [comment]
This has be implemented and will be available in our next release. We even added milliseconds 😄
