### ISSUE TITLE
[BUG]: Linked dashboards get saved with a Guid instead of Dashboard/.rdash Name

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#98]
### SDK Version

1.6.0

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Linked dashboards get saved with a GUID instead of the rdash file name. For example, if I've got a dashboard named "Marketing" and I want to link to another one named "Campaigns", the link gets saved with "id:8c623e37-7efa-47eb-7185-108ff5b37e97" instead of "id:Campaigns". _Note that we are creating dashboards in Slingshot, and we originally brought up this issue to Slingshot support, but they directed us to make a report here saying it was a Reveal issue in general._
 
Our problem is when you use the two dashboards together in Reveal on the web application the Reveal SDK passes in the id "8c623e37-7efa-47eb-7185-108ff5b37e97" from the .rdash file instead of "Campaigns" which is not the name of the rdash file in the Dashboards directory.

We were able to get around this by creating a lookup, and mapping both the dashboard name and the GUID to the appropriate rdash file. But it would be nice to not have to do this extra step.

**Comment by brianlagunas** [comment]
I'm not sure why they told you this is a Reveal issue. Slingshot is a stand-alone application that uses the Reveal SDK as a feature of it's offering. We have no control over how the Slingshot app is saving the linked dashboards. The Reveal SDK does not have a built-in dashboard linking function. The end developer must implement the linking. Slingshot has actually customized their implementation of the Reveal SDK to the point where there are incompatibilities between Slingshot dashboards and native Reveal SDK dashboards. I thin you have run into a few of these issues yourself.

Unfortunately, this is not something we can address.

By the way, do you know that name of the person that told you that?

**Comment by brianlagunas** [comment]
The `onLinkeddashboardProviderAsync` event has two parameters, one if the ID and the other is the title.  Can you just use the title instead of the ID?

```
  revealView.onLinkedDashboardProviderAsync = (dashboardId, title) => {
     //maybe do a check for the ID to see if it's a guid or not
      return $.ig.RVDashboard.loadDashboard(title);
  };
```
