### ISSUE TITLE
[BUG]: When using Pivot visualization, it does not resize appropriately based on window size

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#99]
### SDK Version

1.6.0

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We have several dashboards with a Pivot at the top and a Grid below it. The Pivot does not resize nicely when the browser window is resized and the visualizations auto-arrange. 

If screen is large enough, the visualizations are arranged into two rows, one column and you can see the Pivot in its entirety.
1920px x 931px
![Screenshot 2023-10-03 at 3 07 23 PM](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/35a11f99-bd97-4acd-9288-b1e641e42034)

If I shorten the window a lot, the visualizations rearrange into a single row of two columns, which is good.
1920px x 684px
![Screenshot 2023-10-03 at 3 10 21 PM](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/89830a27-a996-4eca-a081-fcf374aaef11)

But if I shorten it a lesser amount, the pivot visualization is awkwardly cut off.
1920px x 785px:
![Screenshot 2023-10-03 at 3 13 27 PM](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/1edd3dd8-caf7-4b4f-8753-fd49c859f66e)

I would expect that for a grid or pivot (any table-like visualization), the height of the visualization would not be reduced past the point where you wouldn't see one row of data. Otherwise it looks very awkward.

Video:
https://github.com/RevealBi/Reveal.Sdk/assets/136626707/625502ac-b20e-4790-b9ad-7f60482035ee

**Comment by PVillarmarzo** [comment]
An internal issue was created regarding this report. Tracked with AB#27284

**Comment by brianlagunas** [comment]
Thanks for reporting this issue. We spent a lot of time trying to fix this, but turns out the issue is deep in our internal layout engine and trying to fix this would be extremely risky and would require a rewrite of our layout engine. Due to the time and risk factors we have decided to not fix this bug and leave it as a known issue. I am sorry for the inconvenience this may have caused you.
